const fs = require('fs');
const path = require('path');

const espDir = path.join(__dirname, 'app', 'src', 'data', 'clubes', 'espania');

const fixes = {
    'osasuna': "La historia de este estandarte navarro comenzó en las mesas del céntrico Café Kutz, en la ciudad de Pamplona. El 24 de octubre de 1920, tras varias tertulias, pioneros como Marcos Eizaguirre, el periodista Benjamín Andoian Martínez y Eduardo Aizpún conformaron un nuevo equipo producto de la unificación entre el Sportiva Foot-Ball Club y el New Club. En esa misma reunión, Benjamín Andoian propuso un nombre de milenaria raíz euskera: 'Osasuna' (que significa Salud, Vigor y Fuerza), sellando para siempre la identidad de un equipo forjado bajo una mística inquebrantable de tenacidad e identidad local.",
    'rayo-vallecano': "En el corazón proletario de Vallecas, un 29 de mayo de 1924, un grupo de jornaleros e hinchas locales liderados por Prudencio Priego concibieron la Agrupación Deportiva Rayo Vallecano. En sus humildes inicios formales en las calles de tierra madrileñas, la entidad forjó su identidad al compás del esfuerzo obrero. Posteriormente, en un acuerdo histórico con el Atlético de Madrid, adoptaron la inmortal franja roja cruzada en el pecho, un emblema que con el tiempo los identificaría como el heroico 'Matagigantes' del barrio.",
    'real-betis': "El origen del Real Betis Balompié es producto de fusiones y rebeliones estudiantiles a principios del siglo XX. En 1907, alumnos sevillanos apartados de otros clubes elitistas fundaron el 'Sevilla Balompié' bajo el amparo de la Academia Politécnica. Paralelamente nacería el Betis Football Club. Fue la sublime unificación de ambas entidades bajo la mediación de Eladio García de la Borbolla lo que conformó definitivamente al club. Asumiendo la palabra romana 'Baetis' (río Guadalquivir) y los colores verde y blanco, sentenciaron su eterna mística guerrera bajo el lema popular '¡Viva el Betis manque pierda!'.",
    'real-madrid': "El equipo más laureado del mundo conoció sus raíces lejos de las cortes imperiales, naciendo en los descampados de la Institución Libre de Enseñanza a fines del siglo XIX bajo el amparo del club clandestino 'Foot-Ball Sky' presidido por Julián Palacios. La entidad alcanzó su legalidad y estructuración definitiva el 6 de marzo de 1902 gracias al impulso fundamental de los pioneros hermanos Juan y Carlos Padrós. Con la indumentaria inmaculada inspirada en el legendario Corinthian inglés, el recién denominado 'Madrid Foot-ball Club' inició un camino que lo terminaría erigiendo como el rey indiscutido del fútbol europeo.",
    'real-sociedad': "A merced de la playa de La Concha, encarnó su nacimiento la escuadra representativa del territorio de Guipúzcoa. Forjados a partir de ciclistas y deportistas escindidos del originario Club Ciclista en San Sebastián, el nacimiento oficial como 'Sociedad de Fútbol' aconteció el 7 de septiembre de 1909 gracias a fundadores de la talla de Tomás Guruceta y Adolfo Sáenz Alonso. Enfundados en sus listones blanquiazules (txuri-urdin), el club forjó rápidamente una política deportiva férrea, sentando las bases de una entidad clásica e irremplazable en el norte de la península.",
    'real-valladolid': "El nacimiento del coloso de Castilla es fruto de una excepcional cordura cívica y deportiva. En 1928, la incipiente escena vallisoletana desgastaba sus fuerzas en las pujas fratricidas entre sus dos entidades más poderosas: la Real Unión Deportiva y el Club Deportivo Español. Gracias a las intensas gestiones diplomáticas del insigne pacificador organizativo Pedro Zuloaga, el 20 de junio de 1928 se obró el milagro de la unificación. Nació así el Real Valladolid, asumiendo los clásicos tonos violeta y blanco y congregando a todos los ciudadanos bajo un único blasón representativo en el panorama nacional.",
    'sevilla': "El sevillismo gestó sus raíces más profundas en medio de las históricas delegaciones británicas andaluzas. La noche del 25 de enero de 1890, durante la festividad escocesa de Burns Night, un grupo de pioneros británicos liderados por Edward Farquharson Johnston, Hugo MacColl e Isaías White rubricaron la creación del Sevilla Football Club. Johnston asumió como primer presidente de esta escuadra pionera, que semanas después disputaría ante el Recreativo de Huelva el primer partido bajo reglas oficiales en suelo español. Este sólido nacimiento cimentó la poderosa institución blanquirroja que dominaría el sur durante el siguiente siglo.",
    'valencia': "El nacimiento del conjunto ché se dictaminó de un modo tan singular como histórico. En las mesas del legendario Bar Torino de la ciudad, un 18 de marzo de 1919, un entusiasta grupo de pioneros formalizó la creación del Valencia Foot-Ball Club. Ante la indecisión sobre quién ocuparía la primera presidencia, la disputa entre Octavio Augusto Milego Díaz y Gonzalo Medina Pernas se resolvió de forma azarosa mediante el lanzamiento de una moneda al aire. Milego ganó el sorteo y asumió el liderazgo fundacional, impulsando a la institución blanquinegra bajo la sombra del poderoso murciélago.",
    'villarreal': "El origen de la entidad se remonta a la tranquilidad provinciana de la ciudad castellonense a principios de 1923. Impulsado por el fervor visionario del boticario local José Calduch Almela y un círculo de amigos que utilizaban la trastienda de su farmacia 'La Botica' como improvisado salón de asambleas, el viejo Club Deportivo de Villarreal fue fundado oficialmente el 10 de marzo de ese mismo año. Aunque en sus primeros tiempos el incipiente equipo vestía camisa blanca y pantalón negro, rápidamente consolidaría el color amarillo que lo convertiría más de medio siglo después en uno de los proyectos modernos más temidos de Europa.",
    'celta-vigo': "Su nacimiento es el relato de un acuerdo cívico ejemplar para defender deportivamente a toda una región. En 1923, la ciudad sufría la cruenta rivalidad entre sus dos gigantes: el Real Vigo Sporting Club y el Real Club Fortuna de Vigo. El magistral periodista Manuel de Castro 'Handicap' pregonó durante meses la unión total, la cual fue rubricada el 23 de agosto de 1923 en los salones de la Federación. Liderados por Juan Baliño Ledo y Pepe Bar, ambos clubes renunciaron a su historia para amalgamar fuerzas enfundándose bajo una nueva armadura celeste, bautizados como 'Celta' en claro tributo a sus ancestros gallegos.",
    'getafe': "Tras la dolorosa desaparición en 1983 del antiguo Club Getafe Deportivo, la tristeza futbolera en el cinturón sur de Madrid duró apenas treinta días. La humilde taberna 'Peña Morate' fue el refugio donde el 8 de julio de 1983, un inquebrantable grupo de aficionados liderados por Antonio de Miguel, Enrique Fanjul y el exalcalde Jesús Prieto, firmó la refundación total bajo la nomenclatura actual de Getafe Club de Fútbol. Comenzando de nuevo desde el eslabón más bajo del fútbol regional, forjaron un club espartano que lograría acceder a la máxima élite europea respaldando por siempre su tradicional camiseta azul.",
    'girona': "El 23 de julio de 1930, en medio del dinamismo social local, nació el equipo destinado a llevar el escudo de la ciudad a la primera plana catalana. La asamblea fundacional tuvo lugar en las populares mesas del Café Norat, en las Ramblas. Allí, encabezados por su flamante presidente Albert de Quintana de León, junto a escuderos históricos como Joaquim Ribas y Andreu de Bosch, forjaron los estatutos del Girona Football Club. Inspirados directamente en el antiguo escudo de armas municipal, adoptaron los formidables colores albirrojos, proyectando la creación de un reducto fortificado de jerarquía indiscutible.",
    'las-palmas': "En la convulsa década de los cuarenta, el talento insular sufría un constante éxodo hacia la España peninsular. Tratando de blindar su patrimonio deportivo, el visionario dirigente Manuel Rodríguez Monroy propuso una alianza sin precedentes. El 22 de agosto de 1949, cinco equipos históricos de la isla —Real Club Victoria, Arenas Club, Club Deportivo Gran Canaria, Atlético Club de Schamann y Marino Fútbol Club— sacrificaron sus identidades jurídicas para fundar orgánicamente la Unión Deportiva Las Palmas. Sembraron de esa forma un inmenso acorazado insular vestido al azul y amarillo de sus mares y playas pacíficas.",
    'leganes': "El origen de los populares pepineros transcurrió bajo la brisa de los llanos agrícolas del sur madrileño. Conformado por un núcleo de emprendedores y agricultores locales, el 23 de junio de 1928 se gestó estatutariamente el Club Deportivo Leganés. Bajo la estricta conducción de su primer y devoto presidente, Ramón del Hierro, y sus laderos agricultores, los fundadores adoptaron los identificatorios colores blanquiazules. La institución forjó una relación muy humilde e indisoluble con su origen trabajador hortelano, consolidando una mística de ascensión obrera para superar una a una todas las escalas del ascenso ibérico.",
    'alaves': "El fútbol arribó a Vitoria a principios de siglo, pero su consolidación definitiva estalló en los albores de los años veinte. Impulsados por un contingente desprendido del 'Sport Friends Club', pioneros como José Gabriel de Guinea, Amadeo García de Salazar y Hilario Dorado proclamaron el nacimiento del Deportivo Alavés el 23 de enero de 1921. Sentados en la tenencia de la alcaldía local, acordaron vestir la camisa albiazul, diseñando cuidadosamente una institución transversal que amparara con euforia social tanto a la burguesía vizcaína como a los trabajadores de pie, cimentando un orgullo de resistencia que mereció ser vitoreado luego como 'El Glorioso'."
};

for (const [slug, newDesc] of Object.entries(fixes)) {
    const jsonPath = path.join(espDir, `${slug}.json`);
    if(fs.existsSync(jsonPath)) {
        let data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
        if (data.historia && data.historia.length > 0) {
            data.historia[0].desc = newDesc; // Apply the clean fix to the first element (which is always foundation)
            fs.writeFileSync(jsonPath, JSON.stringify(data, null, 2), 'utf8');
            console.log(`Punto 1 Fixed para: ${slug}`);
        }
    }
}
