const fs = require('fs');

const data = {
  "real-madrid": "En la llovizna fundacional de fines del siglo XIX, la élite académica de la Institución Libre de Enseñanza comenzó a ensayar un extraño juego inglés en los descampados madrileños, formando el clandestino 'Foot-Ball Sky' bajo la mirada atenta de Julián Palacios. Sin embargo, la cristalización monumental del equipo más laureado del orbe definitivo ocurrió el 6 de marzo de 1902. Reunidos en la modesta trastienda de la tienda de modas 'Al Capricho' en la calle Alcalá, los hermanos catalanes Juan y Carlos Padrós, junto a fundadores históricos como Adolfo Meléndez, Enrique Varela y Arturo Meléndez, rubricaron la creación del 'Madrid Foot-ball Club'. Inspirados visualmente por el prestigioso Corinthian FC de Londres, adoptaron el color inmaculado y un escudo entrelazado. Apenas comenzaron a pisar el césped de la antigua Plaza de Toros, impusieron una aristocracia deportiva que, veinte años más tarde, convencería al propio Rey Alfonso XIII de otorgarles el título real, sentenciando la eternidad la corona del Rey indiscutido de Europa.",
  "valencia": "La llanura costera del Turia observaba con intriga la fiebre por el balón. La génesis del conjunto che fue tan bohemia como magnética. La tarde del 18 de marzo de 1919, las bulliciosas mesas del céntrico Bar Torino, en plena Plaza del Ayuntamiento, sirvieron de cuna para el nacimiento ineludible del Valencia Foot-Ball Club. Ante la falta de un líder absoluto, la primera presidencia se resolvió de forma mítica e hilarante mediante el azaroso lanzamiento de una moneda al aire. El lado ganador de la moneda coronó a Octavio Augusto Milego Díaz como primer presidente, relegando a su íntimo amigo Gonzalo Medina Pernas a la vicepresidencia. Acompañados de padres fundadores de la talla de Julio Gascó, Fernando Marzal y Andrés Bonilla, los pioneros acordaron vestir la casaca blanca y enarbolar en el pecho la sagrada imagen del murciélago (lo rat penat), animal heráldico y monárquico del Reino de Valencia. Erigieron así las barreras de un club temperamental y volcánico que dominaría la cuenca mediterránea.",
  "sevilla": "La Giralda y los aromas del sur de España atestiguaron uno de los orígenes deportivos más aristocráticos y tempraneros del país. En el corazón de las florecientes delegaciones comerciales británicas, la histórica noche del 25 de enero de 1890 se vistió de gala. Durante las tradicionales celebraciones escocesas de la 'Burns Night' en un céntrico café, la élite empresarial naval impulsó el nacimiento del Sevilla Football Club. La fundación fue liderada incansablemente por pioneros británicos legendarios: el naviero Edward Farquharson Johnston como primer presidente supremo, secundado por el tesorero Hugo MacColl y el entusiasta secretario Isaías White Méndez. Apenas unas semanas después, firmaron la historia dorada al disputar contra el vecino Recreativo de Huelva el primer partido bajo estatutos oficiales que jamás se hubiera jugado en suelo peninsular, triunfando bajo la intensa lluvia en Tablada. Forjados en la cultura industrial extranjera pero arropados por la sangre nervionense, la escuadra consolidó rápidamente el escudo que monopolizaría la gloria eterna en toda Andalucía.",
  "osasuna": "La férrea y orgullosa tierra de Navarra carecía de un estandarte unificado hasta la noche clave del 24 de octubre de 1920. El murmullo tenso de las tertulias taurinas y fiesteras se acalló en las céntricas mesas del legendario Café Kutz, frente a la mismísima Plaza del Castillo en Pamplona. Allí, un grupo de románticos pioneros logró el milagro de unificar el coraje del 'Sportiva Foot-Ball Club' y la destreza del 'New Club' en un solo puño inquebrantable. Bajo la pluma y la visión de próceres fundacionales como el periodista Benjamín Andoian Martínez, Marcos Eizaguirre, Eduardo Aizpún, Joaquín Rasero y el primer presidente Eusebio Sánchez, se firmó el pacto fundacional rojillo. Fue el propio Andoian quien asestó el golpe maestro proponiendo un nombre de milenaria raíz euskera, desterrando de cuajo todo anglicismo: 'Osasuna' (que clama por la Salud, el Vigor y la Fuerza bruta universal). Así, entre copas y puros, nació un club de pura cepa, destinado irremisiblemente a representar la tenacidad navarra.",
  "alaves": "El frío sepulcral y la elegante burguesía de Vitoria fueron el caldo de cultivo ideal para un grito de identidad. Aunque el fútbol trotaba tímidamente desde 1913 bajo el formato del primitivo 'Sport Friends Club', la ebullición absoluta ocurrió en los despachos de la mismísima tenencia de alcaldía en enero de 1921. Con un hambre voraz por plantar cara a los vecinos bilbaínos, próceres institucionales de la talla de José Gabriel de Guinea, el icónico y visionario Amadeo García de Salazar, junto a pioneros incansables como Hilario Dorado y Carmelo Leza, rubricaron el parto oficial del 'Deportivo Alavés'. Se conjuraron bajo un emblema transversal que buscaba derribar las barreras clasistas: amparar por igual el fervor de los obreros de la metalurgia local y la ilusión de la alta sociedad vizcaína. Enfundados originalmente con camisetas regaladas por la Real Sociedad, cimentaron el irrenunciable honor albiazul, erigiendo una máquina defensiva tan heroica, áspera e indomable, que en poco tiempo mereció el apodo eterno de 'El Glorioso'.",
  "celta-vigo": "El oleaje atlántico empujó un pacto cívico y deportivo sin parangón en las rías gallegas. Entrada la década de los veinte, la ciudad marinera sufría el sangriento cisma competitivo entre sus dos tótems ineludibles: el aristócrata 'Real Vigo Sporting Club' y el ferviente 'Real Club Fortuna de Vigo'. Sabedor de que divididos eran presa fácil ante los poderes castellanos y vascos, el brillante periodista deportivo Manuel de Castro, apodado históricamente 'Handicap', lideró una cruzada diplomática incansable por la hermandad. Su utopía se concretó el vibrante 23 de agosto de 1923, en los solemnes salones de la Federación Gallega. Custodiados por pilares fundamentales como Juan Baliño Ledo y el inmortal Pepe Bar, ambas directivas firmaron la claudicación de sus propios colores en nombre de un escudo invencible y supremo que protegiera a toda Galicia. Renegaron del anglicismo 'Foot-ball' y, enarbolando un brutal orgullo ancestral, lo bautizaron solemnemente bajo el peso celta. Tiñeron su ropa con el color exacto del gélido cielo gallego en honra perpetua a su mar.",
  "villarreal": "Lejos del bullicio industrial, el municipio castellonense gestó su inmortalidad corporativa entre el aroma penetrante a medicamentos y fórmulas maestras. En los apacibles inicios de 1923, la trastienda de la farmacia local 'La Botica' se transformó mágicamente en la asamblea clandestina de la juventud soñadora apasionada por el fútbol. Impulsados incansablemente por el fervor visionario y altruista del boticario José Calduch Almela, y secundados por un círculo irreductible de próceres fundacionales como Pascual Font de Mora, José Llorca y Enrique Segarra, se sentaron las bases definitivas el 10 de marzo para rubricar oficialmente el Club Deportivo de Villarreal. Adquiriendo los yermos terrenos comunales para instalar El Madrigal, los primeros futbolistas, enfundados con camisas blancas remendadas y rudimentarios pantalones negros que sus propias madres hilaban, comenzaron a dictar sentencias deportivas sobre la arcilla. Posteriormente transmutarían al glorioso e incandescente amarillo oro que los convertiría de campesinos al letal, respetado y temido monstruo táctico pan-europeo rebautizado mundialmente hoy como el 'Submarino Amarillo'.",
  "getafe": "En pleno corazón del arrabal proletario y del resistente cinturón sur de Madrid, el colapso financiero amenazaba con exterminar al fútbol local en 1983. Ante las cenizas desgarradoras del antiguo e histórico Club Getafe Deportivo, la tristeza popular no detuvo la fuerza obrera. El calor y el aroma de la legendaria taberna 'Peña Morate' sirvió como guarida insurreccional. Allí, en una trinchera cubierta de aserrín y pasiones rotas, un inquebrantable grupo de hinchas de clase trabajadora liderados ciegamente por Antonio de Miguel, el perseverante Enrique Fanjul y el salvador y exalcalde municipal Jesús Prieto, firmaron un acta precaria pero dotada de amor incesable el caluroso 8 de julio de 1983. Refundaron completamente de la nada, con los bolsillos pelados, al moderno 'Getafe Club de Fútbol'. Arrastrando escudos heráldicos cubiertos de polvo, forjaron un club espartano partiendo exactamente desde el fondo infernal e invisible amateur madrileño, destrozando barreras a pura sangre hasta codearse contra los transatlánticos europeos enfundados en esa armadura azulina insoslayable e innegociable.",
  "girona": "El clamor independentista y el fervor catalán buscaban de manera acuciante una voz representante en la rica llanura del río Onyar. Tras la disolución trágica de la previa Unión Esportiva, las bases fundacionales para un frente impenetrable se plantaron bajo el arco cálido y bohemio del mítico Café Norat, un emblema vital que latía incesante sobre la Rambla de la Llibertat. En ese bullicio ciudadano, el 23 de julio de 1930, se consolidó la gran asamblea madre ciudadana. Guiados magistralmente por la elocuencia de su flamante primer presidente Albert de Quintana de León, y flanqueados en la pesada batalla burocrática por escuderos eternos e inversores claves como los empresarios Joaquim Ribas, Andreu de Bosch, Lluís de Puig y Manuel de Chopitea, el Girona Football Club exhaló su poderoso primer latido oficial. Absorbiendo directamente los estandartes romboideos escuderos municipales, los creadores adoptaron orgullosamente las casacas albirrojas de identidad total, sellando para siempre el compromiso moral, catalanista y estoico de fortificar el estadio perenne de Montilivi.",
  "real-betis": "Los restrictivos vientos universitarios de minorías élites que corrían por los cerrados salones de Sevilla sembraron indirectamente la más romántica rebelión del balompié popular. En 1907, asfixiados de la opresión local selecta, un cúmulo de alumnos apartados y excluidos fundaron el incipiente 'Sevilla Balompié' forjado a fuego lento en el crisol libre de la Academia Politécnica. A la par nacería el indomable Betis Football Club impulsado por el romanticismo incansable de la familia Alarcón de la Lastra. Fue la colosal ingeniería comunitaria bajo el ala protectora de Eladio García de la Borbolla, sumado al aporte pionero de José Gutiérrez y Hermosa, la que terminó uniendo ambas pasiones marginadas conformando el masivo Real Betis Balompié. Asumiendo orgullosamente la imponente palabra romana antigua 'Baetis', herencia sagrada natural del paso del río Guadalquivir, se envolvieron en místicas líneas verticales verdes y blancas. Rubricaron una idiosincrasia tribal, obrera, andaluza, sufriente pero de amor absoluto resumida para la eternidad planetaria en su estruendo oficial de '¡Viva el Betis manque pierda!'.",
  "real-sociedad": "Las gélidas mareas cantábricas y la apacible brisa de la preciosa playa de La Concha acunaron una fundación pionera forjada en el barro donostiarra. Hartos de disputar precarios recintos prestados y conformados velozmente a partir de atléticos y románticos deportistas escindidos del originario Club Ciclista en San Sebastián, el parto oficial y glorioso como 'Sociedad de Fútbol' atronó y retumbó por los pasillos vascos la lluviosa tarde del 7 de septiembre de 1909. La engorrosa pluma burocrática recayó irremediablemente sobre los hombros fundacionales del tenaz presidente Adolfo Sáenz Alonso, quien gozaba del indispensable y estricto coraje organizativo de próceres legendarios como Tomás Guruceta y Primitivo Gafoz. Enfundados visual y sagradamente desde sus raíces absolutas en la gloriosa indumentaria de listones blanquiazules (aquella mítica txuri-urdin irrenunciable), esta casta visionaria selló los pilares inquebrantables de un fútbol regional cerrado y heroico, garantizando el respeto de una institución cívica impoluta que destella honor, linaje vasco intocable e insufla terror a cualquier potencia europea.",
  "rayo-vallecano": "El latido proletario estallaba colapsando de presión las arterias de Madrid desde su margen sur polvoriento y barrial. A un abismo de distancia de la cuna acaudalada del centro ostentoso, la incansable agitación vecinal de un innegociable orgullo comunero vio la luz el cálido 29 de mayo de 1924, exactamente en el lecho entrañable de la legendaria doña Elvira. Guiados bajo la astuta pasión asfáltica de Primitivo y Prudencio Priego (primer presidente, ideólogo fundador), flanqueados incansablemente en asambleas humildes por pioneros y peones obreros valientes como Julio Cuitiño, Amadeo Sánchez, Modesto Rodríguez y José Salvo, se conformó con un par de moneditas solidarias la Agrupación Deportiva Rayo Vallecano. En sus crudos inicios formales transitaban los baldíos y potreros envueltos en camisas ajadas puramente blancas. Sería luego de un acuerdo con el Atlético, e inspirados ciegamente en River Plate, cuando incrustarían de por vida la estruendosa franja roja relámpago cruzando el pecho, consagrando mundialmente el alma guerrillera de un bloque barrial rebelde antifascista, el eterno Matagigantes de Vallecas."
};

const dir = 'app/src/data/clubes/espania/';
let modded = 0;
for (const [id, newText] of Object.entries(data)) {
  const file = dir + id + '.json';
  if (fs.existsSync(file)) {
    const json = JSON.parse(fs.readFileSync(file));
    if (json.historia && json.historia.length > 0) {
      json.historia[0].desc = newText;
      fs.writeFileSync(file, JSON.stringify(json, null, 2));
      modded++;
      console.log(`Reescrito nivel Bilbao: ${id}`);
    }
  }
}
console.log(`\nReescritos exitosamente ${modded} clubes.`);

