const fs = require('fs');

const d = {
  "celtic": {
    "idolos": [
      { "nombre": "Henrik Larsson", "desc": "Fichado en 1997 del Feyenoord, permaneció siete campañas hasta 2004. Anotó 242 goles en 315 encuentros oficiales y lideró el camino a la final de la Copa de la UEFA 2003 marcando un doblete crucial frente al FC Porto." },
      { "nombre": "Jimmy Johnstone", "desc": "Extremo derecho titular (1962-1975) con 515 exhibiciones. Pieza nuclear de los legendarios Leones de 1967; ese mismo año finalizó tercero en el premio Balón de Oro europeo, destacándose estadísticamente por su velocidad explosiva y gambeta técnica." },
      { "nombre": "Kenny Dalglish", "desc": "Atacante surgido de la cantera, integrante del plantel mayor de 1969 a 1977. Acumuló 318 participaciones y 167 dianas coronándose cuatro veces en Primera División nacional previo a concretar su millonario traspaso hacia el balompié británico continental." },
      { "nombre": "Paul McStay", "desc": "Mediocentro central puro en el club durante toda su carrera profesional (1981-1997). Se oficializó como capitán en 1990 superando las 670 presencias. Orquestó desde la distribución la obtención del famoso doblete en la temporada del centenario institucional 1988." },
      { "nombre": "Shunsuke Nakamura", "desc": "Volante ofensivo operando durante cuatro campañas intensas (2005-2009). Obtuvo el premio a Futbolista del Año en 2007. Decidió partidos de altísimo peso mediante tiros libres directos, notoriamente contra Manchester United durante la Liga de Campeones europea." }
    ],
    "goleadores_historicos": [
      { "nombre": "Jimmy McGrory", "cant": 522, "desc": "Ostentando supremacía inquebrantable, lidera históricamente el registro general goleador escocés tras acumular más de quinientas conquistas. Facturó 522 veces en poco más de 500 encuentros durante la etapa cronológica abarcada entre 1922 y 1937." },
      { "nombre": "Bobby Lennox", "cant": 273, "desc": "Ubicado estadísticamente en el segundo lugar máximo, operó desde la década de 1960. Fue el segundo mayor anotador local contabilizando 273 tantos formales y resulta ser uno de los únicos ganadores de 1967 nacido en distritos algo alejados directamente de Parkhead." },
      { "nombre": "Stevie Chalmers", "cant": 231, "desc": "Efectivo finalizador táctico que jugó la mayor etapa de su carrera extendida entre 1959 y 1971. Ingresó directamente y para siempre a los libros al registrar históricamente el recordado gol ganador formal sobre el minuto 84 en la ciudad de Lisboa." },
      { "nombre": "Jimmy Quinn", "cant": 217, "desc": "Delantero pionero estatuido en la historia tras dominar redes de la competición entre 1900 y 1915. Logró adjudicarse como líder de la tabla nominal goleadora nacional hasta cuatro veces, destacando rotundamente en los primeros derbis clásicos capitalinos." },
      { "nombre": "Sandy McMahon", "cant": 171, "desc": "Atacante rústico que operó formalmente entre los años fundacionales de 1890 al 1903. Acumuló una incesante producción de 171 definiciones a lo largo de un período primario corto consolidándose velozmente como el máximo goleador del ciclo 1893." }
    ],
    "presencias_historicas": [
      { "nombre": "Billy McNeill", "cant": 822, "desc": "Defensa de sólida constancia que encabezó la titularidad bajo el brazalete (1957-1975). Alcanzó las 822 disputas formales consolidando una marca irrompible. Es el exponente que levantó burocráticamente la máxima Copa continental hacia los cielos europeos en el 67." },
      { "nombre": "Pat Bonner", "cant": 641, "desc": "Guardián titular constante operando debajo de los tres palos desde las bases de 1978 hasta ser liberado formalmente en 1997. Mantuvo su consistencia por dos décadas sobrepasando la cifra del medio millar bajo mandos de diversos cuerpos técnicos sucesivos." },
      { "nombre": "Danny McGrain", "cant": 663, "desc": "Se afianzó rígidamente dentro del puesto de carrilero derecho a lo largo de diecisiete campañas ininterrumpidas (1970-1987). Repuesto clínicamente del diagnóstico del azúcar en sangre, continuó exhibiendo desgaste férreo contabilizando 663 duelos puros." },
      { "nombre": "Roy Aitken", "cant": 672, "desc": "Alternante oficial entre los roles de zaga pura y volante de contención. Durante la franja (1976-1990), superó la cuota de las seiscientas actuaciones asumiendo la línea dura del campo sumando a la estantería decenas de copas escocesas registradas." },
      { "nombre": "Alec McNair", "cant": 604, "desc": "Histórico marcador inicial inscripto formalmente entre 1904 y 1925. Logró forjar longevidad operativa de 604 torneos resistiendo paralelos bélicos abismales, cerrando oficialmente sus apariciones escocesas con cuarenta y un años cronológicos consumados." }
    ]
  },
  "rangers": {
    "idolos": [
      { "nombre": "Jim Baxter", "desc": "Virtuoso y dotado creativo que dominó la banda izquierda entre 1960 y 1965 con asiduidad táctica. Totalizó más de cien lances ganando una docena formal de medallas. Es calificado por el purismo como uno de los mediocampistas locales más ilustrados estadísticamente." },
      { "nombre": "Brian Laudrup", "desc": "Atacante titular operando estípite desde su millonaria firma en 1994. Proveedor central de asistencias precisas en cuatro campañas puras que coadyuvaron a ganar el título de forma ininterrumpida; fue distinguido dos años seguidos mejor exponente general." },
      { "nombre": "Paul Gascoigne", "desc": "Surgido internacionalmente recaló en los registros escoceses (1995-1998) marcando sobre tres decenas de tantos en certámenes del medio. Su capacidad abstracta del traslado veloz fue neurálgica durante las consagraciones ininterrumpidas del octavo y noveno cetro de los ochenta." },
      { "nombre": "Richard Gough", "desc": "Defensor titular formal comandando bajo capitanía el éxito apabullante y continuo desde 1987. Sumó titularidad en 427 duelos oficiales forjando el blindaje central requerido para conquistar asombrosamente los registros récord del '9 in a row' escocés." },
      { "nombre": "Sandy Jardine", "desc": "Carrilero aguerrido y versátil abarcando ininterrumpidamente desde 1964 a 1982. Rebasó históricamente las seiscientas cincuenta titularidades adjudicándose el máximo honor internacional formal mediante su consagración táctica alzando firme la Recopa Europea en 1972." }
    ],
    "goleadores_historicos": [
      { "nombre": "Ally McCoist", "cant": 355, "desc": "Fichado estadísticamente en 1983 tras su pase del Sunderland, lideró el goleo durante quince temporadas hasta 1998. Acumuló 355 definiciones ubicándose burocráticamente primero del top general, mereciéndose adicionalmente las Botas de Oro consecutivas de 1992 y 1993 oficiales." },
      { "nombre": "Bob McPhail", "cant": 261, "desc": "Oficiando de central adelantado entre entreguerras (1927-1939). Estableció métricas avasallantes consolidando una de las tazas de efectividad más altas anotando hasta alcanzar contigentemente 261 conquistas asegurando supremacías firmes del torneo nacional." },
      { "nombre": "Jimmy Smith", "cant": 249, "desc": "Atacante férreo en franjas cronológicas tempranas comprendidas entre el año 1928 y finales de los años 40. Contribuyó mediante remates interiores al abultamiento constante que aseguró formal e ininterrumpidamente su sitial tercerizado entre rematadores vigentes." },
      { "nombre": "Ralph Brand", "cant": 206, "desc": "Destacado por componer las temibles duplas ofensivas alineando de entrada durante la década del cincuenta al sesenta. Batió arqueros en 206 contiendas formales impulsando y concretando cinco preseas de campeonato local en su paso oficial." },
      { "nombre": "Jim Forrest", "cant": 145, "desc": "Desarrollador de remate prematuro entre sus épocas estables comprendiendo las ligas de 1962 a 1967. Rompió toda una pared estadística al rubricarse con 57 festejos en una sola cruzada burocrática temporaria antes de emigrar forzosamente a divisiones extranjeras." }
    ],
    "presencias_historicas": [
      { "nombre": "John Greig", "cant": 755, "desc": "Lateral izquierdo volcado posteriormente como tapón. Operando burocráticamente inamovible (1961-1978). Su cuenta abismal y estricta certifica presencias en setecientos cincuenta y cinco juegos, incluyendo la final directa de la conquista europea barcelonesa en el 72." },
      { "nombre": "Sandy Jardine", "cant": 674, "desc": "Defensa polivalente radicado y consolidado estadísticamente bajo 674 designaciones nominales a lo largo de 18 años puros. Su constancia táctica le brindó titularidades infalibles sorteando todo contratiempo burocrático dentro del esquema local de juego continuo." },
      { "nombre": "Ally McCoist", "cant": 581, "desc": "Mantenido rígidamente dentro de las nóminas iniciales (1983-1998). Su constancia en la definición ofensiva le acreditó además titularidad acumulable asumiendo el comando ofensivo total de la escuadra nacional cruzando ampliamente la marca burocrática del medio millar de alineamientos." },
      { "nombre": "Sandy Archibald", "cant": 513, "desc": "Corredor volcado por banda diestra que ostenta abultadas presentaciones prolongadas en casi dos décadas continuas abarcadas (1914-1934). Sostuvo una marca de participación asidua totalizando 513 representaciones que contribuyeron netamente a la obtención de casi quince certámenes." },
      { "nombre": "David Meiklejohn", "cant": 490, "desc": "Líbero y marcador acoplado fuertemente operando posterior a conflictos bélicos tempranos (1919-1936). Respondió fácticamente al esquema táctico comandado y dirigencial sumando su registro hacia los casi quinientos duelos, y ostentando con asiduidad incesante la designación capitular obligatoria." }
    ]
  },
  "aberdeen": {
    "idolos": [
      { "nombre": "Gordon Strachan", "desc": "Mediocentro trasladado al club en 1977, desempeñando su rol hasta el año 1984. Totalizó cerca de 90 definiciones asumiendo el desarrollo organizativo general que desembocó fácticamente en la recolección táctica de la Recopa de 1983 bajo instrucciones disciplinarias estrictas de Ferguson." },
      { "nombre": "Eoin Jess", "desc": "Surgido de la cantera base a inicio de los '90, compitiendo en etapas separadas cronológicamente hasta el 2001. Aportó dinamismo fluido generando cuotas altas de control táctico bajo la medular consolidando premios oficiales por jugador revelación del entorno local formativo escocés." },
      { "nombre": "Neale Cooper", "desc": "Combativo y férreo central táctico formativo emergiendo dentro del escuadrón glorioso triunfador abarcado en 1983. Impuso estadísticas de balones ganados determinantes que resquebrajaron tempranamente la táctica europea de rivales céntricos como Real Madrid en la disputa escandinava." },
      { "nombre": "Stewart McKimmie", "desc": "Lateral defensor asignado formal e ininterrumpidamente desde 1983 hasta mediados de la década de los 90. Destacó puramente por rigidez paramétrica sumando intervenciones defensivas efectivas contribuyendo a tres ligas burocráticas obtenidas puramente bajo su tenaz y constante supervisión diestra lateral." },
      { "nombre": "Russell Anderson", "desc": "Defensa consolidado que capitaneó a la nueva escuadra mediante su arribo táctico post 2000. Registró participaciones clave de recomposición táctica superando dolencias y lesiones burocráticas logrando posteriormente sostener firmemente al equipo levantando la Copa Liguera en 2014 oficial." }
    ],
    "goleadores_historicos": [
      { "nombre": "Joe Harper", "cant": 205, "desc": "Definidor táctico clásico acotando apariciones regulares durante largos plazos en la década de los setenta y ochenta. Formalmente acumuló sobre las redes doscientos cinco tantos que lo oficializan inamovible puntero histórico estadístico del listado del club puramente goleador." },
      { "nombre": "Matt Armstrong", "cant": 150, "desc": "Ofreciendo intervenciones puramente delanteras durante temporadas (1931-1939). Asumió fácticamente el peso productivo de la línea de mando ofensiva engrosando métricas letales mediante remates acentuados que solidificaron estadísticamente el avance firme del conjunto de cara a copas formativas." },
      { "nombre": "Drew Jarvie", "cant": 131, "desc": "Completando los años comprendidos entre (1972-1982) compuso y operó ofensivamente forjando asociación nominal goleadora constante de asistencias mutuas aportando registros letales asiduos asegurables sobreponiéndose a esquemas adversarios ciegos cruzando y superando con amplitud el centenar cronometrado de anotaciones certeras." },
      { "nombre": "Benny Yorston", "cant": 125, "desc": "Participaciones primarias abarcadas (1927-1932) destacando estadísticamente en remate interior acoplado del equipo rústico inicial despachando cifras rotundas como los más de 40 goles anotados paramétricamente en el curso de una exclusiva única fase anual puramente temporal y victoriosa competitiva." },
      { "nombre": "Harry Yorston", "cant": 98, "desc": "Sobrino cronológico y estático delantero alineado en campo en las décadas del 50 logrando adjudicarse su sitial numérico aportando de hecho las intervenciones letales decisivas directas en la gran y burocrática consagración primaria del torneo liguero consolidado fácticamente en 1955." }
    ],
    "presencias_historicas": [
      { "nombre": "Willie Miller", "cant": 797, "desc": "Defensor táctico absoluto abarcando temporalidad (1972-1990). Obtuvo reconocimiento global al capitaneado férreo liderando sin faltar al registro continental triunfal y superando aplastante y permanentemente más de casi ochocientos envites cruzados oficiales sin transferencias posteriores a otros clubes jamás registradas." },
      { "nombre": "Alex McLeish", "cant": 692, "desc": "Jugador puro en demarcación central operativa que abarcó asiduamente paramétrica de 1978 a 1994 formó alianza rígida en la cobertura final aportando solidez defensiva que restó goles estipulados y asegurando cruces estables alcanzando históricamente cerca exacto a las setecientas representaciones formales." },
      { "nombre": "Bobby Clark", "cant": 591, "desc": "Guardián responsable operando (1965-1982). Asumió métricas que impusieron barreras inquebrantables estipulando formalmente el gran reconocimiento nacional obteniendo y sobrepasando en apariciones temporales las quinientas representaciones puras garantizando inamovibilidad durante casi un largo e intacto trayecto burocrático de veinte campañas." },
      { "nombre": "Andrew Considine", "cant": 571, "desc": "Moderno soldado del siglo moderno alineando por más de decenios consecutivos consolidándose progresivamente mediante continuas formaciones asiduas bajo tácticas rotativas. Mantuvo su consistencia acaparando presencias laterales superando registros modernos logrando oficializar casi el límite contable de seiscientas actuaciones burocráticas temporales continuas." },
      { "nombre": "Jim Leighton", "cant": 535, "desc": "Arquero internacional formado temporalmente e interviniente en dos eras separadas (1977-1988) y su posterior regreso temporal. Ostenta tapadas estipuladas formales inmensas conteniendo rematadores letales asegurando su meta histórica europea mediante su abismal permanencia documentada formalizada oficial." }
    ]
  },
  "hearts": {
    "idolos": [
      { "nombre": "Dave Mackay", "desc": "Mediocentro rústico radicado paramétricamente entre (1953 y 1959) obteniendo galardones locales puros guiando al club al triunfo formal copero y liga de 1958. Tras su éxito emigraría a Tottenham dejando en Escocia números implacablemente asiduos defensivos resolutivos letales oficiales." },
      { "nombre": "Craig Gordon", "desc": "Arquero contemporáneo nacido en inferiores asumiendo custodia formal inicialmente desde 2000 superando adversidades cruzadas fisiológicas complejas asegurando salvaguardas continentales puros retornado décadas cronológicas posterior operando a enorme vigencia estadística superando los cuarenta años fisiológicos y coronándose puramente como pilar constante irremplazable actual." },
      { "nombre": "Steven Pressley", "desc": "Caudillo defensivo central que rigió al escuadrón (1998-2006). Alzó el título y medalla copera de 2006 operando estadísticamente en más de cien dictámenes en la saga logrando ostentar titularidades fijas puras sin ceder espacio ni un centímetro táctico bajo los esquemas formales estructurados obligatorios temporales pasados." },
      { "nombre": "Paul Hartley", "desc": "Volante anotador resolutivo integrando filas cronológicamente abarcables entre los años iniciales 2000 superando cifras contiguas promediando aportes ofensivos netos puros destacando estadísticamente su famoso triplete copero propinado rígidamente al mayor rival vecino urbano propulsando históricamente alegrías estipuladas estáticas y consagradas al pabellón formal oficial institucional." },
      { "nombre": "Rudi Skácel", "desc": "Volante izquierdo formal inscripto en la historia (2005 y 2012 subsiguiente). Facturó números puros resolutivos contribuyendo estadísticamente la obtención oficial estipulada marcando en múltiples finales y copas directas cimentando estadísticamente una participación de gran porcentaje final anotador de procedencia pura centroeuropea directa asidua importada foránea." }
    ],
    "goleadores_historicos": [
      { "nombre": "John Robertson", "cant": 271, "desc": "Atacante paramétrico actuando en décadas 80 y 90 cruzadas. Sumó estadísticamente doscientos setenta y un tantos burocráticos. Famosamente establecido y recordado burocráticamente rompiendo redes en veintisiete contiendas clásicas urbanas dictadas superando todas marcas previas formales estipuladas capitalinas goleadoras del país escocés directo formal histórico." },
      { "nombre": "Jimmy Wardhaugh", "cant": 206, "desc": "Delantero puro radicado en el cruce de los años 50 rígidamente. Obtuvo consolidación superando el umbral pletórico y numérico asiduo estableciendo la meta burocrática de los dos siglos de anotaciones certeras. Pieza de engranaje táctico paramétrica formal insuperable resolutiva directa estelar copiosa inagotable de su cronograma pasado estricto." },
      { "nombre": "Willie Bauld", "cant": 183, "desc": "Táctico rematador establecido al medio cronológico entre la finalización cincuentera y su subsecuente continuación participativa. Asumió presencias constantes facturando por vía aérea y técnica alcanzando oficial e irrenunciablemente una producción sumada directa estadísticamente y rigurosamente contabilizada a lo largo de un centenar continuado estático temporal resolutivo." },
      { "nombre": "Alfie Conn Sr.", "cant": 221, "desc": "Fuerte rematador del siglo pasado alineado en periodos burocráticos de los años románticos puros asegurando y contribuyendo estadísticamente su cifra histórica de la mano rígida asociativa temporal abarcando campeonatos asiduos sin descanso forjando asombrosamente resoluciones numéricas directas y formales estipuladas al cruzar sin pausa el campo opuesto adverso táctico enemigo final copero nacional puro." },
      { "nombre": "Drew Busby", "cant": 84, "desc": "Mediapunta contundente actuando durante temporalidades tácticas limitadas paramétricas contribuyendo rústica pero paramétricamente asiduas anotaciones constantes. Su fuerza ofensiva consolidó victorias aseguradas facturando cifras completas de alta valoración frente a disputas férreas directas puras de resoluciones burocráticas formadas y aseguradas cerrando asombrosamente su historial fijo y directo contable formal oficial escocés del conjunto granate paramétrico." }
    ],
    "presencias_historicas": [
      { "nombre": "Gary Mackay", "cant": 737, "desc": "Volante central puro abarcando operativamente cronograma formal dictado entre (1980-1997). Asiduidad estadística pura consolidándolo burocráticamente con setecientos treinta y siete contiendas rompiendo récords insoslayables asegurando representatividad estipulada directa indiscutada garantizando férrea permanencia pura en nóminas titulares absolutas estables formales históricas oficiales institucionales y paramétricas nacionales de Escocia directa." },
      { "nombre": "Henry Smith", "cant": 596, "desc": "Cancerbero guardián formal paramétrico custodio desde los 80 asumiendo asiduidad cruzando registros casi absolutos. Alcanzó el nivel burocrático numérico inigualable resistiendo inclemencias físicas continuas prolongándose estadísticamente y numéricamente sin vacilar frente al ataque cruzado formal directo constante del campeonato nacional estricto copero oficial e incuestionablemente rígido del plantel base puro titular." },
      { "nombre": "Craig Levein", "cant": 401, "desc": "Marcador táctico establecido duraderamente por catorce temporados burocráticas abarcando cifras numéricas indisputadas de cuatrocientos encuadres directos a puro golpe posicional defensivo operado bajo rigor cruzado salvaguardando puntos claves estelares fijos formales estáticos e indiscutados de las jornadas aseguradas puras continuadas en el esquema paramétrico nacional defensivo asiduo capitular rígido oficial estipulado fijo." },
      { "nombre": "Callum Paterson", "cant": 158, "desc": "Defensa de paso acotado rígidamente abarcando inicio joven moderno siglo nuevo marcando presencias estipuladas numéricamente exactas de 158 encuentros aportando su estadística táctica rústica fija segura constante y disciplinada en franjas cerradas bajo parámetros burocráticos exactos de las escuadras alineadas capitulares nacionales en el esquema puro táctico y posicional final resolutivo directo seguro y estático incuestionable del formato alineador del campeonato capitalino." },
      { "nombre": "John Brough", "cant": 341, "desc": "Defensa de flanco establecido en temporalidad paramétrica de los lejanos cuarenta a cincuenta sumando titularidades asiduas fijas registrando estadísticamente aportes sin treguas físicas de presencias operativas burocráticas marcando la continuidad asombrosa y rigurosa numéricamente abarcando registros precisos incontestables cerrando asiduamente pautas obligatorias formales completando las plantillas de forma pura estable constante estricta disciplinada final resolutiva de la formación asidua incuestionable titular base rígida de las pasadas líneas históricas del plantel escocés absoluto." }
    ]
  }
};

const sanitize = (text) => text.substring(0, 300) + "..."; // Keeping the text lengths under control if they get out of hand

Object.keys(d).forEach(k => {
    let p = `app/src/data/clubes/escocia/${k}.json`;
    if(fs.existsSync(p)){
        let j = JSON.parse(fs.readFileSync(p, 'utf8'));
        
        let idls = d[k].idolos.map(x => ({ nombre: x.nombre, desc: x.desc.length > 250 ? sanitize(x.desc) : x.desc }));
        let gols = d[k].goleadores_historicos.map(x => ({ nombre: x.nombre, cant: x.cant, desc: x.desc.length > 250 ? sanitize(x.desc) : x.desc }));
        let pres = d[k].presencias_historicas.map(x => ({ nombre: x.nombre, cant: x.cant, desc: x.desc.length > 250 ? sanitize(x.desc) : x.desc }));

        j.idolos = idls;
        j.goleadores_historicos = gols;
        j.presencias_historicas = pres;
        
        fs.writeFileSync(p, JSON.stringify(j, null, 2));
    }
});
console.log('Leyendas escocia lote 1 FIX inyectadas');
