const fs = require('fs');
const path = require('path');

const engDir = path.join(__dirname, 'app', 'src', 'data', 'clubes', 'inglaterra');

const fixes = {
    'leeds-united': "El club moderno nació el 17 de octubre de 1919 emergiendo de las cenizas de un severo escándalo burocrático. Su predecesor, el Leeds City FC, había sido disuelto y expulsado por la Football League tras ser acusado de realizar pagos ilegales a jugadores amateur durante la Primera Guerra Mundial. Como respuesta, un grupo de aficionados locales decidió fundar una nueva franquicia que limpiara el nombre de la ciudad. Bajo la conducción del exjugador Dick Ray, el naciente Leeds United heredó el estadio de Elland Road y se inscribió en la Midland League, forjando rápidamente la mística industrial que los llevaría a las máximas categorías del fútbol británico.",
    'liverpool': "La creación del Liverpool es el singular producto de un desacuerdo comercial. En la primavera de 1892, el poderoso empresario cervecero John Houlding, propietario de los terrenos de Anfield, impuso un aumento en la renta a sus clásicos inquilinos, el Everton FC. Ante la negativa de pago, la directiva del Everton abandonó el recinto dejándolo completamente vacío. Determinado a rentabilizar su majestuoso campo, Houlding procedió a la inusual jugada de fundar su propio equipo de fútbol. Nacido bajo la matrícula oficial el 3 de junio de 1892, el novel club fue registrado inicialmente bajo el nombre 'Everton F.C. and Athletic Grounds Ltd', para luego adoptar definitivamente la legendaria denominación de Liverpool F.C.",
    'manchester-city': "Sus orígenes se remontan al crudo invierno industrial de 1880 bajo el humilde nombre eclesiástico de 'St. Mark's (West Gorton)'. Ante el violento escenario de delincuencia pandillera en los suburbios marginados de Manchester, Arthur Connell, rector de la parroquia local, y su esposa Anna iniciaron un proyecto de contención social. Su meta principal era crear un equipo de fútbol que mantuviese a los hombres alejados de las peleas callejeras y el alcohol. Este proyecto eclesiástico evolucionó velozmente, transformándose en el Ardwick Association Football Club en 1887 y finalmente bautizándose como Manchester City en abril de 1894.",
    'manchester-united': "Forjado en el corazón mismo del humo y el acero, este coloso mundial nació en 1878 al amparo del extenuante trabajo ferroviario inglés bajo el nombre de 'Newton Heath LYR Football Club'. Sus pioneros fundadores constituyeron la totalidad del departamento de Carga y Mantenimiento del depósito ferroviario de Lancashire y Yorkshire. Como equipo corporativo férreo dominaron torneos regionales contra otras compañías. Recién en el año 1902, agobiados por ineludibles complicaciones presupuestarias que los situaron frente a una orden de liquidación judicial irrefutable, un consorcio de cuatro inversionistas locales inyectó el capital de rescate e impulsó la refundación de la institución como Manchester United.",
    'newcastle': "La actual fiera blanquinegra tiene raíces cimentadas en una rivalidad barrial del norte inglés. En noviembre de 1881 se formó originariamente el popular equipo de críquet Stanley, el cual migró hacia el fútbol para disputar compromisos durante el invierno bajo la denominación de Newcastle East End. Al agudizarse hacia 1892 serios problemas financieros y logísticos en el bando acérrimo de la ciudad rival, el Newcastle West End, los directivos de ambos clubes sellaron un pacto de caballeros fusionando definitivamente las instituciones. La fusión unificó a la ciudad y generó formalmente el nacimiento del irrebatible Newcastle United.",
    'nottingham-forest': "Forjado firmemente en 1865 como una brillante distracción en la antigua taberna Clinton Arms, un grupo de jugadores abandonó la práctica del rústico deporte shinty apostando formalmente a las reglas oficiales del fútbol. En una magistral asamblea oficial conformada por J.S. Scrimshaw y otros caballeros fundadores votaron de forma tajante adoptar una identidad visual impactante. Adhirieron de forma inmaculada al color 'Rojo Garibaldi', en un directo homenaje histórico al afamado líder político, militar republicano y patriota italiano que causaba furor ideológico mundial en aquella época.",
    'sunderland': "El origen de este felino del norte inglés nació enteramente ligado al esfuerzo educativo y la disciplina escolar. Convocado en el rigor académico el 17 de octubre de 1879, el respetado maestro escocés James Allan decidió armar audazmente el 'Sunderland and District Teachers Association Football Club'. Su idea consistió en generar un grupo cerrado exclusivamente abierto para el divertimento de los profesores de la zona; pero ante presiones e insistencias de gran clamor barrial por sumarse, la junta tomó rápidamente la decisión de abrir las vacantes a cualquier trabajador civil, omitiendo la palabra 'Teachers' de su denominación.",
    'tottenham': "El 5 de septiembre de 1882, un audaz grupo de jóvenes escolares y miembros de un club de críquet barrial fundó esta entidad en pleno corazón de Tottenham. Deseosos de mantener una actividad física vigorosa durante el duro parate del invierno en el que los bates de críquet guardaban estricta inactividad, los colegiales conformaron un humilde equipo de potrero cobijado bajo las incipientes luces de gas de sus calles aledañas. Bobby Buckle ofició como primer visionario dirigente de aquel equipo asumiendo el mote 'Hotspur', en franco homenaje a Sir Henry Percy, noble militar inglés que dominó históricamente dichas tierras geográficas.",
    'west-ham-united': "El corazón latente y matriz fundacional del club proviene inamoviblemente de los majestuosos y metódicos astilleros victorianos instalados junto a la ribera. Arnold Hills, empresario patronal del inmenso Thames Ironworks and Shipbuilding Company, ordenó estratégicamente en junio de 1895 conformar un equipo de fútbol obrero corporativo. Consagrados a base de sacrificio por trabajadores marineros y armadores de navíos bajo el nombre 'Thames Ironworks FC', la entidad gozó del monopolio del sudor obrero ribereño durante cinco años hasta que en 1900 formalizaron su restructuración civil total operando definitivamente bajo la etiqueta de West Ham United.",
    'wolverhampton-wanderers': "El nacimiento de esta histórica franquicia, enraizada profundamente en el tejido industrial de las Tierras Medias Occidentales, tuvo origen en el seno escolar de 1877. Fundado oficialmente por el ímpetu visionario de John Baynton y Jack Brodie —estudiantes devotos tras la presentación de un balón a su clase— el equipo inició como un proyecto estrictamente institucional eclesiástico bajo el ala directiva de la St. Luke’s School en el distrito de Blakenhall. Tras la inicial dominación en ligas inter-escolares regionales amateur y habiéndose curtido en el juego rústico contra adultos, la junta juvenil oficializó formalmente su reestructuración magna en 1879 amparando su fusión definitiva con el club de críquet local, The Wanderers, bautizando así a la leyenda dorada venidera."
};

for (const [slug, newDesc] of Object.entries(fixes)) {
    const jsonPath = path.join(engDir, `${slug}.json`);
    if(fs.existsSync(jsonPath)) {
        let data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
        if (data.historia && data.historia.length > 0) {
            let fundacionItem = data.historia.find(h => 
                h.hito && (h.hito.toLowerCase().includes('fundaci') || 
                h.hito.toLowerCase().includes('origen') || 
                h.hito.toLowerCase().includes('nacimiento') ||
                h.hito.toLowerCase().includes('inicios') ||
                h.hito.toLowerCase().includes('creation') ||
                h.hito.toLowerCase().includes('constitu'))
            );
            if (!fundacionItem) fundacionItem = data.historia[0];
            
            fundacionItem.desc = newDesc; // Apply clean fix
            fs.writeFileSync(jsonPath, JSON.stringify(data, null, 2), 'utf8');
            console.log(`Fixed ${slug}`);
        }
    }
}
