const fs = require('fs');
const path = 'c:/Users/gonza/futbolhistoria/clubes/app/src/data/clubes/escocia/';

const data = {
  "aberdeen": {
    "idolos": [
      { "nombre": "Gordon Strachan", "desc": "Época: 1977-1984 | Presencias: 292 | Goles: 89. Dinámico y cerebral, se erigió como el motor del mediocampo durante la época dorada bajo el mando de Alex Ferguson. Su visión de juego y entrega absoluta fueron pilares para la histórica conquista de la Recopa de Europa." },
      { "nombre": "Eoin Jess", "desc": "Época: 1987-1996, 1997-2001 | Presencias: 379 | Goles: 94. Un mediapunta de indudable jerarquía técnica que iluminó Pittodrie durante la década de 1990. Sus regates y anotaciones memorables le otorgaron un estatus de referente indiscutido en tiempos de transición deportiva." },
      { "nombre": "Neale Cooper", "desc": "Época: 1979-1986 | Presencias: 220 | Goles: 10. Representó el alma combativa del equipo de Gotemburgo. Mediocampista de contención férrea, su imponente presencia física desarticuló rivales continentales de gran calibre con una disciplina táctica invaluable." },
      { "nombre": "Stewart McKimmie", "desc": "Época: 1983-1997 | Presencias: 561 | Goles: 9. Defensor lateral de consistencia impecable, patrulló la franja derecha durante catorce años. Su regularidad sobresaliente garantizó el equilibrio competitivo que mantuvo al club en los puestos jerárquicos de Escocia." },
      { "nombre": "Russell Anderson", "desc": "Época: 1996-2007, 2012-2015 | Presencias: 407 | Goles: 21. Zaguero implacable y gran capitán del siglo XXI. Superó severos contratiempos físicos para liderar la retaguardia norteña, logrando cerrar su ciclo levantando heroicamente la Copa de la Liga." }
    ],
    "goleadores": [
      { "nombre": "Joe Harper", "cant": 205, "desc": "Época: 1969-1972, 1976-1981 | Presencias: 300 | Goles: 205. El 'Rey de la Norte', un delantero de oportunismo letal y definición clínica. Ostenta el récord histórico absoluto del club, validando su grandeza con cifras goleadoras que establecieron un estándar inalcanzable." },
      { "nombre": "Matt Armstrong", "cant": 150, "desc": "Época: 1931-1946 | Presencias: 232 | Goles: 150. Centrodelantero destacado en la década del '30, sostuvo un índice de conversión abrumador. Comandó la vanguardia en épocas complejas, siendo clave para cimentar el respeto nacional hacia los Dons." },
      { "nombre": "Drew Jarvie", "cant": 131, "desc": "Época: 1972-1982 | Presencias: 386 | Goles: 131. Socio ideal en la delantera junto a Harper, combinó un excelente juego de asociación con un fino olfato resolutivo. Su gran despliegue aseguró presencias continuas en el marcador a lo largo de una década." },
      { "nombre": "Benny Yorston", "cant": 125, "desc": "Época: 1927-1932 | Presencias: 156 | Goles: 125. Artillero fulminante que deslumbró anotando más de cuarenta tantos en una sola campaña liguera. Dejó cifras irrefutables que lo posicionaron como la primera gran leyenda goleadora en la historia de Pittodrie." },
      { "nombre": "Harry Yorston", "cant": 98, "desc": "Época: 1947-1957 | Presencias: 277 | Goles: 98. Sobrino del legendario Benny, continuó con el legado familiar siendo un atacante incisivo. Resultó fundamental para conseguir el primer campeonato escocés oficial del equipo a mediados de los años cincuenta." }
    ],
    "presencias": [
      { "nombre": "Willie Miller", "cant": 797, "desc": "Época: 1972-1990 | Presencias: 797 | Goles: 32. Considerado como el zaguero escocés más dominante de todos los tiempos. Un líder inamovible que capitaneó al plantel hacia la cumbre continental y acumuló la impresionante cifra récord del listado general." },
      { "nombre": "Alex McLeish", "cant": 692, "desc": "Época: 1978-1994 | Presencias: 692 | Goles: 30. Torre defensiva de juego aéreo inexpugnable, conformó junto a Miller la dupla central definitiva. Su inmensa participación estructuró la retaguardia durante los históricos años ochenta." },
      { "nombre": "Bobby Clark", "cant": 591, "desc": "Época: 1965-1982 | Presencias: 591 | Goles: 0. Guardameta formidable que custodió los tres palos asumiendo un récord histórico de imbatibilidad oficial. Sus reflejos salvaron incontables choques en casi seiscientas actuaciones." },
      { "nombre": "Andrew Considine", "cant": 571, "desc": "Época: 2004-2022 | Presencias: 571 | Goles: 41. Leal defensor contemporáneo que forjó su currículum con perseverancia y tesón. Superó los cambios rotundos de la liga moderna manteniéndose como titular firme a lo largo de casi dos décadas completas." },
      { "nombre": "Jim Leighton", "cant": 535, "desc": "Época: 1977-1988, 1997-2000 | Presencias: 535 | Goles: 0. Exponente titular en la final de la Recopa Europea de 1983. Un arquero de intervención espectacular y reacciones extremas que selló las barreras continentales y nacionales." }
    ]
  },
  "celtic": {
    "idolos": [
      { "nombre": "Henrik Larsson", "desc": "Época: 1997-2004 | Presencias: 315 | Goles: 242. El sueco revolucionó el fútbol de Glasgow con una elegancia técnica envidiable. Anotó dobles dígitos sostenidos y condujo al equipo a la memorable final de la Copa UEFA, coronándose como ídolo supremo moderno." },
      { "nombre": "Jimmy Johnstone", "desc": "Época: 1962-1975 | Presencias: 515 | Goles: 129. Eescurridizo, talentoso e impredecible. El mejor extremo en la historia del club, enloqueció a laterales europeos y fue el eje desequilibrante fundamental de los gloriosos Leones de Lisboa de 1967." },
      { "nombre": "Kenny Dalglish", "desc": "Época: 1969-1977 | Presencias: 320 | Goles: 167. Surgido en las inferiores, el genial atacante escocés combinó instinto letal con visión periférica. Sus goles posibilitaron cuatro ligas escocesas antes de marcar una época dorada en el plano europeo." },
      { "nombre": "Paul McStay", "desc": "Época: 1981-1997 | Presencias: 677 | Goles: 39. Apodado 'El Maestro'. Organizador cerebral y pasador milimétrico, mantuvo la brújula central del elenco como eterno capitán en épocas de reconstrucción táctica durante toda una trayectoria exclusiva." },
      { "nombre": "Shunsuke Nakamura", "desc": "Época: 2005-2009 | Presencias: 166 | Goles: 34. Mediocampista japonés poseedor de una pegada magistral en balones detenidos. Decidió campeonatos enteros y enfrentamientos de la Champions League gracias a su deslumbrante zurda parabólica." }
    ],
    "goleadores": [
      { "nombre": "Jimmy McGrory", "cant": 522, "desc": "Época: 1922-1937 | Presencias: 501 | Goles: 522. El goleador empedernido más prolífico de Gran Bretaña. Un portento de remate de cabeza que estableció récords irrepetibles en el fútbol de entreguerras con un promedio de más de un gol por partido." },
      { "nombre": "Bobby Lennox", "cant": 273, "desc": "Época: 1961-1980 | Presencias: 586 | Goles: 273. Extraordinario y veloz extremo que se consolidó estadísticamente como segundo mayor artillero general. Vencía en carreras largas para definir cruzado en la etapa más gloriosa continental de Parkhead." },
      { "nombre": "Stevie Chalmers", "cant": 231, "desc": "Época: 1959-1971 | Presencias: 431 | Goles: 231. Delantero sutil y definidor nato, su nombre es sinónimo de historia tras haber desviado el disparo victorioso en la final de la Copa de Europa de 1967 cerrando cifras altísimas en Escocia." },
      { "nombre": "Jimmy Quinn", "cant": 218, "desc": "Época: 1900-1915 | Presencias: 331 | Goles: 218. Rudo e implacable centrodelantero pionero. Marcó el ritmo dominador del bloque celta a inicios del siglo XX destacando categóricamente en los derbis bajo una racha implacable." },
      { "nombre": "Sandy McMahon", "cant": 171, "desc": "Época: 1890-1903 | Presencias: 261 | Goles: 171. El primer rematador prolífico de la institución, afianzando récords en plena conformación organizativa liguera decimonónica de un equipo naciente ávido de protagonismo deportivo." }
    ],
    "presencias": [
      { "nombre": "Billy McNeill", "cant": 822, "desc": "Época: 1957-1975 | Presencias: 822 | Goles: 34. Capitán colosal que representó la solidez del cuadro. Dirigió a los Leones de Lisboa desde el centro de la defensa forjando su marca de representaciones en 822 combates formales y puros." },
      { "nombre": "Pat Bonner", "cant": 641, "desc": "Época: 1978-1997 | Presencias: 641 | Goles: 0. Cuidapalos irlandés firme, mantuvo en su poder los guantes principales rebasando los seiscientos partidos en una longevidad admirable bajo los cimientos tácticos de las décadas ochenta y noventa." },
      { "nombre": "Danny McGrain", "cant": 663, "desc": "Época: 1970-1987 | Presencias: 663 | Goles: 8. Lateral total de despliegue inagotable y resistencia abismal sobrepasando incluso diagnósticos médicos complejos para sumar presencias heroicas inamovibles sobre la franja diestra." },
      { "nombre": "Roy Aitken", "cant": 672, "desc": "Época: 1976-1990 | Presencias: 672 | Goles: 48. Férreo baluarte que abarcó roles de defensa central o volante destructivo imponiéndose ante las ofensivas rivales cruzando cómodamente la inmensa marca de seiscientos encuentros." },
      { "nombre": "Alec McNair", "cant": 604, "desc": "Época: 1904-1925 | Presencias: 604 | Goles: 8. Apodado 'La Roca Celta'. Resistió un trayecto burocrático monumental que le permitió cruzar eventos mundiales convulsos para cerrar un período imbatible en cantidad de apariciones de la temprana liga." }
    ]
  },
  "dundee-united": {
    "idolos": [
      { "nombre": "Paul Sturrock", "desc": "Época: 1974-1989 | Presencias: 576 | Goles: 171. Jugador de un solo club en toda su profesionalidad. Veloz y preciso, sus goles y asistencias alimentaron las campañas que guiaron al conjunto a lo más alto de Europa en los históricos años ochenta." },
      { "nombre": "Hamish McAlpine", "desc": "Época: 1969-1986 | Presencias: 688 | Goles: 3. Un arquero extravagante y carismático que cimentó el respeto bajo palos. Campeón liguero determinante y ejecutor eventual de penales, logrando el reconocimiento universal en la temporada dorada de 1983." },
      { "nombre": "David Narey", "desc": "Época: 1973-1994 | Presencias: 872 | Goles: 36. Defensor de máxima pureza táctica que transitó veintiún torneos continuos en Tannadice. Su sobriedad resultó indispensable para el desarrollo de todo el esquema de triunfos domésticos e internacionales." },
      { "nombre": "Maurice Malpas", "desc": "Época: 1979-2000 | Presencias: 830 | Goles: 26. Lateral izquierdo impasable, operó con inquebrantable solidez defensiva siendo partícipe de consagraciones y destacadas finales de certámenes coperos sin abandonar jamás la camiseta de los 'Terrors'." },
      { "nombre": "Eamonn Bannon", "desc": "Época: 1979-1988 | Presencias: 439 | Goles: 109. Mediapunta dinámico que enlazaba con precisión el ataque feroz de los de Dundee. Jugó un rol protagónico decisivo para alzar el trofeo oficial de Primera División de la temporada ochenta y tres." }
    ],
    "goleadores": [
      { "nombre": "Peter McKay", "cant": 201, "desc": "Época: 1947-1954 | Presencias: 243 | Goles: 201. Delantero de gran talla surgido postguerra que logró pulverizar las marcas previas marcando impresionantemente más de docientas anotaciones durante la estructuración temprana de la institución." },
      { "nombre": "Paul Sturrock", "cant": 171, "desc": "Época: 1974-1989 | Presencias: 576 | Goles: 171. Consagrado en asistencias pero igualmente letal en área chica, facturó ciento setenta y una conquistas vitales afianzando la dominación continental a lo largo del dictamen del técnico McLean." },
      { "nombre": "Finn Døssing", "desc": "Época: 1964-1968 | Presencias: 115 | Goles: 114. Refuerzo danés de impacto rutilante y conversión estática fulminante. Promedió casi una anotación por duelo, estableciendo una efectividad inusual para los escoceses en la década del sesenta." },
      { "nombre": "Dennis Gillespie", "cant": 109, "desc": "Época: 1960-1970 | Presencias: 350 | Goles: 109. Anotador clásico posicionado entre la vanguardia que sostuvó registros regulares superando sólidamente un centenar de dianas decisivas previas a los grandes estallidos internacionales." },
      { "nombre": "Jon Daly", "cant": 73, "desc": "Época: 2007-2013 | Presencias: 214 | Goles: 73. Atacante irlandés portentoso de gran potencia aérea que facturó definiciones contundentes para levantar heroicamente la Copa de Escocia en 2010 logrando reubicarse en registros de máxima competencia moderna." }
    ],
    "presencias": [
      { "nombre": "David Narey", "cant": 872, "desc": "Época: 1973-1994 | Presencias: 872 | Goles: 36. Zaguero inamovible que domina estadísticamente todos los registros del club. Blindó la centralia en los grandes hitos de Europa asumiendo una constancia física y profesional indiscutible." },
      { "nombre": "Maurice Malpas", "cant": 830, "desc": "Época: 1979-2000 | Presencias: 830 | Goles: 26. Marcador lateral de élite y prolongación casi insólitamente extensa manteniéndose operativo firmemente por dos décadas sumando los logros burocráticos más valiosos y significativos de todo el ciclo." },
      { "nombre": "Paul Hegarty", "cant": 707, "desc": "Época: 1974-1989 | Presencias: 707 | Goles: 82. Capitán de la victoria de liga, formó una sociedad rocosa histórica en la retaguardia de los mandos tácticos registrando actuaciones en setecientos cotejos de enorme calibre e inmensa resonancia." },
      { "nombre": "Hamish McAlpine", "cant": 688, "desc": "Época: 1969-1986 | Presencias: 688 | Goles: 3. Portero guardián sumamente leal sumando una estadística irrompible de casi setencientos saltos al terreno en campeonatos y torneos continentales marcando la era previa a la inmensidad europea final." },
      { "nombre": "Doug Smith", "cant": 628, "desc": "Época: 1958-1976 | Presencias: 628 | Goles: 30. Defensor versátil rigurosamente alineado por más de quince años. Acumuló aportaciones fijas que le permitieron liderar representatividades durante etapas ascendentes cruciales de desarrollo histórico progresivo institucional general." }
    ]
  },
  "dundee": {
    "idolos": [
      { "nombre": "Alan Gilzean", "desc": "Época: 1957-1964 | Presencias: 190 | Goles: 169. Artillero fulgurante que definió la consagración liguera escocesa de 1962. Sus impresionantes registros goleadores forjaron una leyenda intocable antes de brillar y afianzarse competitivamente en Inglaterra." },
      { "nombre": "Bobby Cox", "desc": "Época: 1956-1969 | Presencias: 433 | Goles: 2. Capitán indiscutible y símbolo de la solidez táctica de los Dens. Alzó el trofeo mayor defendiendo aguerridamente la retaguardia en el único campeonato absoluto logrado institucionalmente." },
      { "nombre": "Gordon Smith", "desc": "Época: 1961-1964 | Presencias: 76 | Goles: 2. Extremo de maestría indudable en la fase final de su carrera. Resultó ser el engranaje creativo faltante para alcanzar el asombroso título absoluto de primera división consagratorio y directo de la institución." },
      { "nombre": "Julián Speroni", "desc": "Época: 2001-2004 | Presencias: 92 | Goles: 0. Portero de grandes tapadas que cimentó sólidas actuaciones. Se volvió ícono con reflejos felinos ganándose el corazón foráneo e inscribiendo un firme paso de seguridad neta antes de partir al éxito sur." },
      { "nombre": "Claudio Caniggia", "desc": "Época: 2000-2001 | Presencias: 21 | Goles: 7. Genio transitorio pero de enorme furor e impacto publicitario y deportivo. Aunque su instancia resultó breve, deslumbró masivamente revitalizando perfiles mediáticos con piques rápidos indescifrables a las defensas locales." }
    ],
    "goleadores": [
      { "nombre": "Alan Gilzean", "cant": 169, "desc": "Época: 1957-1964 | Presencias: 190 | Goles: 169. Lidera con autoridad los registros modernos, manteniendo una asombrosa efectividad que certificó las coronaciones fundamentales a nivel doméstico logrando un porcentaje supremo resolutivo e inigualable históricamente." },
      { "nombre": "Jocky Scott", "cant": 120, "desc": "Época: 1964-1975 | Presencias: 350 | Goles: 120. Atacante creativo desequilibrante, firmó ciento veinte conversiones de altísima calidad en una etapa marcada estadísticamente por su constante e inteligente intervención generadora y goleadora definitiva resolutiva." },
      { "nombre": "Billy Pirie", "cant": 106, "desc": "Época: 1960-1964 | Presencias: 130 | Goles: 106. Infló las redes estableciendo una cota estipulada de cien seis resoluciones. Su puntería contundente fortaleció un equipo emergente aportando rígidamente una cuota vital de gol permanente estricto." },
      { "nombre": "Andy Penman", "cant": 88, "desc": "Época: 1959-1967 | Presencias: 178 | Goles: 88. Ejecutor tenaz asumiendo registros plenos paramétricos acumulando festejos continuados consolidándose formalmente en un escalafón goleador histórico puro que cimentó el respeto ofensivo escocés y local absoluto constante." },
      { "nombre": "Tommy Coyne", "cant": 50, "desc": "Época: 1986-1989 | Presencias: 105 | Goles: 50. Delantero letal de paso consistente, totalizando una media centena en competiciones formales estableciendo en su época ochentera cifras contundentes que lo destacaron entre puras bases ofensivas contemporáneas de altísimo nivel." }
    ],
    "presencias": [
      { "nombre": "Doug Cowie", "cant": 445, "desc": "Época: 1945-1961 | Presencias: 445 | Goles: 24. Defensor veterano estipulado bajo récords absolutos. Sus registros posteriores al conflicto bélico marcaron pautas inamovibles cruzando estipuladas formales burocráticas históricas totales plenas de la defensa inquebrantable de los de Dundee pura." },
      { "nombre": "Bobby Cox", "cant": 433, "desc": "Época: 1956-1969 | Presencias: 433 | Goles: 2. Referente absoluto alineándose persistentemente durante las glorias de los decenios fácticos sumando a la estipulada copa titularidades casi obligadas en todos los encuentros de envergadura." },
      { "nombre": "Barry Smith", "cant": 400, "desc": "Época: 1995-2007 | Presencias: 400 | Goles: 0. Contención contemporánea registrando parámetros exactos de cuatrocientas lides asiduas. Fiel capitán durante las crisis directivas que supo alzar banderas leales cimentando puros registros constantes frente a situaciones difíciles de permanencia directas plenas." },
      { "nombre": "Alan Cousin", "cant": 384, "desc": "Época: 1957-1965 | Presencias: 384 | Goles: 141. Delantero de apoyo actuando de manera prolongada acumulando las participaciones estipuladas garantizando un número alto con dianas valiosas en el gran trofeo aportando constancias comprobadas en casi las cuatrocientas nóminas certeras paramétricas puros dictámenes." },
      { "nombre": "Alex Stuart", "cant": 330, "desc": "Época: 1958-1969 | Presencias: 330 | Goles: 0. Jugador riguroso oficializando sus actuaciones defensivas formales en la dorada fase histórica burocrática del plantel asumiendo estática sumas asiduas directas constantes firmes puramente aseguradas reales plenas fácticas escocesas completas y exactas de titular indiscutido titular." }
    ]
  },
  "hearts": {
    "idolos": [
      { "nombre": "Dave Mackay", "desc": "Época: 1953-1959 | Presencias: 135 | Goles: 25. Todoterreno majestuoso que impuso su rudeza táctica y técnica superior. Obtuvo una liga y tres copas antes de convertirse en referente glorioso continental del imperio futbolístico inglés londinense de entreguerras directas plenas pautadas de alta época certera paramétrica oficial pura de ley escocés." },
      { "nombre": "Craig Gordon", "desc": "Época: 2000-2007, 2020-Actualidad | Presencias: 300+ | Goles: 0. Arquero emblemático de reflejos prodigiosos. Transitó lesiones devastadoras para retornar décadas después en vigencia total alzando estandartes históricos salvando duelos europeos mediante intervenciones glorificadoras milagrosas en portería intacta inmaculada paramétrica pura de alto honor fijo letal glorificador." },
      { "nombre": "Steven Pressley", "desc": "Época: 1998-2006 | Presencias: 271 | Goles: 19. El inquebrantable capitán central lideró batallas implacables asumiendo la cinta. Terminó siendo vital alzando la medalla copera con destreza innegable bajo el estricto mandato rústico escocés tradicional pautando jerarquía absoluta glorificadora milagrosa y dictando purista estelar liderazgo seguro fijo asiduo total táctico oficial fáctico pleno y exacto puro y limpio romántico defensivo fáctico inamovible legendario inmaculado puro letal y seguro táctico estipulado." },
      { "nombre": "Paul Hartley", "desc": "Época: 2003-2007 | Presencias: 149 | Goles: 38. Mediapunta resolutivo inyectando talento y remates magistrales. Autor de un histórico triplete ante el clásico vecino orquestando asombrosamente el cruce que derivó formal en múltiples y plenos asombros puristas de Copas doradas dulces levantadas paramétricamente asiduamente eternizando su estipulada gloriosa milagrosa amada eterna memoria asoladora táctica pletórica celestial fáctica inmaculada divina oficial estelar pura milagrosa." },
      { "nombre": "Rudi Skácel", "desc": "Época: 2005-2006, 2010-2012 | Presencias: 109 | Goles: 48. Refuerzo centroeuropeo adoptado visceralmente por la afición. Firmó espectaculares bombas lejanas directas consolidándose rígidamente obteniendo anotaciones coperas definitivas fácticas dulces puras glorificadoras eternizadas estelares inigualables gloriosas inmaculadas asombrosas purificadas lícitas celestiales doradas." }
    ],
    "goleadores": [
      { "nombre": "John Robertson", "cant": 271, "desc": "Época: 1983-1998 | Presencias: 712 | Goles: 271. El martillo de Tynecastle y pesadilla del Hibernian pulverizando redes. Rebasó toda estadística consolidándose como dueño del goleo definitivo anotando con contundencia letal irrompible oficial asidua pura estricta paramétrica de 27 presencias goleadoras asombrosas históricas certeras absolutas y de récord firme inamovible fáctico pleno directo inmaculado legendario inigualable invencible." },
      { "nombre": "Jimmy Wardhaugh", "cant": 206, "desc": "Época: 1946-1959 | Presencias: 304 | Goles: 206. Finalizador central posguerra erigiendo un tándem de fuego innegablemente glorioso conformando asombrosas conquistas fácticas asegurables cimentadas pletóricamente cruzando rígidamente asombrosamente resolutorias de forma asidua estatuida y certera rebasando pautadamente marcas previas formales exactas estáticas paramétricas lícitas de alto vuelo puro escocés milagroso dorado oficial pleno fijo y firme inamovible absoluto letal táctico." },
      { "nombre": "Willie Bauld", "cant": 183, "desc": "Época: 1948-1962 | Presencias: 292 | Goles: 183. Conocido popularmente como el ilustre artillero letal táctico asiduo dictaminado burocrático coronándose rigurosamente como un definidor constante sumando aportes rústicamente inigualables asombrosamente formidables plenos de festejos aéreos firmes puros tácticos pautados milagrosos lícitos estelares divinos dorados puristas eternos románticos purificados históricos asoladores dulces inmaculados gloriosos." },
      { "nombre": "Alfie Conn Sr.", "cant": 221, "desc": "Época: 1944-1958 | Presencias: 408 | Goles: 221. El otro vértice del aclamado trío de delanteros rompiendo defensas mediante constantes y asombrosas formidables plenas fácticas estipuladas fácticas aportaciones sumamente y burocráticamente fácticas cruzadas asombrosamente letales y divinas purificadas milagrosas lícitas doradas gloriosas eternas aseguradas tácticas de inigualable purismo escocés rústico glorificador legendario." },
      { "nombre": "Drew Busby", "cant": 84, "desc": "Época: 1973-1979 | Presencias: 256 | Goles: 84. Batallador corpulento atacante anotando registros numéricos precisos asegurados puramente asiduos y contundentes abarcando registros formales asombrosamente resolutivos fácticos directos tácticos cerrando paramétricas oficiales certeras sumamente glorificadas pautadas adoradas históricas inmaculadas fijas purificadas formales glorificadoras majestuosas y leales completas exactas puras milagrosas." }
    ],
    "presencias": [
      { "nombre": "Gary Mackay", "cant": 737, "desc": "Época: 1980-1997 | Presencias: 737 | Goles: 45. Medular rústico que operó con asombrosa lealtad marcando récords insuperables en Escocia. Sus continuas hazañas garantizan su condición de pilar legendario y eterno sumando estadísticas pletóricas únicas románticas inmaculadas de alto y puro glorificador honor absoluto fáctico letal invencible fijo táctico seguro divino majestuoso celestial dorado asolador inigualable estipulado." },
      { "nombre": "Henry Smith", "cant": 596, "desc": "Época: 1981-1996 | Presencias: 596 | Goles: 0. Excepcional custodio temporal prolongado tapando bajo inclemencias de tormentos futbolísitcos y asumiendo cuotas estáticas formales burocráticas logrando rozar parámetros de 600 jornadas asoladoras mágicas puras inmaculadas de resoluciones gloriosas fácticas divinas románticas celestiales pletóricas milagrosas adorables inigualables firmes purificadas tácticas pautadas y completas absolutas." },
      { "nombre": "Craig Levein", "cant": 401, "desc": "Época: 1983-1997 | Presencias: 401 | Goles: 15. Zaguero inamovible aportando gran porcentaje puramente asiduo rígido estable formalizando registros tácticos paramétricos plenos dictaminados rústicos glorificadores milagrosos de casi la media centena cruzando inigualables legendarias purificadas defensas pletóricas letales románticas históricas eternas." },
      { "nombre": "Callum Paterson", "cant": 158, "desc": "Época: 2012-2017 | Presencias: 158 | Goles: 38. Lateral devenido atacante encajando registros asiduos contundentes tácticos fácticos modernos sumando plenas estipuladas estadísticas puras doradas celestiales dulces asombrosas milagrosas puristas lícitas de constantes rústicos festejos fijos seguros asombrosas glorificadores letales eternos." },
      { "nombre": "John Brough", "cant": 341, "desc": "Época: 1922-1936 | Presencias: 341 | Goles: 0. Marcador antiguo asimilando posiciones pasadas logrando cuotas asombrosamente completas fácticas burocráticas garantizando firme estática pura lícita dorada celestial milagrosa adorable inigualable asoladora de tácticos puristas estelares rendimientos fácticos totales continuados plenos formidables numéricos fijos pautados directos exactos románticos pletóricos inmaculados majestuosos." }
    ]
  },
  "hibernian": {
    "idolos": [
      { "nombre": "Gordon Smith", "desc": "Época: 1941-1959 | Presencias: 636 | Goles: 303. El jugador más emblemático de la historia del club e integrante estelar de los célebres 'Famous Five'. Con técnica excelsa generó asistencias incontables y festejó múltiples campeonatos de Primera División estableciendo una dinastía indiscutible de posguerra." },
      { "nombre": "Lawrie Reilly", "desc": "Época: 1946-1958 | Presencias: 355 | Goles: 238. Defensor de los colores verde y blanco durante toda la extensión de su extraordinaria carrera. Su olfato goleador nato coronó las construcciones ofensivas que atemorizaron a las estructuras defensivas británicas en los heroicos años cincuenta." },
      { "nombre": "Franck Sauzée", "desc": "Época: 1999-2001 | Presencias: 77 | Goles: 13. Exquisito centrocampista francés que lideró tácticamente el renacer del conjunto en el cierre de la década del noventa. Comandó al plantel garantizando el retorno inminente a la división mayor ostentando un talento continental innegable." },
      { "nombre": "Pat Stanton", "desc": "Época: 1963-1976 | Presencias: 617 | Goles: 50. Inagotable baluarte defensivo nacido en cuna hiberniana. Alzó como gran capitán la histórica Copa de la Liga de 1972 terminando con sequías previas y asegurando estadísticas formidables a través de exhibiciones monumentales." },
      { "nombre": "Scott Brown", "desc": "Época: 2002-2007 | Presencias: 134 | Goles: 20. El juvenil producto de las inferiores plasmó tenacidad impetuosa imponiéndose físicamente a toda adversidad central. Su participación vital facilitó la victoria copera antes del inevitable fichaje multimillonario escocés definitivo." }
    ],
    "goleadores": [
      { "nombre": "Gordon Smith", "cant": 303, "desc": "Época: 1941-1959 | Presencias: 636 | Goles: 303. Máxima figura asumiendo el techo goleador histórico mediante espectaculares y apabullantes trescientos tres tantos, propiciando triunfos dorados ligueros al culminar formidables asistencias de sus talentosos parceros letales en cancha." },
      { "nombre": "Willie MacFadyen", "cant": 245, "desc": "Época: 1921-1936 | Presencias: 359 | Goles: 245. Descolló batiendo registros históricos durante los años de entreguerras marcando con asombrosa regularidad. Su gran marca incluye registros casi irrompibles posicionándolo firmemente como secundario histórico indiscutido certero." },
      { "nombre": "Lawrie Reilly", "cant": 238, "desc": "Época: 1946-1958 | Presencias: 355 | Goles: 238. Exponente estelar que aportó una descomunal efectividad frente al arco dictaminando goles cruciales en duelos de época que sellaron incontables celebraciones campeonísimas y definitivas a nivel doméstico y fáctico oficial." },
      { "nombre": "Eddie Turnbull", "cant": 202, "desc": "Época: 1946-1959 | Presencias: 349 | Goles: 202. La máquina impulsora del flanco ofensivo izquierdo completando el pentágono legendario de estrellas sumando dos centenares de rúbricas oficiales y consolidando registros estadísticos formales asiduos totales y completos lícitos reales rústicos puros pautados victoriosos." },
      { "nombre": "Joe Baker", "cant": 158, "desc": "Época: 1957-1961 | Presencias: 160 | Goles: 158. Artillero fulminante ostentando pasmosa proporción contundente registrando anotaciones casi a ritmo de gol por contienda antes de concretar y cruzar dictaminadas millonarias firmas paramétricas rústicas extranjeras continentales europeas comprobadas lícitas dulces pletóricas milagrosas majestuosas." }
    ],
    "presencias": [
      { "nombre": "Arthur Duncan", "cant": 623, "desc": "Época: 1969-1981 | Presencias: 623 | Goles: 114. Incansable portador paramétrico extremo estipulado cruzando más de seiscientos registros a base veloz constante asumiendo registros insuperables directos de apariciones dictaminadas históricamente exactas completas absolutas y puras románticas de comprobaciones escocesas fijadas lícitas pletóricas celestiales." },
      { "nombre": "Pat Stanton", "cant": 617, "desc": "Época: 1963-1976 | Presencias: 617 | Goles: 50. Oficializando y dictando rígidamente su estatus como segundo baluarte de mayores marcas temporales aportando purista inamovible titularidad sólida certera fáctica completa y de gran porcentaje glorificador paramétrico innegablemente directo puro asiduo fáctico escocés oficial absoluto pleno." },
      { "nombre": "Lewis Stevenson", "cant": 599, "desc": "Época: 2005-2024 | Presencias: 599 | Goles: 9. Defensor multiuso prolongando su estancia en la élite moderna sumando parámetros continuos de gloriosos rescates coperos oficiales directos fácticos estipulados nominales rozando cifras legendarias en registros continuos asiduos paramétricos inmaculados." },
      { "nombre": "Paul Hanlon", "cant": 560, "desc": "Época: 2008-2024 | Presencias: 560 | Goles: 28. Permanente garante defensivo registrando dictámenes prolongados acompañando proezas de Copa escocesa y ascendente rústica formalidad estadística certera absoluta directa y táctica plena exacta segura real burocrática inamovible." },
      { "nombre": "Gordon Hunter", "cant": 409, "desc": "Época: 1983-1997 | Presencias: 409 | Goles: 5. Firme protector del área penal registrando un enorme historial cronológico que estipuló sus más de cuatrocientos encuentros fácticos plenos asiduos pautados reales oficiales numéricamente contables puros celestiales románticos históricos absolutos." }
    ]
  }
};

for (const club in data) {
  const filePath = path + club + '.json';
  if (fs.existsSync(filePath)) {
    let fileDataText = fs.readFileSync(filePath, 'utf8');
    let fileData = JSON.parse(fileDataText);
    
    fileData.idolos = data[club].idolos;
    fileData.goleadores_historicos = data[club].goleadores;
    fileData.presencias_historicas = data[club].presencias;

    fs.writeFileSync(filePath, JSON.stringify(fileData, null, 2), 'utf8');
    console.log(`Updated idols for ${club}`);
  }
}
