const fs = require('fs');
const path = 'c:/Users/gonza/futbolhistoria/clubes/app/src/data/clubes/espania/';

const fundacionesAmpliadas = {
  "mallorca.json": "El archipiélago balear exigía a gritos su propia voz futbolera tras una desorganizada y bohemia importación de pelotas desde la lejana península durante principios de siglo. El 5 de marzo de 1916 floreció la primera piedra monumental liderada casi en soledad, pero con una convicción y poder descomunal, por el insigne Adolfo Vázquez Humasqué, acompañado íntimamente por fundadores románticos de la isla como Antoni Moner, Julio Peñas y Ferran Pin. Así, bautizado pomposa y majestuosamente como la insigne 'Sociedad Alfonso XIII Foot-Ball Club' en honores inmaculados a la monarquía (que tardaría años en castellanizarse para asomar eternamente como Real CD Mallorca y derrocar tintes reales puristas). Los primeros ropajes piratas ensayaban rudimentos rústicos hasta asentarse el bermellón oscuro (rojo y negro) en sus gloriosas banderas infiriendo respeto asfixiante, abriendo fuego para siempre en un humilde descampado insular para forjar a pura garra bermellona la identidad de un equipo abocado a destruir gigantes venidos de mares europeos para encender de rojo hasta el último trozo de tierra de Palma.",
  "osasuna.json": "La crudeza invernal del norte no solo esculpió caracteres, sino que deparó en un estandarte único mundial en la bulliciosa ciudad de Pamplona en plenos años veinte. Las tertulias del legendario e inmaculado y céntrico Café Kutz fueron testigos del furioso parto la inquebrantable tarde oscura del 24 de octubre de 1920. Hastiados e inquietos, los históricos pioneros navarros como Marcos Eizaguirre, el decisivo periodista Benjamín Andoian Martínez, el aguerrido Eduardo Aizpún (que alzaría impasible y estoico la primera presidencia oficial) y Joaquín Rasero sellaron una cruenta y mágica alianza de fusión entre los fragmentados grupos locales Sportiva Football Club y el temido New Club. Fue precisamente en el clamor heroico de la mesa cuando Benjamín Andoian alzó su inquebrantable voz dictaminando un nombre purísimo en milenaria raíz euskera: 'Osasuna' (Salud, Vigor, Fuerza), forjando irremediablemente el primer y pavoroso escudo donde se juramentó hasta la muerte entregar el alma feroz navarra por cada pelota hasta asfixiar rivales como bestias rojillas bajo una hostería perpetua y mágica como El Sadar.",
  "rayo-vallecano.json": "Vallecas no es solo un barrio, es un sentimiento visceral sangrante madrileño. En el corazón proletario inquebrantable asfixiado por las desigualdades el candente 29 de mayo de 1924, a metros asfixiantes del polvo seco vallecanno, un incondicional grupo de jornaleros e hinchas encarnizados concibieron El Rayo. Liderados de arranque por valientes soñadores y lugareños formidables como Prudencio Priego, Julio Rivera, unificaron a hijos de familias y obreros destrozando diferencias de cuna. Sus fundadores obreros gestaron así humildemente y desde lo más oscuro a la imponente y legendaria Agrupación Deportiva Rayo Vallecano, instaurando un equipo que al no poseer recursos, robaba camisetas imitando a los de élite hasta enamorarse eternamente y firmar el idilio asombroso con el River Plate argentino asumiendo de ellos la inmortal y sagrada y eterna mágica franja roja cruzada en el inmaculado y combativo pecho guerrero, emblema incisivo que atemoriza hoy como la bestia temible 'Matagigantes' que fulmina reinos enteros.",
  "real-betis.json": "Las gloriosas páginas andaluzas exigen destilar en pleno furor hispalense el inmenso mito del Real Betis Balompié. Escindidos furiosos por los agusanados desplantes elitistas aristócratas puros que asfixiaban a ciertos alumnos sevillanos apartados cruelmente en el año 1907 e imbuidos a la vez de rebeldía, nació desde las aulas heroicas en Sevilla y para Sevilla las cenizas históricas del 'Sevilla Balompié'. Engendrado majestuosamente por valerosos estudiantes y jóvenes fundadores envalentonados en el llanto y furia inquebrantable de la temible y mágica Academia Politécnica liderados enormemente como Alfonso del Castillo, Edmundo Sykes y Jacinto Wesolowski. Al mismo tiempo y cruzando orillas nacería el indomable e histórico Betis Football Club bajo el ala y mística genial protectora sin parangones de Eladio García de la Borbolla. Fue la unificación sublime e indestructible posterior entre Balompié y Betis lo que conformó irremediablemente el idilio puro con la palabra celta sagrada eterna andaluza del río majestuoso Guadalquivir ('Baetis'). Asumiendo mágicos los verdes de la esperanza pura y blanco inmaculado, sentenciaron las leyes con el místico e inmortal lema guerrero estoico e intratable '¡Viva el Betis manque pierda!'.",
  "real-madrid.json": "El Rey de Reyes en la historia de la humanidad futbolera tuvo una génesis poéticamente universitaria ajena a las cortes imperiales que hoy habita. Sus raíces penden heroicamente desde los fríos descampados de la Institución Libre de Enseñanza donde intelectuales absolutos ex estudiantes en Oxbridge paseaban balones locos en la incipiente capital europea bajo las faldas arcaicas de un humilde pseudo-club clandestino y místico llamado Foot-Ball Sky de Julián Palacios hacia fines del siglo XIX. Fue formal e indudablemente que explotó y vio la estruendosa legalidad y la mágica y definitiva inmortal luz un sagrado 6 de marzo de 1902 gracias a los sublimes hermanos y pioneros inmortales formidables e imperiales catalanes: Juan Padrós y Carlos Padrós, arropados fuertemente y apuntalados tras escudos forjados por Arturo Meléndez conformando oficialmente el colosal 'Madrid Foot-ball Club'. Con la indumentaria sagrada, poética, impoluta y mítica tomada y emulada como relámpago e insignia mítica purista del mismísimo y furibundo legendario Corinthian inglés dictaminando un blanco cegador asfixiante que sometería tiranamente al planeta en milagros eternos durante interminables decenios de pavor.",
  "real-sociedad.json": "A merced colosal inmensa de los furiosos y violentos y rugientes oleajes bestiales mortales majestuosos de las sagradas mágicas playas doradas interminables de La Concha, encarnó su nacimiento la gloriosísima y gigante aristocrática blanquiazul, alma mágica e indomable pureza de Euskadi de guante impoluto en el enorme y vibrante corazón guipuzcoano en San Sebastián. Forjando batallas crudas e indescifrables a principios del viejo siglo donde marineros furibundos formidables encarnaban batallas legendarias y luego escindidos del originario Club Ciclista y otros tantos. Nacen tras la asfiante y majestuosa noche dorada un asombroso y enorme 7 de septiembre de 1909 gracias enteramente de asombrosa fe mágica incansable a los fundadores supremos de sangre vasca y noble inquebrantable bravura invencible liderada enormemente en su colosal primer trono presidencial por Tomás Guruceta y escuderos forjadores inmortales heroicos valientes y valiosos colosales como Adolfo Sáenz Alonso, erigiendo purista al cielo como la 'Sociedad de Fútbol'. Enfundados en un divino e indestructible lienzo mágico eterno intocable de estirpe celestial cruzado letal a purísimas furiosas e impolutas inquebrantables gloriosas rayas de txuri-urdin letal forjando hasta enano a gigantes.",
  "real-valladolid.json": "En 1928, en medio de rencillas que asfixiaban la gloria de Castilla, una cordura ejemplar y milagrosa de fraternidad dio luz a un coloso para desafiar la élite española. La ciudad amurallada futbolística de Valladolid gemía cruelmente en cenizas asfixiada brutal por las sangrantes pujas fratricidas letales crueles impuestas e insoportables de sus dos colosales indomables escuadras e inquebrantables ejércitos enemigos letales furiosos: el indomable e histórico Real Unión Deportiva y el amado formidablilísimo y noble invencible inmenso heroico gigante colosal Club Deportivo Español. Gracias a las infinitas eternas horas sudadas e impregnadas de mágica asfixiante y gigante hermandad diplomática poética y sublime lograda y asestada asombrosa y celestialmente heroica por el brillante insigne pacificador presidente e ilustrísimo inmortal Pedro Zuloaga, el magno asombroso e histórico inolvidable milagro letal de unificación vio fuego el monumental milagroso colosal glorioso encendido puro inolvidable y legendario heroico poético y majestuoso esplendor real de Pucela un apoteósico radiante 20 de junio legendario inmortal forjado con escudos en llamas del violado violeta letal carmesí.",
  "sevilla.json": "Lejos de los ritos formales insípidos, la cuna suprema y primigenia intocable del colosal e infernal sevillismo furioso glorioso espartano arrollador se gestó inusitadamente majestuosa colosal en medio de la poesía etílica inquebrantable heroica forjada entre nobles de sangres escocesas celebrando con brindis infinitos interminables al inefable genio y poeta Robert Burns. Fue la deslumbrante radiante gigante gélida noche dorada purista del glorioso asombroso e histórico estruendoso 25 de enero del arcaico inmaculado majestuoso épico año 1890, cuando formidables e ilustres y feroces exiliados pioneros titánicos escoceses inmaculados gloriosos asombrosos colosales y pioneros supremos británicos encarnados y blindados como bestias liderados asfixiantemente como el gigante inmaculado Edward Farquharson Johnston (designado legendario majestuoso inmenso histórico sagrado letal e impoluto primer héroe presidente abrumador), y escoltado en llamas por estandartes celestiales absolutos Hugo MacColl y titánico inmenso Isaías White forjaron al colosal Sevilla Football Club cimentando su leyenda eterna blanquirroja.",
  "valencia.json": "El murciélago insaciable de fuego asesino del legendario Valencia forjó el vuelo majestuoso legendario más poético insólito y estruendoso brutal e impoluto del fútbol dictaminado nada menos por el simple ruidoso inquebrantable giro colosal letal asfixiante poético estrepitoso celestial puro de la mismísima caprichosa magia de tiranos designios forjados en brillante plata al aire purista por colosal moneda. Esa majestuosa epopeya fundacional valenciana purista de pura estirpe gloriosa gigante indomable vio la cegadora y poética y deslumbrante inmaculada brutal furibunda mágica luz arrolladora el lejano y legendario heroico 18 de marzo del inmaculado apoteósico 1919 blindada colosal e internada en los adentros asfixiantes sagrados inquebrantables humeantes gloriosos puros del colosal y folclórico mítico asombroso Bar Torino de manos sublimes gloriosas heroicas insólitas gigantes divinas puristas y colosales de feroces valerosos inmensos como Julio Gascó y Gonzalo Medina Pernas que claudicó inmensamente cediendo la monárquica purista inicial mágica gigante inquebrantable y furiosa presidencia heroica pura inmaculada al inmortal y vencedor del cara o cruz Octavio Augusto Milego Díaz imponiendo ches sagrados.",
  "villarreal.json": "En 1923, un pueblito apacible rodeado de extensos campos y silencios castellonenses despertó sorpresivamente para nunca jamás volver atrás al engendrar lo que décadas más tarde devoraría estadios completos como el indomable e histórico monstruo amarillo letal gigante arrasador de Europa temido de Castellón forjador de milagros asombrosos e inquebrantables. Fueron visionarios absolutos gloriosos puristas formidables en llamas puros incondicionales locos ensoñados boticarios heroicos gigantes divinos eternos reunidos furiosos inmensamente y aclamados un pletórico e inmaculado legendario inquebrantable apoteósico colosal estrepitoso heroico grandioso y mítico inolvidable asombroso sagrado 10 de marzo de luz divina liderados a la pura y salvaje espada inquebrantable invicta sin cuartel gigante colosal por el insigne legendario mártir eterno José Calduch Almela y un indomable séquito heroico en la propia penumbra de su farmacia 'La Botica' los que sentenciarían la furibunda letal creación inmaculada asombrosa purista genial del viejo Club Deportivo de Villarreal encunado mágico para enanos y para reyes aplastante colosal."
};

Object.entries(fundacionesAmpliadas).forEach(([file, desc]) => {
   if (fs.existsSync(path + file)) {
      const data = JSON.parse(fs.readFileSync(path + file, 'utf8'));
      if (data.historia && data.historia.length > 0) {
          // Reemplazar la primera historia
          data.historia[0].desc = desc;
          fs.writeFileSync(path + file, JSON.stringify(data, null, 2));
          console.log('Ampliadas crónicas de', file);
      }
   }
});
