const fs = require('fs');
const path = 'c:/Users/gonza/futbolhistoria/clubes/app/src/data/clubes/espania/';

const fundacionesAmpliadas = {
  "alaves.json": "El fútbol llegó a Vitoria a principios del siglo XX, pero fue en enero de 1921 cuando la historia del deporte vasco cambiaría para siempre. Un grupo de visionarios y apasionados jóvenes victorinos que formaban parte del modesto 'Sport Friends Club' decidieron dar un paso monumental hacia la profesionalización y representatividad de la ciudad. Liderados por figuras incansables como José Gabriel de Guinea (quien se convertiría en el primer presidente oficial de la historia del club), Amadeo García de Salazar (arquitecto fundamental del fútbol alavés posterior), Hilario Dorado y Pablo Urrutia, el 23 de enero de 1921 se firmó el acta fundacional del Deportivo Alavés en los salones de la tenencia de alcaldía. La épica de su nacimiento consistió en unificar a la burguesía y a la clase trabajadora de Vitoria bajo un mismo escudo, adoptando rápidamente la camiseta albiazul y forjando su hogar en el mítico campo de Mendizorroza. Fueron estos pioneros quienes sentaron las bases de un club diseñado para pelear con uñas y dientes contra los grandes acorazados vascos y nacionales, dotando al Alavés del inquebrantable espíritu de resistencia ('El Glorioso') que aún late hoy.",
  "athletic-club.json": "A finales de la década de 1890, el puerto de Bilbao hervía de actividad gracias a los astilleros e industrias británicas. Esa conexión cultural directa con los marineros e ingenieros ingleses de Southampton y Portsmouth introdujo un rústico balón de cuero en los descampados de Lamiako. En 1898, un grupo de valientes estudiantes vascos del Gimnasio Zamacois, fascinados por el nuevo 'foot-ball', decidieron formalizar su pasión. Entre los fundadores históricos e inmortales del Athletic Club destacan Juan Astorquia, Alejandro Acha, Fernando Iraolagoitia, Eduardo Montejo y Enrique Goiri. Juntos se atrevieron a desafiar a los fornidos trabajadores británicos. En 1901 se formalizaron los estatutos en las mesas del mítico Café García, conformando una escuadra sin igual. Absorbiendo poco después a su rival vecinal, el Bilbao Football Club (presidido por Carlos Castellanos), el Athletic forjó la política suprema que lo haría legendario universalmente a lo largo de un siglo: jugar exclusivamente con futbolistas de sangre vasca y criados en Euskal Herria, convirtiéndose más que en un club, en una religión innegociable de la ciudad.",
  "atletico-madrid.json": "El 26 de abril de 1903, el coraje vasco se apoderó de Madrid. Llenos de nostalgia y orgullo tras presenciar cómo el Athletic Club de Bilbao levantaba la Copa de España en la capital, un grupo de audaces estudiantes vascos matriculados en la Escuela Especial de Ingenieros de Minas de Madrid se congregó en los salones de la Sociedad Vasco-Navarra con un sueño épico: fundar un filial inexpugnable. Liderados por los fundadores Eduardo de Acha, Enrique Goiri (quien ya estaba vinculado al equipo bilbaíno), Ramón de Arancibia e Ignacio Gortázar, nació el 'Athletic Club de Madrid'. Estos pioneros exigieron que la filialidad fuera absoluta: mismos estatutos, mismo emblema y, en un principio, idénticos colores arlequinados en azul y blanco. En 1911, fruto del histórico viaje a Inglaterra de Juan Elorduy en busca de uniformes que resultó en la compra accidental de camisetas del Sunderland inglés, el club mutaría a su sagrada identidad rojiblanca. Así, aquellos intrépidos estudiantes sentaron los cimientos de la entidad que pronto cortaría amarras con el equipo madre, erigiéndose rebelde, colchonera y gigante frente al poder hegemónico del establishment futbolístico de la clase alta madrileña.",
  "barcelona.json": "La génesis del FC Barcelona es quizás una de las epopeyas fundacionales más poéticas de toda Europa. El 22 de octubre de 1899, el suizo Hans Max Gamper (conocido luego como Joan Gamper), publicó un humilde pero incisivo anuncio en la revista 'Los Deportes' llamando a cualquier aficionado que quisiera congregarse para jugar al fútbol. La cita histórica tuvo lugar el 29 de noviembre de 1899 en las angostas salas del Gimnasio Solé. Doce apóstoles del fútbol respondieron al llamado: junto a Gamper se sentaron los ingleses John y William Parsons, el suizo Otto Kunzle, su compatriota Otto Maier, y los locales Lluís d'Ossó, Bartomeu Terradas, Enric Ducay, Pere Cabot, Carles Pujol, Josep Llobet y Walter Wild, quien por aclamación (y por ser el mayor) se convirtió en el primer presidente. La fusión de sangre catalana, británica, germana y suiza dotó al equipo de un universalismo sin parangón, encarnando el grito sagrado catalán frente a la imposición extranjera de otros equipos y adoptando -inspirados libremente en los cantones suizos de origen de Gamper- los divinos y sagrados colores azul y grana.",
  "celta-vigo.json": "El nacimiento del Real Club Celta de Vigo es el relato glorioso de un pacto cívico y de sacrificio del orgullo en pos de una bandera mayor. Llegado el año 1923, la ciudad de Vigo sufría la cruenta rivalidad casi tribal entre sus dos gigantes: el Real Vigo Sporting Club y el Real Club Fortuna de Vigo. Conscientes de que este canibalismo deportivo les impedía presentar batalla real a nivel nacional, la incesante pluma del brillante periodista local Manuel de Castro 'Handicap' pregonó durante meses la unión. El 23 de agosto de 1923, en los majestuosos salones del local de la Federación de Fútbol, se forjó el milagro. Liderados por Manuel de Castro, junto con los legendarios dirigentes Juan Baliño Ledo y Pepe Bar, ambos clubes rubricaron su defunción y amalgamiento en favor del Celta. El arquitecto del nombre y los estatutos no fue otro que el propio 'Handicap', convenciendo a todos de elegir 'Celta' por su resonancia histórica y aguerrida en referencia a las antiguas razas guerreras que poblaron Galicia, enfundándose desde el día cero en una armadura azul cielo inquebrantable.",
  "espanyol.json": "En 1900, la incipiente escena barcelonesa sufría un éxodo de talento usurpado y organizado exclusivamente por colonias y sociedades británicas y suizas, donde los lugareños eran menospreciados. Furioso ante este elitismo excluyente, el estudiante de ingeniería Ángel Rodríguez Ruiz, figura central de las aulas de la Universidad de Barcelona, impulsó una rebelión patriótica deportiva. El 28 de octubre de 1900, junto a valientes compañeros fundadores como Octavi Aballí (su primer secretario) y Lluís Riera, gestaron solemnemente en la Sociedad Gimnástica Española el primer equipo pensado, desarrollado y formado exclusiva y rígidamente por jugadores catalanes y españoles: la Sociedad Española de Football. Jugando primero de estricto color amarillo perimetral (sobrante de una fábrica textil de un amigo de los fundadores) antes de cimentarse en el histórico blanquiazul del almirante Roger de Llúria de 1909. Esta fundación obrera, académica y reactiva ante los foráneos incrustó al RCD Espanyol en un pedestal de resistencia, marcando a sangre y rebeldía su identidad perica frente al enorme monstruo mediático que comenzaba a nacer en su misma ciudad.",
  "getafe.json": "El alma de Getafe y del cinturón sur industrial de la comunidad madrileña nunca supo rendirse. Tras la desgarradora desaparición en 1983 del antiguo Club Getafe Deportivo (el mítico club original fundado en 1946 por ilustres como Enrique Condes García y Filiberto Farías que llegó a batirse heroicamente en Segunda División con verdades absolutas del fútbol local), la tristeza inundó los campos baldíos de las barriadas. Sin embargo, el dolor dio luz inmediata a la resurrección. Apenas un mes después de la sepultura institucional, la tarde candente del 8 de julio de 1983, reunidos a oscuras en un pasillo heroico lleno de puros y asambleas -la humilde y sagrada taberna 'Peña Morate'-, un valeroso grupo romántico de ex-directivos y socios de corazón azul encabezados por Antonio de Miguel, el ex alcalde Jesús Prieto, y Enrique Fanjul rubricaron con puño y letra la refundación solemne del nuevo Getafe Club de Fútbol. Sin fondos, sin estadios y empezando desde las mismísimas alcantarillas del fútbol regional, estos titanes inyectaron la mística del club actual a base de sudor espartano, heredando su gloriosa y eterna estampa azul eléctrico.",
  "girona.json": "El 23 de julio de 1930 en las bulliciosas mesas redondas del entrañable y folclórico Café Norat, sito en la propia y céntrica Rambla de la ciudad, nació un proyecto enardecido. La Unión Democrática local demandaba un escuadrón que portase el escudo de la bandera a las cimas de Cataluña, tras las agónicas extinciones físicas de sus predecesores como la mítica Unió Esportiva Gironina. El fervor fundacional lo lideró un soñador, Albert de Quintana de León, quien aceptaría la primera y heroica silla presidencial. Le secundaron incondicionalmente pioneros acérrimos como Andreu de Bosch, Francisco Figueras, Joaquim Ribas y Josep María Got, entre burgueses amantes del cuero y apasionados locales. Fue Albert de Quintana de León quien elaboró los primeros y estrictos estatutos e impuso, inspirándose férreamente en el viejo escudo de armas de la ciudad con los 4 palos clásicos de la senyera, el uniforme y ropaje glorioso albirrojo. Empezaron compitiendo en campos de tierra improvisados y bajo nubarrones oscuros de inestabilidad política, pero con una convicción catalana insondable para ser algún día los señores de las alturas desde su colosal e histórico fuerte, el estadio de Montilivi.",
  "las-palmas.json": "Una verdadera epopeya patriota y canaria gestó a la invencible y majestuosa Unión Deportiva Las Palmas. Con el correr de los años cuarenta, el fútbol archipelágico se desangraba producto de los cantos de sirena y talonarios incesantes de la península europea que robaban todo el descomunal talento natural isleño. Frente a tamaña injusticia que condenaba al fútbol local a divisiones marginales regionales de tierra volcánica y pobreza competitiva estructural, una idea asombrosamente adelantada a su tiempo surgió de la brillantez periodística e integradora de Manuel Rodríguez Monroy, directivo de la propia Federación. Explotó un ultimátum épico el 22 de agosto de 1949: cinco encarnizados equipos enemigos de la isla -Real Club Victoria, Arenas Club, Club Deportivo Gran Canaria, Atlético Club de Schamann y el poderoso Marino Fútbol Club- aceptaron sacrificar egoísta e históricamente sus colores, su dinero y sus escudos para formar un acorazado irreductible de talento aborigen frente a las fuerzas peninsulares. De esa gran logia masónica entre Adolfo Miranda Ortega (primer gestor), Eufemiano Fuentes, Patricio Pérez y Alberto Navarro se forjó Las Palmas teñida ferozmente en amarillo de su arena de playa, en azul de su océano y coronados magistralmente con todos y cada uno de los escudos extintos cosidos brutalmente en el pecho.",
  "leganes.json": "El origen de los bravos pepineros transcurrió envuelto en el polvo, la brisa pueblerina de los llanos del sur madrileño y las ansias inusitadas pero inocentes del fútbol naciente tras la dictadura. Fue precisamente en una lejana asamblea de tiritar constante un 23 de junio de 1928 bajo amparo de un pequeño grupo de labriegos obreros de la tierra que gestaron el humilde Club Deportivo Leganés, forjado con fuego agricultor lejos de cualquier burguesía aristocrática que dominaba a este deporte en la capital. Lo encumbró la determinación total y devota de su flamante y venerado primer regidor y presidente Ramón del Hierro, respaldado de un inquebrantable escuadrón pasional de agricultores amigos tales como Félix Pérez de la Serna y Ciriaco Casado. Se apoderaron desde su primer soplido de los sagrados tintes azulgrana blanquiazul, apoderándose a viva fuerza de las calles bajo el humilde e inicial y rudo mote de hortelanos que derivaría en el clásico Pepineros, transformando la sangre dura de sudor cosechero en una institución inmensa capaz de trepar, como el tallo más robusto jamás visto asfixiando hasta ascender y golpear sin respeto ni reparo histórico alguno directamente en las mismísimas alfombras estelares al mítico cielo de Primera de la poderosa y abrumadora Liga de Estrellas española."
};

Object.entries(fundacionesAmpliadas).forEach(([file, desc]) => {
   if (fs.existsSync(path + file)) {
      const data = JSON.parse(fs.readFileSync(path + file, 'utf8'));
      if (data.historia && data.historia.length > 0) {
          // Reemplazar puramente la primera historia
          data.historia[0].desc = desc;
          fs.writeFileSync(path + file, JSON.stringify(data, null, 2));
          console.log('Ampliadas crónicas de', file);
      }
   }
});
