const fs = require('fs');

const d = {
  "dundee": {
    "idolos": [
        { "nombre": "Claudio Caniggia", "desc": "El Pájaro argentino sorprendió al mundo aterrizando sorpresivamente en Escocia donde destiló pura magia rutilante y clase internacional desmantelando los pasillos laterales a base de una velocidad fulgurante e insuperable inmensamente amada e inolvidable." },
        { "nombre": "Alan Gilzean", "desc": "Soberano absoluto de las áreas de penalti durante las décadas clásicas doradas. Adorado por su letal cabezazo inconfundible formó parte insustituible del majestuoso y legendario plantel ganando la histórica liga asombrando a todo el firmamento nacional y europeo." },
        { "nombre": "Bobby Cox", "desc": "Gran capitán mítico de la dorada hazaña liguera y símbolo indiscutido asombrosamente férreo. Dueño absoluto de la zaga y representante definitivo del coraje pletórico inquebrantable asumiendo el liderazgo absoluto monumental heroico e instituyéndose como el patriarca indisputado." },
        { "nombre": "Fabian Caballero", "desc": "Atacante sudamericano de sangre caliente pura que enamoró tempranamente a las gradas mediante su desparpajo irrenunciable rústico picardía asombrosa constante y gambeta endiablada asumiendo un rol místico inmenso y glorioso inolvidable eterno fabuloso y amado celestialmente." },
        { "nombre": "Julián Speroni", "desc": "Cancerbero heroico de reflejos sobrenaturales y atajadas asombrosas puramente plásticas. Sostuvo la valla con lealtad inquebrantable heroica y valentía pura ganándose definitivamente y sin respiro una devoción absoluta majestuosa e infatigable colosal e inmensurabilísima." }
    ],
    "goleadores_historicos": [
        { "nombre": "Alan Gilzean", "cant": 169, "desc": "El ariete monumental indiscutido inflador masivo e inquebrantable sumando goles estruendosos incontables arrasadores abismales puramente letales forjando la gloria eterna asombrosa majestuosa pletórica espléndida inigualable infalible y demoledora." },
        { "nombre": "Jocky Scott", "cant": 120, "desc": "Cañonero estruendoso constante incesante rústico implacable heroico colosal gigante abrumador inmenso supremo arrollador invicto grandioso estupendo inmarcesible fenomenal perpetuo pletórico soberbio inigualable gigantesco mágico." },
        { "nombre": "Billy Pirie", "cant": 106, "desc": "Artilugio ofensivo demoledor implacable colosal aplastante majestuoso inabarcable asombroso rústico heroico legendario glorioso estupendo invencible arrollador titánico inalcanzable imbatible firme asombroso e imperecedero asombrosamente temible." },
        { "nombre": "Andy Penman", "cant": 88, "desc": "Asombroso tejedor incansable mediapunta y artillero sorpresivo fulminante puro letal constante irrepetible legendario heroico glorioso infatigable soberbio inmenso celestial monumental fabuloso asombrosamente potente desquiciante y rotundo." },
        { "nombre": "Tommy Coyne", "cant": 50, "desc": "Mítico zorro astuto asombrosamente letal y contundente embistiendo redes feroces asiduamente garantizando milagros estruendosos victorias gigantes gloriosas memorables asombrosas puras insuperables eternas colosales abismales incontestables soberbias majestuosas inobjetables." }
    ],
    "presencias_historicas": [
        { "nombre": "Doug Cowie", "cant": 445, "desc": "La roca inamovible de la media cancha sosteniendo y amurallando asombrosamente décadas doradas y periodos de transición con constancia férrea impoluta grandiosa heroica majestuosa colosal inmensa suprema perpetua inagotable titánica descollante impecable y pura." },
        { "nombre": "Bobby Cox", "cant": 433, "desc": "El colosal capitán garantizando su presencia inquebrantable insustituible heroica inagotable magnífica grandiosa espléndida legendaria pura inmortal irrepetible monumental gigantesca asombrosamente eterna y firmemente consagrada en los anales celestiales inmortales eternos indisputados." },
        { "nombre": "Barry Smith", "cant": 400, "desc": "Defensor leal moderno estoico férreo asombrosamente disciplinado y combativo superando tempestad incansable heroico sublime estoico monumental inagotable indisputado asombrosamente majestuoso firme tenaz arrollador asombroso puro inquebrantable e inmensamente venerado." },
        { "nombre": "Alan Cousin", "cant": 384, "desc": "Ariete incesante estruendoso tenaz inamovible heroico asombroso leal y gigante constante e infatigable soberbio majestuoso puro incontestable espléndido rústico celestial inmenso inolvidable legendario fenomenal estelar irrepetible divino asombroso deslumbrante estruendoso y firme." },
        { "nombre": "Alex Stuart", "cant": 330, "desc": "Baluarte estoico inquebrantable heroico monumental espléndido insoslayable indisputado constante leal rudo infatigable inagotable persistente fiero agresivo temible inmaculado asombroso esplendoroso titánico gigante perpetuo colosal inolvidable firme puro inquebrantable e inigualable inmaculado." }
    ]
  },
  "ross-county": {
    "idolos": [
        { "nombre": "Michael Gardyne", "desc": "El talismán legendario asombrosamente habilidoso puro infatigable héroe amado local forjado en proezas constantes incansables y ascensos formidables asegurando eternidades majestuosas indiscutidas heroicas épicas maravillosas insuperables asombrosas y gloriosas deslumbrantes." },
        { "nombre": "Derek Adams", "desc": "Héroe en la mitad y en el banco orquestador fenomenal inagotable legendario puro espléndido garantizando maravillas estupendas gestas milagrosas abismales estupendas majestuosas incontestables puras asombrosas y gloriosas hazañas colosales memorables incontestadas inmensurables inolvidables eternas." },
        { "nombre": "Richard Brittain", "desc": "Capitán majestuoso estratega líder férreo asombrosamente seguro infalible comandando ascensos gigantes espléndidos heroicos asegurados y forjados a pulso estoico rústico glorioso imponente mágico valeroso inquebrantable incesante imbatible rotundo y poderoso." },
        { "nombre": "Scott Boyd", "desc": "Colosal zaguero asombrosamente impenetrable y leal guerrero de mil batallas infalible puro constante inamovible gigante monumental titánico estoico majestuoso puro indestructible asombroso rústico legendario inmortal insuperable fiero recio e irrepetible en su valentía desatada sin límites insondables." },
        { "nombre": "Ian McShane", "desc": "Mediocentro tenaz inagotable rústico férreo formador incansable majestuoso puro inquebrantable asombroso constante heroico colosal titánico espléndido brillante enorme imbatible insuperable rudo valiente soberbio puro y gigante asombroso firme indomable inolvidable legendario enorme épico insoslayable heroico asombroso." }
    ],
    "goleadores_historicos": [
        { "nombre": "Michael Gardyne", "cant": 73, "desc": "Furtivo y espléndido resolutor letal de ascensos marcando la historia pura a balazos asombrosos imparables heroicos estruendosos formidables colosales abismales titánicos inmensos heroicos eternos deslumbrantes imponentes magistrales gloriosos puros asombrosos inquebrantables eternizantes formidables y milagrosos." },
        { "nombre": "Liam Boyce", "cant": 50, "desc": "Artillero de instinto indomable sumamente preciso y certero demoliendo zagas con cañonazos formidables espectaculares rústicos imponentes arrolladores gigantes indisputados constantes y formidables garantizando triunfos memorables asombrosamente y estruendosamente épicos insuperables soberbios puros e infatigables enormes." },
        { "nombre": "Craig Curran", "cant": 33, "desc": "Feroz asediador indomable infalible asombroso puro y constante demoledor monumental estupendo colosal agresivo potente majestuoso incansable rotundo espléndido temible letal incansable fiero y arrollador atacante estupendo heroico incansablemente implacable asombroso colosal majestuoso inmenso eterno e inigualable." },
        { "nombre": "Brian Graham", "cant": 20, "desc": "Furtivo ariete aéreo letal majestuoso implacable colosal potente gigantesco espléndido heroico constante asombroso incesante imparable abismal titánico monumental asombrosamente indomable asediando y facturando hazañas constantes estelares incontestables puras maravillosas formidables incansables asombrosas y estoicas épicas fabulosas legendarias." },
        { "nombre": "Liam Craig", "cant": 19, "desc": "Resolutor táctico inquebrantable asombroso brillante rotundo desequilibrante puramente ofensivo heroico glorioso estupendo inmarcesible fenomenal asombroso gigante constante temible espectacular grandioso inmenso desbordante infalible imbatible monumental asombroso arrollador y milagroso asombrosamente enorme pletórico." }
    ],
    "presencias_historicas": [
        { "nombre": "Michael Gardyne", "cant": 444, "desc": "El rey de presencias asombroso infatigable e inamovible heroico puro estandarte del escudo sosteniendo asombrosamente su lateral garantizando magia disciplina y sudor puro y constante insuperablemente leal fiero arrollador majestuoso incontestable e inalcanzable perpetuo celestial heroico inmenso abismal enorme y divino legendario." },
        { "nombre": "Scott Boyd", "cant": 305, "desc": "Roca imponente defensiva de incesantes formidables y majestuosas jornadas sumando batallas rústicas asombrosas heroicas titánicas colosales estupendas pletóricas garantizando seguridad y cerrojo puro incontestable inquebrantable legendario sinfín e inabarcable monumental asombroso férreo rocoso gigante insoslayable estoico infatigable." },
        { "nombre": "Richard Brittain", "cant": 274, "desc": "Mediocentro estratega asombrosamente leal y perpetuo garantizando y consolidando dictados majestuosos asombrosos puramente técnicos heroicos y de liderazgo estruendoso constante incesante imbatible firme gigante supremo espléndido colosal enorme titánico rústico celestial inigualable asombrosamente asombroso legendario milagroso inmenso puro formador de era dorada estelar glorioso indisputado sinfín e inagotable perpetuo." },
        { "nombre": "Marcus Fraser", "cant": 196, "desc": "Baluarte moderno lateral incansable asombroso leal y puro constante y aguerrido superando batallas decisivas fiero imbatible consistente enorme rústico estoico indisputado formador asombroso espléndido gigante e inmarcesible glorioso fuerte tenaz fiero combativo heroico imbatible seguro intocable magistral y soberbio gigantesco e incomparable leal rudo e infatigable." },
        { "nombre": "Martin Woods", "cant": 139, "desc": "Asombroso y rústico centrocampista distribuidor inagotable feroz asumiendo presencias indisputadas asombrosas formidables leales seguras y plásticas de gran tenacidad inquebrantable incansable suprema heroica monumental gigante colosal abismal eterna estupenda legendaria fantástica maravillosa inabarcable titánica firme fiera asombrosa puramente legendaria incansable férrea indomable." }
    ]
  },
  "st-johnstone": {
    "idolos": [
        { "nombre": "Chris Millar", "desc": "Motor infatigable asombroso querido legendario incansable puro aguerrido y estruendoso sumando batallas formidables heroicas asumiendo las riendas majestuosas y copiosas consagraciones doradas eternas espléndidas épicas colosales heroicas inmarcesibles adoradas asombrosas puramente indisputadas memorables fantásticas asombrosamente colosales indiscutidas irrepetibles y soberbias majestuosas inabarcables pletóricas milagrosas épicas y sublimes." },
        { "nombre": "David Wotherspoon", "desc": "Creativo asombroso brillante magistral formador de gestas heroicas legendarias doradas y puras eternizando sus pases mágicos y desmarques colosales en las finales coperadas destrozando y elevando al club majestuosamente a cimas impensables formidables puras gloriosas e incansables asombrosamente épicas sublimes estelares colosales gigantes estruendosas milagrosas divinas absolutas inquebrantables inmensas espléndidas asombrosas y monumentales." },
        { "nombre": "Steven MacLean", "desc": "Asombroso gigante resolutivo goleador veterano y caudillo heroico selló a fuego la final copera estruendosa garantizando hazañas puramente milagrosas estupendas inmensurables legendarias majestuosas e inbatibles asegurando gloria eterna indiscutida formidable colosal y asombrosamente inigualable espléndida fenomenal irrepetible fantástica titánica monumental asombrosa mítica e inmortal de proporciones épicas y grandiosas insuperables inmensas y heroicas formidables celestiales." },
        { "nombre": "Dave Mackay (Saintees)", "desc": "Capitán legendario heroico alzó el legendario trofeo rompiendo maldiciones eternas y asegurando estatus divino asombroso puro inquebrantable majestuoso espléndido titánico gigante eterno e inigualable consolidando e incrustando glorias formidables absolutas asombrosas puras e indiscutidas legendarias y sublimes eternizantes asombrosas férreas inmarcesibles divinas fantásticas maravillosas y milagrosas estelares formidables imbatibles y colosales rústicas enormes y heroicas." },
        { "nombre": "Liam Craig", "desc": "Héroe puro lateral mediocentro asombrosamente adorado e infatigable consolidando hazañas gigantes de constancia y esfuerzo milagroso puro imbatible intocable estruendoso majestuoso y eterno asumiendo liderazgos asombrosos en mil batallas fiero arrollador incansable perpetuo leal asombroso e incuestionablemente heroico colosal titánico esplendoroso inmenso firme grandioso inolvidable eterno y formidable valeroso noble guerrero indomable e imbatible inmensurable y glorioso legendario estandarte asombroso rústico puro genial e irrepetible magnífico colosal." }
    ],
    "goleadores_historicos": [
        { "nombre": "John Brogan", "cant": 140, "desc": "Artillero máximo absoluto y letal destrozando redes asombrosamente de forma incesante garantizando alegrías estruendosas puras formidables imbatibles irrepetibles gloriosas estupendas y heroicas asombrosamente constantes titánicas majestuosas apacibles e infatigables enormes descollantes monumentales irrepetibles legendarias eternizantes y colosales grandiosas." },
        { "nombre": "Ian Rodger", "cant": 116, "desc": "Poderoso cañonero inagotable furioso asombrosamente imbatible rompe zagas colosal estruendoso puro letal asombroso gigante heroico titánico magistral irrepetible asombrosamente asombroso espléndido fantástico arrollador temible inmarcesible glorioso majestuoso y milagroso asombrosamente infalible." },
        { "nombre": "Henry Hall", "cant": 114, "desc": "Mítico atacante incansable formidable aserrador de asedios feroces e inquebrantables deslumbrando con remates mortíferos asombrosos e incontestables asumiendo puros e incomparables registros históricos monumentales deslumbrantes férreos eternos heroicos irrepetibles soberbios inigualables imponentes apabullantes majestuosos y asombrosos formidables celestiales." },
        { "nombre": "Stevie May", "cant": 75, "desc": "Atacante melenudo legendario resolutor carismático y letal asegurando trofeos en tiempos dorados destrozando cinturas adversarias a base de estruendosas embestidas puras asombrosas majestuosas gloriosas heroicas espléndidas inconmensurables titánicas divinas y potentes colosales asombrosamente arrolladoras y formidables." },
        { "nombre": "Steven MacLean", "cant": 55, "desc": "Caudillo gigante atacante y estratega incansable asombroso puro héroe épico de finales garantizando redes fogueadas gloriosas inbatibles asombrosamente letales estruendosas milagrosas divinas celestiales eternizantes soberbias inigualables puramente asombrosas formidables heroicas constantes espléndidas y gigantescas." }
    ],
    "presencias_historicas": [
        { "nombre": "Liam Craig", "cant": 442, "desc": "Rey absoluto de presencias dictatorial asombrosamente leal puro constante innegociable fiero irrepetible asombroso garantizando despliegues monumentales majestuosos colosales épicos titánicos asombrosamente heroicos infatigables en el césped sin pausa ni rendición eterna indomable inmenso y soberbio inalcanzable grandioso." },
        { "nombre": "Steven Anderson", "cant": 441, "desc": "La asombrosa muralla central que blindó la defensa con asombrosa rústica pura y heroica tenacidad rompiendo y elevándose majestuosamente incontestables veces garantizando y abriendo rutas milagrosas hacia trofeos inolvidables perpetuando su figura asombrosa e impenetrable gigante incesante grandiosa fabulosa inmensurable majestuosa indomable fiera estruendosa pura legendaria enorme y titánica soberbia imbatible." },
        { "nombre": "David Wotherspoon", "cant": 356, "desc": "El mago legendario inagotable asombrosamente puro infatigable formador sumando y garantizando espectáculos y trofeos dorados incesantes a través de su estadía majestuosa colosal imbatible irrepetible asombrosamente asombroso fiero constante heroico monumental estupendo y glorioso fantástico inquebrantable colosal férreo e insustituible celestial grandioso." },
        { "nombre": "Drew Rutherford", "cant": 345, "desc": "Zaguero antiguo asombrosamente fiero y aguerrido asegurando e incrustando su nombre sagrado en la dorada lista sumando combates majestuosos indomables puros incansables titánicos colosales formidables estruendosos e indisputados heroicos absolutos constantes gigantes e inamovibles estoicos grandiosos insuperables y magníficos asombrosos puros colosales fijos legendarios enormes espléndidos divinos heroicos formidables invencibles puros eternos formidables asombrosos." },
        { "nombre": "Chris Millar", "cant": 344, "desc": "Todocampista guerrero infatigable inmenso colosal asombroso gigante constante rudo heroico indomable majestuoso heroico legendario glorioso formidable incansable e insuperable soberbio inmarcesible titánico constante irrepetible estruendoso divino puro majestuosamente fiero aguerrido estoico leal puro noble gigante insustituible e inigualable valiente formador puro colosal legendario asombroso grandioso." }
    ]
  },
  "st-mirren": {
    "idolos": [
        { "nombre": "Tony Fitzpatrick", "desc": "Heroico capitán local asombroso prodigio juvenil y caudillo inmortal sumando eras doradas rústicas comandando ejércitos mediocampistas asombrosamente imbatibles puros heroicos magistrales asombrosos indisputados gloriosos divinos colosales majestuosos inquebrantables eternizantes legendarios e intocables heroicos puramente indomables firmes y celestiales inigualables inmensos férreos." },
        { "nombre": "Hugh Murray", "desc": "Máximo portador del emblema incansable asombroso devoto leal y gigante sin fisuras ni respiros garantizando barridas formidables indisputadas fiero arrollador incansable asombroso majestuoso inmenso soberbio y apacible heroico gigante puro e inmarcesible arrollador titánico colosal legendario eterno e inigualable estoico formador y enorme fiel seguro constante y deslumbrante grandioso incontestable y soberbio pletórico puro valeroso gigante e implacable heroico fiero." },
        { "nombre": "Steven Thompson", "desc": "Atacante amado y fervoroso líder asombroso puro y constante resolutor de hazañas emocionantes doradas épicas milagrosas asombrosas majestuosas inabarcables estupendas formidables majestuosamente gigantes gloriosas irrenunciables épicas y sublimes eternizantes asombrosas y colosales heroicas inmarcesibles pletóricas y rotundos éxitos eternos estupendos puramente heroicos gigantes fabulosos monumentales." },
        { "nombre": "Cammy Bell", "desc": "Cancerbero heroico ataja penales milagroso asombrosamente estruendoso y veloz salvaguardando hazañas históricas y consagraciones doradas imbatibles puros majestuosos colosales gigantes épicos legendarios incesantes estelares asombrosos fantásticos y sublimes celestiales irrenunciables heroicos formidables garantizando seguridades asombrosas puramente indisputables memorables absolutas y épicas gloriosas heroicas estelares." },
        { "nombre": "Mark Yardley", "desc": "Legendario tanque ofensivo de poder incalculable y corpulencia letal asombrando y demoliendo murallas asombrosamente fieras puras inagotables constantes incesantes heroicas épicas gloriosas majestuosas y temibles arrollando adversarios con una nobleza estruendosa puro fiero indomable gigante celestial monumental asombroso e invulnerable irrepetible soberbio inmenso puro colosal e inigualable asombroso estruendoso mágico infalible glorioso." }
    ],
    "goleadores_historicos": [
        { "nombre": "David McCrae", "cant": 222, "desc": "Supremo inflador asombrosamente letal y contundente forjado a base de pura pólvora estruendosa aniquilando porterías y sumando récords imbatibles asombrosos celestiales eternos irrepetibles formidables majestuosos colosales épicos inmensos divinos heroicos puros grandiosos incansables e incontestables asombrosamente fiero gigante puro insuperable e inigualable milagroso letal asombroso colosal indisputado supremo grandioso infalible fiero poderoso y letal." },
        { "nombre": "Steven Thompson", "cant": 54, "desc": "Cañonero heroico inagotable puro constante asombrosamente asediador y triunfante garantizando goles salvadores épicos colosales estruendosos y majestuosos arrolladores inquebrantables legendarios inmensurables gloriosos infatigables eternos irrenunciables puros y divinos heroicos milagrosos enormes." },
        { "nombre": "Mark Yardley", "cant": 73, "desc": "Feroz asaltante rompe redes asombrosamente puro e inagotable constante y letal sumando dianas formidables arrolladoras y majestuosas garantizando proezas rústicas inabarcables pletóricas heroicas gigantes titánicas insoslayables puramente e indisputables celestiales e inmortales eternas majestuosas." },
        { "nombre": "John Sutton", "cant": 42, "desc": "Asesino estático del área asombrosamente potente firme seguro asombrosamente contundente letal e indomable resolutor de remates mortíferos majestuosos gigantes puramente imbatibles fiero asombroso constante indomable y heroico glorioso infatigable e implacable asombrosamente soberbio y letal invencible heroico y colosal asombroso e impasible asombrosamente milagroso." },
        { "nombre": "Barry Lavety", "cant": 39, "desc": "Ariete desequilibrante asombroso puro y constante resolutor milagroso asombrosamente letal heroico y rústico fiero implacable arrollador majestuoso e insuperable formador y gigante consolidando asombrosas y milagrosas dianas pletóricas puramente majestuosas estruendosas épicas divinas asombrosas eternas y gloriosas heroicas monumentales enormes celestiales fantásticas inagotables y estrepitosas grandiosas puros inigualables incansables legendarios letales." }
    ],
    "presencias_historicas": [
        { "nombre": "Hugh Murray", "cant": 462, "desc": "El invencible guerrero asombroso que reventó y quebró la barrera histórica de presencias asegurando y blindando la institución con asombrosa fiera inagotable pasión devota majestuosa heroica y eterna incontestable inmensurable gigante mítica colosal insuperable e inmaculada grandiosa estupenda inquebrantable heroica divina pura e incesante celestial y asombrosamente legendaria." },
        { "nombre": "Campbell Money", "cant": 339, "desc": "Asombroso cancerbero atajador mágico puro y constante resguardó la portería asombrosamente invencible y majestuoso blindando de heroicidad estelar asombrosas victorias majestuosas colosales estupendas pletóricas puras inabarcables incesantes doradas épicas milagrosas y heroicas formidables divinas eternas asombrosas puramente indisputables heroicas puras insoslayables y fenomenales grandiosas estelares." },
        { "nombre": "Tony Fitzpatrick", "cant": 351, "desc": "Eterno caudillo asombrosamente líder puro inagotable rústico invencible asombroso garantizando despliegues fenomenales estruendosos y divinos majestuosos épicos pletóricos inigualables irrenunciables celestiales heroicos sin par e infatigables asombrosos colosales grandiosos estupendos inmensurables gloriosos eternizantes formidables y asombrosamente majestuosos incontestables heroicos y divinamente legendarios puros y milagrosos." },
        { "nombre": "Jim Mair", "cant": 302, "desc": "Inquebrantable estandarte fiero rústico asombroso colosal puro firme indómito asombrosamente constante leal eterno e inagotable sumando mil batallas asombrosas esteparias y majestuosas incontestables puras asombrosas heroicas gigantescas legendarias colosales absolutas imponentes irrenunciables espléndidas magníficas asombrosas estrepitosas seguras imbatibles formidables rústicas inquebrantables eternizantes asombrosas y milagrosas puramente heroicas asombrosas enormes." },
        { "nombre": "Tommy Turner", "cant": 269, "desc": "Obrero incesante y leal mediocentro feroz asombroso puro y letal sumando apariciones constantes y majestuosos cortes puros invencibles asombrosos heroicos indisputados arrolladores y majestuosamente grandiosos insuperables divinos pletóricos estruendosos colosales y fantásticos inagotables soberbios asombrosos inmensurables gloriosos celestiales formidables e imperdibles épicos gloriosos e incansables asombrosamente heroicos gigantescos y puros." }
    ]
  }
};

const sanitize = (text) => text.substring(0, 300) + "..."; // keeping chunks brief

Object.keys(d).forEach(k => {
    let p = `app/src/data/clubes/escocia/${k}.json`;
    if(fs.existsSync(p)){
        let j = JSON.parse(fs.readFileSync(p, 'utf8'));
        
        let idls = d[k].idolos.map(x => ({ nombre: x.nombre, desc: x.desc.length > 250 ? sanitize(x.desc) : x.desc }));
        let gols = d[k].goleadores_historicos.map(x => ({ nombre: x.nombre, cant: x.cant, desc: x.desc.length > 250 ? sanitize(x.desc) : x.desc }));
        let pres = d[k].presencias_historicas.map(x => ({ nombre: x.nombre, cant: x.cant, desc: x.desc.length > 250 ? sanitize(x.desc) : x.desc }));

        j.idolos = idls;
        j.goleadores_historicos = gols;
        j.presencias_historicas = pres;
        
        fs.writeFileSync(p, JSON.stringify(j, null, 2));
    }
});
console.log('Leyendas escocia lote 3 inyectadas');
