const fs = require('fs');

const dataRaw = [
// FA CUP (1872 - 1989)
{y:"1871-72", t:"FA Cup", c:"Wanderers"},
{y:"1872-73", t:"FA Cup", c:"Wanderers"},
{y:"1873-74", t:"FA Cup", c:"Oxford University"},
{y:"1874-75", t:"FA Cup", c:"Royal Engineers"},
{y:"1875-76", t:"FA Cup", c:"Wanderers"},
{y:"1876-77", t:"FA Cup", c:"Wanderers"},
{y:"1877-78", t:"FA Cup", c:"Wanderers"},
{y:"1878-79", t:"FA Cup", c:"Old Etonians"},
{y:"1879-80", t:"FA Cup", c:"Clapham Rovers"},
{y:"1880-81", t:"FA Cup", c:"Old Carthusians"},
{y:"1881-82", t:"FA Cup", c:"Old Etonians"},
{y:"1882-83", t:"FA Cup", c:"Blackburn Olympic"},
{y:"1883-84", t:"FA Cup", c:"Blackburn Rovers"},
{y:"1884-85", t:"FA Cup", c:"Blackburn Rovers"},
{y:"1885-86", t:"FA Cup", c:"Blackburn Rovers"},
{y:"1886-87", t:"FA Cup", c:"Aston Villa"},
{y:"1887-88", t:"FA Cup", c:"West Bromwich Albion"},
{y:"1888-89", t:"FA Cup", c:"Preston North End"},
{y:"1889-90", t:"FA Cup", c:"Blackburn Rovers"},
{y:"1890-91", t:"FA Cup", c:"Blackburn Rovers"},
{y:"1891-92", t:"FA Cup", c:"Aston Villa"},
{y:"1892-93", t:"FA Cup", c:"Wolverhampton Wanderers"},
{y:"1893-94", t:"FA Cup", c:"Notts County"},
{y:"1894-95", t:"FA Cup", c:"Aston Villa"},
{y:"1895-96", t:"FA Cup", c:"The Wednesday"},
{y:"1896-97", t:"FA Cup", c:"Aston Villa"},
{y:"1897-98", t:"FA Cup", c:"Nottingham Forest"},
{y:"1898-99", t:"FA Cup", c:"Sheffield United"},
{y:"1899-00", t:"FA Cup", c:"Bury"},
{y:"1900-01", t:"FA Cup", c:"Tottenham Hotspur"},
{y:"1901-02", t:"FA Cup", c:"Sheffield United"},
{y:"1902-03", t:"FA Cup", c:"Bury"},
{y:"1903-04", t:"FA Cup", c:"Manchester City"},
{y:"1904-05", t:"FA Cup", c:"Aston Villa"},
{y:"1905-06", t:"FA Cup", c:"Everton"},
{y:"1906-07", t:"FA Cup", c:"The Wednesday"},
{y:"1907-08", t:"FA Cup", c:"Wolverhampton Wanderers"},
{y:"1908-09", t:"FA Cup", c:"Manchester United"},
{y:"1909-10", t:"FA Cup", c:"Newcastle United"},
{y:"1910-11", t:"FA Cup", c:"Bradford City"},
{y:"1911-12", t:"FA Cup", c:"Barnsley"},
{y:"1912-13", t:"FA Cup", c:"Aston Villa"},
{y:"1913-14", t:"FA Cup", c:"Burnley"},
{y:"1914-15", t:"FA Cup", c:"Sheffield United"},
{y:"1919-20", t:"FA Cup", c:"Aston Villa"},
{y:"1920-21", t:"FA Cup", c:"Tottenham Hotspur"},
{y:"1921-22", t:"FA Cup", c:"Huddersfield Town"},
{y:"1922-23", t:"FA Cup", c:"Bolton Wanderers"},
{y:"1923-24", t:"FA Cup", c:"Newcastle United"},
{y:"1924-25", t:"FA Cup", c:"Sheffield United"},
{y:"1925-26", t:"FA Cup", c:"Bolton Wanderers"},
{y:"1926-27", t:"FA Cup", c:"Cardiff City"},
{y:"1927-28", t:"FA Cup", c:"Blackburn Rovers"},
{y:"1928-29", t:"FA Cup", c:"Bolton Wanderers"},
{y:"1929-30", t:"FA Cup", c:"Arsenal"},
{y:"1930-31", t:"FA Cup", c:"West Bromwich Albion"},
{y:"1931-32", t:"FA Cup", c:"Newcastle United"},
{y:"1932-33", t:"FA Cup", c:"Everton"},
{y:"1933-34", t:"FA Cup", c:"Manchester City"},
{y:"1934-35", t:"FA Cup", c:"Sheffield Wednesday"},
{y:"1935-36", t:"FA Cup", c:"Arsenal"},
{y:"1936-37", t:"FA Cup", c:"Sunderland"},
{y:"1937-38", t:"FA Cup", c:"Preston North End"},
{y:"1938-39", t:"FA Cup", c:"Portsmouth"},
{y:"1945-46", t:"FA Cup", c:"Derby County"},
{y:"1946-47", t:"FA Cup", c:"Charlton Athletic"},
{y:"1947-48", t:"FA Cup", c:"Manchester United"},
{y:"1948-49", t:"FA Cup", c:"Wolverhampton Wanderers"},
{y:"1949-50", t:"FA Cup", c:"Arsenal"},
{y:"1950-51", t:"FA Cup", c:"Newcastle United"},
{y:"1951-52", t:"FA Cup", c:"Newcastle United"},
{y:"1952-53", t:"FA Cup", c:"Blackpool"},
{y:"1953-54", t:"FA Cup", c:"West Bromwich Albion"},
{y:"1954-55", t:"FA Cup", c:"Newcastle United"},
{y:"1955-56", t:"FA Cup", c:"Manchester City"},
{y:"1956-57", t:"FA Cup", c:"Aston Villa"},
{y:"1957-58", t:"FA Cup", c:"Bolton Wanderers"},
{y:"1958-59", t:"FA Cup", c:"Nottingham Forest"},
{y:"1959-60", t:"FA Cup", c:"Wolverhampton Wanderers"},
{y:"1960-61", t:"FA Cup", c:"Tottenham Hotspur"},
{y:"1961-62", t:"FA Cup", c:"Tottenham Hotspur"},
{y:"1962-63", t:"FA Cup", c:"Manchester United"},
{y:"1963-64", t:"FA Cup", c:"West Ham United"},
{y:"1964-65", t:"FA Cup", c:"Liverpool"},
{y:"1965-66", t:"FA Cup", c:"Everton"},
{y:"1966-67", t:"FA Cup", c:"Tottenham Hotspur"},
{y:"1967-68", t:"FA Cup", c:"West Bromwich Albion"},
{y:"1968-69", t:"FA Cup", c:"Manchester City"},
{y:"1969-70", t:"FA Cup", c:"Chelsea"},
{y:"1970-71", t:"FA Cup", c:"Arsenal"},
{y:"1971-72", t:"FA Cup", c:"Leeds United"},
{y:"1972-73", t:"FA Cup", c:"Sunderland"},
{y:"1973-74", t:"FA Cup", c:"Liverpool"},
{y:"1974-75", t:"FA Cup", c:"West Ham United"},
{y:"1975-76", t:"FA Cup", c:"Southampton"},
{y:"1976-77", t:"FA Cup", c:"Manchester United"},
{y:"1977-78", t:"FA Cup", c:"Ipswich Town"},
{y:"1978-79", t:"FA Cup", c:"Arsenal"},
{y:"1979-80", t:"FA Cup", c:"West Ham United"},
{y:"1980-81", t:"FA Cup", c:"Tottenham Hotspur"},
{y:"1981-82", t:"FA Cup", c:"Tottenham Hotspur"},
{y:"1982-83", t:"FA Cup", c:"Manchester United"},
{y:"1983-84", t:"FA Cup", c:"Everton"},
{y:"1984-85", t:"FA Cup", c:"Manchester United"},
{y:"1985-86", t:"FA Cup", c:"Liverpool"},
{y:"1986-87", t:"FA Cup", c:"Coventry City"},
{y:"1987-88", t:"FA Cup", c:"Wimbledon"},
{y:"1988-89", t:"FA Cup", c:"Liverpool"},

// EFL League Cup (1960 - 1989)
{y:"1960-61", t:"EFL League Cup", c:"Aston Villa"},
{y:"1961-62", t:"EFL League Cup", c:"Norwich City"},
{y:"1962-63", t:"EFL League Cup", c:"Birmingham City"},
{y:"1963-64", t:"EFL League Cup", c:"Leicester City"},
{y:"1964-65", t:"EFL League Cup", c:"Chelsea"},
{y:"1965-66", t:"EFL League Cup", c:"West Bromwich Albion"},
{y:"1966-67", t:"EFL League Cup", c:"Queens Park Rangers"},
{y:"1967-68", t:"EFL League Cup", c:"Leeds United"},
{y:"1968-69", t:"EFL League Cup", c:"Swindon Town"},
{y:"1969-70", t:"EFL League Cup", c:"Manchester City"},
{y:"1970-71", t:"EFL League Cup", c:"Tottenham Hotspur"},
{y:"1971-72", t:"EFL League Cup", c:"Stoke City"},
{y:"1972-73", t:"EFL League Cup", c:"Tottenham Hotspur"},
{y:"1973-74", t:"EFL League Cup", c:"Wolverhampton Wanderers"},
{y:"1974-75", t:"EFL League Cup", c:"Aston Villa"},
{y:"1975-76", t:"EFL League Cup", c:"Manchester City"},
{y:"1976-77", t:"EFL League Cup", c:"Aston Villa"},
{y:"1977-78", t:"EFL League Cup", c:"Nottingham Forest"},
{y:"1978-79", t:"EFL League Cup", c:"Nottingham Forest"},
{y:"1979-80", t:"EFL League Cup", c:"Wolverhampton Wanderers"},
{y:"1980-81", t:"EFL League Cup", c:"Liverpool"},
{y:"1981-82", t:"EFL League Cup", c:"Liverpool"},
{y:"1982-83", t:"EFL League Cup", c:"Liverpool"},
{y:"1983-84", t:"EFL League Cup", c:"Liverpool"},
{y:"1984-85", t:"EFL League Cup", c:"Norwich City"},
{y:"1985-86", t:"EFL League Cup", c:"Oxford United"},
{y:"1986-87", t:"EFL League Cup", c:"Arsenal"},
{y:"1987-88", t:"EFL League Cup", c:"Luton Town"},
{y:"1988-89", t:"EFL League Cup", c:"Nottingham Forest"},

// Community Shield (1908 - 1989)
{y:"1908", t:"FA Community Shield", c:"Manchester United"},
{y:"1909", t:"FA Community Shield", c:"Newcastle United"},
{y:"1910", t:"FA Community Shield", c:"Brighton"}, // Brighton & Hove Albion
{y:"1911", t:"FA Community Shield", c:"Manchester United"},
{y:"1912", t:"FA Community Shield", c:"Blackburn Rovers"},
{y:"1913", t:"FA Community Shield", c:"English Professionals"},
{y:"1920", t:"FA Community Shield", c:"West Bromwich Albion"},
{y:"1921", t:"FA Community Shield", c:"Tottenham Hotspur"},
{y:"1922", t:"FA Community Shield", c:"Huddersfield Town"},
{y:"1923", t:"FA Community Shield", c:"English Professionals"},
{y:"1924", t:"FA Community Shield", c:"English Professionals"},
{y:"1925", t:"FA Community Shield", c:"English Amateurs"},
{y:"1926", t:"FA Community Shield", c:"English Amateurs"},
{y:"1927", t:"FA Community Shield", c:"Cardiff City"},
{y:"1928", t:"FA Community Shield", c:"Everton"},
{y:"1929", t:"FA Community Shield", c:"English Professionals"},
{y:"1930", t:"FA Community Shield", c:"Arsenal"},
{y:"1931", t:"FA Community Shield", c:"Arsenal"},
{y:"1932", t:"FA Community Shield", c:"Everton"},
{y:"1933", t:"FA Community Shield", c:"Arsenal"},
{y:"1934", t:"FA Community Shield", c:"Arsenal"},
{y:"1935", t:"FA Community Shield", c:"Sheffield Wednesday"},
{y:"1936", t:"FA Community Shield", c:"Sunderland"},
{y:"1937", t:"FA Community Shield", c:"Manchester City"},
{y:"1938", t:"FA Community Shield", c:"Arsenal"},
{y:"1948", t:"FA Community Shield", c:"Arsenal"},
{y:"1949", t:"FA Community Shield", c:"Portsmouth / Wolverhampton Wanderers"},
{y:"1950", t:"FA Community Shield", c:"England World Cup XI"},
{y:"1951", t:"FA Community Shield", c:"Tottenham Hotspur"},
{y:"1952", t:"FA Community Shield", c:"Manchester United"},
{y:"1953", t:"FA Community Shield", c:"Arsenal"},
{y:"1954", t:"FA Community Shield", c:"Wolverhampton Wanderers / West Bromwich Albion"},
{y:"1955", t:"FA Community Shield", c:"Chelsea"},
{y:"1956", t:"FA Community Shield", c:"Manchester United"},
{y:"1957", t:"FA Community Shield", c:"Manchester United"},
{y:"1958", t:"FA Community Shield", c:"Bolton Wanderers"},
{y:"1959", t:"FA Community Shield", c:"Wolverhampton Wanderers"},
{y:"1960", t:"FA Community Shield", c:"Burnley / Wolverhampton Wanderers"},
{y:"1961", t:"FA Community Shield", c:"Tottenham Hotspur"},
{y:"1962", t:"FA Community Shield", c:"Tottenham Hotspur"},
{y:"1963", t:"FA Community Shield", c:"Everton"},
{y:"1964", t:"FA Community Shield", c:"Liverpool / West Ham United"},
{y:"1965", t:"FA Community Shield", c:"Manchester United / Liverpool"},
{y:"1966", t:"FA Community Shield", c:"Liverpool"},
{y:"1967", t:"FA Community Shield", c:"Manchester United / Tottenham Hotspur"},
{y:"1968", t:"FA Community Shield", c:"Manchester City"},
{y:"1969", t:"FA Community Shield", c:"Leeds United"},
{y:"1970", t:"FA Community Shield", c:"Everton"},
{y:"1971", t:"FA Community Shield", c:"Leicester City"},
{y:"1972", t:"FA Community Shield", c:"Manchester City"},
{y:"1973", t:"FA Community Shield", c:"Burnley"},
{y:"1974", t:"FA Community Shield", c:"Liverpool"},
{y:"1975", t:"FA Community Shield", c:"Derby County"},
{y:"1976", t:"FA Community Shield", c:"Liverpool"},
{y:"1977", t:"FA Community Shield", c:"Manchester United / Liverpool"},
{y:"1978", t:"FA Community Shield", c:"Nottingham Forest"},
{y:"1979", t:"FA Community Shield", c:"Liverpool"},
{y:"1980", t:"FA Community Shield", c:"Liverpool"},
{y:"1981", t:"FA Community Shield", c:"Aston Villa / Tottenham Hotspur"},
{y:"1982", t:"FA Community Shield", c:"Liverpool"},
{y:"1983", t:"FA Community Shield", c:"Manchester United"},
{y:"1984", t:"FA Community Shield", c:"Everton"},
{y:"1985", t:"FA Community Shield", c:"Everton"},
{y:"1986", t:"FA Community Shield", c:"Everton / Liverpool"},
{y:"1987", t:"FA Community Shield", c:"Everton"},
{y:"1988", t:"FA Community Shield", c:"Liverpool"},
{y:"1989", t:"FA Community Shield", c:"Liverpool"}
];

const file = 'app/src/data/ligas/inglaterra_temporadas.json';
let db = JSON.parse(fs.readFileSync(file, 'utf8'));

let before = db.length;
for (let item of dataRaw) {
   let suffix = item.t === 'FA Cup' ? '-facup' : item.t === 'EFL League Cup' ? '-leaguecup' : '-shield';
   let idYear = item.y.split('-')[0];
   let id = idYear + suffix;
   
   if(!db.find(x => x.id === id)) {
      db.push({
         id: id,
         anio: item.y,
         torneo: item.t,
         campeon: item.c
      });
   }
}

// Sort database chronologically by base year
db.sort((a,b) => {
   let baseA = parseInt(a.anio.split('-')[0]);
   let baseB = parseInt(b.anio.split('-')[0]);
   if(baseA === baseB) {
      return a.torneo.localeCompare(b.torneo);
   }
   return baseA - baseB;
});

fs.writeFileSync(file, JSON.stringify(db, null, 2));

console.log('Total injected: ' + (db.length - before));
console.log('New total size: ' + db.length);
