const fs = require('fs');
const path = require('path');

const campeones = [
  { anio: "1959", campeon: "Bahia", id_suf: "-taca-brasil" },
  { anio: "1960", campeon: "Palmeiras", id_suf: "-taca-brasil" },
  { anio: "1961", campeon: "Santos", id_suf: "-taca-brasil" },
  { anio: "1962", campeon: "Santos", id_suf: "-taca-brasil" },
  { anio: "1963", campeon: "Santos", id_suf: "-taca-brasil" },
  { anio: "1964", campeon: "Santos", id_suf: "-taca-brasil" },
  { anio: "1965", campeon: "Santos", id_suf: "-taca-brasil" },
  { anio: "1966", campeon: "Cruzeiro", id_suf: "-taca-brasil" },
  { anio: "1967", campeon: "Palmeiras", id_suf: "-taca-brasil" },
  { anio: "1967", campeon: "Palmeiras", id_suf: "-robertao" },
  { anio: "1968", campeon: "Botafogo", id_suf: "-taca-brasil" },
  { anio: "1968", campeon: "Santos", id_suf: "-robertao" },
  { anio: "1969", campeon: "Palmeiras", id_suf: "-robertao" },
  { anio: "1970", campeon: "Fluminense", id_suf: "-robertao" },
  { anio: "1971", campeon: "Atlético Mineiro", id_suf: "-serie-a" },
  { anio: "1972", campeon: "Palmeiras", id_suf: "-serie-a" },
  { anio: "1973", campeon: "Palmeiras", id_suf: "-serie-a" },
  { anio: "1974", campeon: "Vasco da Gama", id_suf: "-serie-a" },
  { anio: "1975", campeon: "Internacional", id_suf: "-serie-a" },
  { anio: "1976", campeon: "Internacional", id_suf: "-serie-a" },
  { anio: "1977", campeon: "São Paulo", id_suf: "-serie-a" },
  { anio: "1978", campeon: "Guarani", id_suf: "-serie-a" },
  { anio: "1979", campeon: "Internacional", id_suf: "-serie-a" },
  { anio: "1980", campeon: "Flamengo", id_suf: "-serie-a" },
  { anio: "1981", campeon: "Grêmio", id_suf: "-serie-a" },
  { anio: "1982", campeon: "Flamengo", id_suf: "-serie-a" },
  { anio: "1983", campeon: "Flamengo", id_suf: "-serie-a" },
  { anio: "1984", campeon: "Fluminense", id_suf: "-serie-a" },
  { anio: "1985", campeon: "Coritiba", id_suf: "-serie-a" },
  { anio: "1986", campeon: "São Paulo", id_suf: "-serie-a" },
  { anio: "1987", campeon: "Sport Recife", id_suf: "-serie-a" },
  { anio: "1988", campeon: "Bahia", id_suf: "-serie-a" },
  { anio: "1989", campeon: "Vasco da Gama", id_suf: "-serie-a" },
  { anio: "1990", campeon: "Corinthians", id_suf: "-serie-a" },
  { anio: "1991", campeon: "São Paulo", id_suf: "-serie-a" },
  { anio: "1992", campeon: "Flamengo", id_suf: "-serie-a" },
  { anio: "1993", campeon: "Palmeiras", id_suf: "-serie-a" },
  { anio: "1994", campeon: "Palmeiras", id_suf: "-serie-a" },
  { anio: "1995", campeon: "Botafogo", id_suf: "-serie-a" },
  { anio: "1996", campeon: "Grêmio", id_suf: "-serie-a" },
  { anio: "1997", campeon: "Vasco da Gama", id_suf: "-serie-a" },
  { anio: "1998", campeon: "Corinthians", id_suf: "-serie-a" },
  { anio: "1999", campeon: "Corinthians", id_suf: "-serie-a" },
  { anio: "2000", campeon: "Vasco da Gama", id_suf: "-serie-a" },
  { anio: "2001", campeon: "Athletico Paranaense", id_suf: "-serie-a" },
  { anio: "2002", campeon: "Santos", id_suf: "-serie-a" },
  { anio: "2003", campeon: "Cruzeiro", id_suf: "-serie-a" },
  { anio: "2004", campeon: "Santos", id_suf: "-serie-a" },
  { anio: "2005", campeon: "Corinthians", id_suf: "-serie-a" },
  { anio: "2006", campeon: "São Paulo", id_suf: "-serie-a" },
  { anio: "2007", campeon: "São Paulo", id_suf: "-serie-a" },
  { anio: "2008", campeon: "São Paulo", id_suf: "-serie-a" },
  { anio: "2009", campeon: "Flamengo", id_suf: "-serie-a" },
  { anio: "2010", campeon: "Fluminense", id_suf: "-serie-a" },
  { anio: "2011", campeon: "Corinthians", id_suf: "-serie-a" },
  { anio: "2012", campeon: "Fluminense", id_suf: "-serie-a" },
  { anio: "2013", campeon: "Cruzeiro", id_suf: "-serie-a" },
  { anio: "2014", campeon: "Cruzeiro", id_suf: "-serie-a" },
  { anio: "2015", campeon: "Corinthians", id_suf: "-serie-a" },
  { anio: "2016", campeon: "Palmeiras", id_suf: "-serie-a" },
  { anio: "2017", campeon: "Corinthians", id_suf: "-serie-a" },
  { anio: "2018", campeon: "Palmeiras", id_suf: "-serie-a" },
  { anio: "2019", campeon: "Flamengo", id_suf: "-serie-a" },
  { anio: "2020", campeon: "Flamengo", id_suf: "-serie-a" },
  { anio: "2021", campeon: "Atlético Mineiro", id_suf: "-serie-a" },
  { anio: "2022", campeon: "Palmeiras", id_suf: "-serie-a" },
  { anio: "2023", campeon: "Palmeiras", id_suf: "-serie-a" },
  { anio: "2024", campeon: "Botafogo", id_suf: "-serie-a" },
  { anio: "2025", campeon: "Flamengo", id_suf: "-serie-a" }
];

const arr = campeones.map(c => ({
  id: c.anio + c.id_suf,
  anio: c.anio,
  torneo: "Série A",
  campeon: c.campeon,
  tabla_posiciones: []
}));

const filePath = path.join(__dirname, 'app', 'src', 'data', 'ligas', 'brasil_temporadas.json');
fs.writeFileSync(filePath, JSON.stringify(arr, null, 2));
console.log('Brasil temporadas creadas exitosamente.');
