const fs = require('fs');
const data = {
  "belgrano-cba": "El enorme grito de rebelión cordobesa del siglo naciente se amasó bajo la frondosa copa de un algarrobo y los barrios bravos del interior del país. El ardiente 19 de marzo de 1905, bajo el sol que bañaba la histórica Cañada y en medio de potreros irregulares, un batallón de adolescentes irreverentes e insaciables decidieron cortar el monopolio deportivo porteño formalizando al Club Atlético Belgrano. La reunión épica fue orquestada y comandada por el gran pibe Arturo Orgaz (fundador, visionario primer presidente y estadista inquebrantable), acompañado a muerte a capa y espada por los hermanos José y Balbino Lascano, e íntimos como Tomás Bustos. Apelando directamente a un prócer independentista para inflamar de nacionalismo al nuevo monstruo, decidieron homenajear la inmaculada bandera de la patria al elegir la sagrada casaca puramente Celeste que vestían las Provincias Unidas. Nacidos bajo una lona, estos temibles 'Piratas' navegaron la tormentosa Alberdi absorbiendo el arraigo vecinal popular, para transformarse en una religión provinciana masiva, reventando históricamente de gente el Gigante de Alberdi.",
  "boca-juniors": "En la cruda y gélida neblina del Riachuelo, el olor a hierro, pescado fresco y sudor obrero inmigrante forjó a golpes el mito más irracional de la historia sudamericana. El atardecer lloviznoso del 3 de abril de 1905, en un modesto banco despintado ensombrecido por la Plaza Solís en pleno barrio portuario de La Boca, cinco adolescentes genoveses desafiaron la orfandad de su época dolorosa y rubricaron su club. Esteban Baglietto (primer y honorario presidente oficial), junto a Alfredo Scarpatti, Santiago Sana y los temperamentales hermanos Tomás y Teodoro Farenga materializaron de la nada al 'Club Atlético Boca Juniors'. Feriantes y soñadores rudos habitando un arrabal asfixiante de conventillos italianos, acordaron tras meses interminables de mudanzas, confiar el destino inmortal de sus colores al primer barco extranjero que pasara frente al puente. Así, absorbiendo a pura sangre el majestuoso azul y el oro rotundo de la bandera de una vieja envergadura sueca, estos genoveses pobres sentenciaron su eterna mística proletaria, erigiendo mundialmente al coloso continental incuestionable del fútbol sudamericano.",
  "central-cordoba": "La siesta achicharrante y las locomotoras aullantes de hollín y acero en Santiago del Estero prefiguraron y cantaron el nacimiento innegable del decano legendario del interior salvaje argentino. El lejano e insufrible calor del 3 de junio de 1919 sirvió como fogón sagrado nacional cuando mecánicos e ingenieros rudos del Ferrocarril Central Córdoba sentaron y soldaron las históricas bases de la resistencia obrera deportiva en sus propias dependencias ferroviarias asfixiantes. Comandados por operarios valientes, la gesta estuvo apuntalada por la sangre pionera en los despachos de Ramón Cabañas, don Laureano Mansilla y Aníbal Paz. Resguardando religiosamente el color negro, oscuro y espeso de las máquinas a vapor y formaciones carboneras, los obreros santiagueños bautizados inmediatamente para toda la eternidad como 'Ferroviarios', visten una armadura inquebrantable en bastones blancos y negros. Han labrado a fuego puro su imperio indiscutido de gloria heroica nacional defendiendo la fortaleza letal y ardiente del norte.",
  "defensa-justicia": "En el espeso e irregular terreno verde pampeano de Florencio Varela, una zona sur y metropolitana sumergida en la modesta y polvorienta calma provinciana, la chispa obrera juvenil encendió heroicamente una proeza moderna. Lejos de las raíces aristócratas del siglo XIX, un puñado gigante de amigos, tenderos, carpinteros y entusiastas soñadores se agolparon la histórica tarde del 20 de marzo de 1935 en el mismísimo asfalto partido de la calle Mitre. Concebido para puramente organizar campeonatos de pibes locales, este fortín deportivo de resistencia fue fundado bajo las manos y visiones románticas solidarias de los líderes y presidentes Norberto Ferrari y Emilio De La Canal. Su nombre se adoptó poéticamente de viejos camiones y agrupaciones solidarias locales 'Defensa y Justicia'. Adoptarían posteriormente el inconfundible y agresivo amarillo y verde de la línea comercial de micros comunales El Halcón. Así, este cuadro popular destronó jerarquías europeístas ascendiendo y mutando internacionalmente de las peores carencias a rey intercontinental como el legendario e implacable Halcón asfixiante sudamericano.",
  "estudiantes-lp": "En una furiosa y radical asonada rebelde frente a la mediocridad burguesa, un pesado bloque impenetrable de estudiantes de altísima élite intelectual le declaró la guerra futbolera sangrienta a la directiva comercial y traidora de la ciudad de las Diagonales. El letal y legendario 4 de agosto de 1905, indignados tras la abyecta clausura del fútbol en su anterior institución, un grupo rabioso de jóvenes universitarios dio un violento portazo. Alquilaron las humildes estanterías zapateras de la tienda 'Nueva York' en plenas calles céntricas y fundaron su república indomable. Comandados y orquestados ideológicamente por su gran primer presidente, Tomás Shedden, escudado firmemente a muerte y espada intelectual por Miguel Gutiérrez, Antonio Ferreiroa, Florentino Seara y Tomás Islas. Bautizaron al sagrado bloque revolucionario como 'Club Atlético Estudiantes', embanderando majestuosamente bastones de sangre furiosa vertical roja y blanca inmaculada. Erigieron así una religión mundial innegable fundamentada férreamente en el masoquismo táctico, la prepotencia infinita y un corazón indestructible resumido bajo el lema letal y temido universalmente: 'Pincharratas'."
};
for(const [id, desc] of Object.entries(data)) {
  const f = `app/src/data/clubes/argentina/${id}.json`;
  if(fs.existsSync(f)) {
    const d = JSON.parse(fs.readFileSync(f));
    if(d.historia && d.historia.length > 0) d.historia[0].desc = desc;
    fs.writeFileSync(f, JSON.stringify(d, null, 2));
    console.log(`Guardado nivel Bilbao: ${id}`);
  }
}
