const fs = require('fs');
const path = require('path');

const file1995 = path.join(__dirname, 'app', 'src', 'data', 'copas', 'champions', '1995.json');
const data1995 = JSON.parse(fs.readFileSync(file1995, 'utf-8'));

const rigorSquads = {
  "barcelona": [
    { no: 1, pos: "Portero", name: "Carles Busquets", flag: "es" },
    { no: 13, pos: "Portero", name: "Jesús Angoy", flag: "es" },
    { no: 2, pos: "Defensa", name: "Albert Ferrer", flag: "es" },
    { no: 3, pos: "Defensa", name: "Abelardo Fernández", flag: "es" },
    { no: 4, pos: "Defensa", name: "Ronald Koeman", flag: "nl" },
    { no: 5, pos: "Defensa", name: "Miguel Ángel Nadal", flag: "es" },
    { no: 12, pos: "Defensa", name: "Sergi Barjuan", flag: "es" },
    { no: 22, pos: "Defensa", name: "Xabier Eskurza", flag: "es" },
    { no: 17, pos: "Defensa", name: "Francisco Javier Sánchez Jara", flag: "es" },
    { no: 6, pos: "Centrocampista", name: "José Mari Bakero", flag: "es" },
    { no: 9, pos: "Centrocampista", name: "Guillermo Amor", flag: "es" },
    { no: 14, pos: "Centrocampista", name: "Jordi Cruyff", flag: "nl" },
    { no: 15, pos: "Centrocampista", name: "Eusebio Sacristán", flag: "es" },
    { no: 16, pos: "Centrocampista", name: "Iván Iglesias", flag: "es" },
    { no: 20, pos: "Centrocampista", name: "Pep Guardiola", flag: "es" },
    { no: 21, pos: "Centrocampista", name: "Gheorghe Hagi", flag: "ro" },
    { no: 8, pos: "Delantero", name: "Hristo Stoichkov", flag: "bg" },
    { no: 10, pos: "Delantero", name: "Romário", flag: "br" },
    { no: 11, pos: "Delantero", name: "Txiki Begiristain", flag: "es" },
    { no: 19, pos: "Delantero", name: "Igor Korneev", flag: "ru" }
  ],
  "manchester-united": [
    { no: 1, pos: "Portero", name: "Peter Schmeichel", flag: "dk" },
    { no: 13, pos: "Portero", name: "Gary Walsh", flag: "gb-eng" },
    { no: 2, pos: "Defensa", name: "Paul Parker", flag: "gb-eng" },
    { no: 3, pos: "Defensa", name: "Denis Irwin", flag: "ie" },
    { no: 4, pos: "Defensa", name: "Steve Bruce", flag: "gb-eng" },
    { no: 6, pos: "Defensa", name: "Gary Pallister", flag: "gb-eng" },
    { no: 12, pos: "Defensa", name: "David May", flag: "gb-eng" },
    { no: 27, pos: "Defensa", name: "Gary Neville", flag: "gb-eng" },
    { no: 5, pos: "Centrocampista", name: "Lee Sharpe", flag: "gb-eng" },
    { no: 8, pos: "Centrocampista", name: "Paul Ince", flag: "gb-eng" },
    { no: 11, pos: "Centrocampista", name: "Ryan Giggs", flag: "gb-wls" },
    { no: 14, pos: "Centrocampista", name: "Andrei Kanchelskis", flag: "ru" },
    { no: 16, pos: "Centrocampista", name: "Roy Keane", flag: "ie" },
    { no: 19, pos: "Centrocampista", name: "Nicky Butt", flag: "gb-eng" },
    { no: 24, pos: "Centrocampista", name: "Paul Scholes", flag: "gb-eng" },
    { no: 28, pos: "Centrocampista", name: "David Beckham", flag: "gb-eng" },
    { no: 7, pos: "Delantero", name: "Eric Cantona", flag: "fr" },
    { no: 9, pos: "Delantero", name: "Brian McClair", flag: "gb-sct" },
    { no: 10, pos: "Delantero", name: "Mark Hughes", flag: "gb-wls" },
    { no: 25, pos: "Delantero", name: "Simon Davies", flag: "gb-wls" }
  ],
  "ifk_goteborg": [
    { no: 1, pos: "Portero", name: "Thomas Ravelli", flag: "se" },
    { no: 12, pos: "Portero", name: "Dick Last", flag: "se" },
    { no: 2, pos: "Defensa", name: "Pontus Kåmark", flag: "se" },
    { no: 3, pos: "Defensa", name: "Mikael Nilsson", flag: "se" },
    { no: 4, pos: "Defensa", name: "Joachim Björklund", flag: "se" },
    { no: 5, pos: "Defensa", name: "Magnus Johansson", flag: "se" },
    { no: 14, pos: "Defensa", name: "Jonas Olsson", flag: "se" },
    { no: 6, pos: "Centrocampista", name: "Stefan Rehn", flag: "se" },
    { no: 7, pos: "Centrocampista", name: "Peter Eriksson", flag: "se" },
    { no: 8, pos: "Centrocampista", name: "Magnus Erlingmark", flag: "se" },
    { no: 9, pos: "Centrocampista", name: "Jesper Blomqvist", flag: "se" },
    { no: 16, pos: "Centrocampista", name: "Stefan Landberg", flag: "se" },
    { no: 11, pos: "Delantero", name: "Mikael Martinsson", flag: "se" },
    { no: 15, pos: "Delantero", name: "Mats Lilienberg", flag: "se" },
    { no: 18, pos: "Delantero", name: "Stefan Lindqvist", flag: "se" }
  ],
  "spartak_moscow": [
    { no: 1, pos: "Portero", name: "Dmytro Tyapushkin", flag: "ua" },
    { no: 16, pos: "Portero", name: "Valeri Sarychev", flag: "ru" },
    { no: 2, pos: "Defensa", name: "Dmitri Khlestov", flag: "ru" },
    { no: 3, pos: "Defensa", name: "Yuriy Nikiforov", flag: "ru" },
    { no: 4, pos: "Defensa", name: "Viktor Onopko", flag: "ru" },
    { no: 5, pos: "Defensa", name: "Ramiz Mamedov", flag: "ru" },
    { no: 6, pos: "Defensa", name: "Vladislav Ternavsky", flag: "ru" },
    { no: 7, pos: "Centrocampista", name: "Valery Karpin", flag: "ru" },
    { no: 8, pos: "Centrocampista", name: "Ilya Tsymbalar", flag: "ru" },
    { no: 9, pos: "Centrocampista", name: "Andrei Piatnitski", flag: "ru" },
    { no: 10, pos: "Centrocampista", name: "Dmitri Alenichev", flag: "ru" },
    { no: 11, pos: "Centrocampista", name: "Andrei Tikhonov", flag: "ru" },
    { no: 12, pos: "Centrocampista", name: "Mukhsin Mukhamadiev", flag: "tj" },
    { no: 13, pos: "Centrocampista", name: "Egor Titov", flag: "ru" },
    { no: 14, pos: "Delantero", name: "Nikolai Pisarev", flag: "ru" },
    { no: 15, pos: "Delantero", name: "Valery Kechinov", flag: "ru" },
    { no: 18, pos: "Delantero", name: "Sergei Yuran", flag: "ru" }
  ],
  "dynamo_kyiv": [
    { no: 1, pos: "Portero", name: "Oleksandr Shovkovskyi", flag: "ua" },
    { no: 12, pos: "Portero", name: "Valeriy Vorobyov", flag: "ua" },
    { no: 2, pos: "Defensa", name: "Oleh Luzhnyi", flag: "ua" },
    { no: 3, pos: "Defensa", name: "Serhiy Shmatovalenko", flag: "ua" },
    { no: 4, pos: "Defensa", name: "Vladyslav Vashchuk", flag: "ua" },
    { no: 5, pos: "Defensa", name: "Andriy Khomyn", flag: "ua" },
    { no: 13, pos: "Defensa", name: "Serhiy Bezhenar", flag: "ua" },
    { no: 6, pos: "Centrocampista", name: "Serhiy Mizin", flag: "ua" },
    { no: 7, pos: "Centrocampista", name: "Yuriy Maksymov", flag: "ua" },
    { no: 8, pos: "Centrocampista", name: "Vitaliy Kosovskyi", flag: "ua" },
    { no: 9, pos: "Centrocampista", name: "Dmytro Topchiyev", flag: "ua" },
    { no: 10, pos: "Centrocampista", name: "Yuriy Kalitvintsev", flag: "ua" },
    { no: 11, pos: "Delantero", name: "Viktor Leonenko", flag: "ua" },
    { no: 14, pos: "Delantero", name: "Serhiy Rebrov", flag: "ua" },
    { no: 15, pos: "Delantero", name: "Andriy Shevchenko", flag: "ua" },
    { no: 16, pos: "Delantero", name: "Serhiy Konovalov", flag: "ua" }
  ],
  "galatasaray": [
    { no: 1, pos: "Portero", name: "Hayrettin Demirbaş", flag: "tr" },
    { no: 12, pos: "Portero", name: "Nezih Ali Boloğlu", flag: "tr" },
    { no: 2, pos: "Defensa", name: "Bülent Korkmaz", flag: "tr" },
    { no: 3, pos: "Defensa", name: "Hakan Ünsal", flag: "tr" },
    { no: 4, pos: "Defensa", name: "Mert Korkmaz", flag: "tr" },
    { no: 5, pos: "Defensa", name: "Feti Okuroğlu", flag: "tr" },
    { no: 16, pos: "Defensa", name: "Norman Mapeza", flag: "zw" },
    { no: 6, pos: "Centrocampista", name: "Tugay Kerimoğlu", flag: "tr" },
    { no: 7, pos: "Centrocampista", name: "Suat Kaya", flag: "tr" },
    { no: 8, pos: "Centrocampista", name: "Okan Buruk", flag: "tr" },
    { no: 9, pos: "Centrocampista", name: "Ergün Penbe", flag: "tr" },
    { no: 10, pos: "Centrocampista", name: "Hamza Hamzaoğlu", flag: "tr" },
    { no: 13, pos: "Centrocampista", name: "Ilyas Kahraman", flag: "tr" },
    { no: 11, pos: "Delantero", name: "Hakan Şükür", flag: "tr" },
    { no: 14, pos: "Delantero", name: "Arif Erdem", flag: "tr" },
    { no: 15, pos: "Delantero", name: "Kubilay Türkyilmaz", flag: "ch" },
    { no: 18, pos: "Delantero", name: "Saffet Sancaklı", flag: "tr" }
  ],
  "hajduk_split": [
    { no: 1, pos: "Portero", name: "Tonči Gabrić", flag: "hr" },
    { no: 12, pos: "Portero", name: "Sandro Tomić", flag: "hr" },
    { no: 2, pos: "Defensa", name: "Igor Štimac", flag: "hr" },
    { no: 3, pos: "Defensa", name: "Slaven Bilić", flag: "hr" },
    { no: 4, pos: "Defensa", name: "Darko Butorović", flag: "hr" },
    { no: 5, pos: "Defensa", name: "Mirsad Hibić", flag: "ba" },
    { no: 20, pos: "Defensa", name: "Stjepan Andrijašević", flag: "hr" },
    { no: 6, pos: "Centrocampista", name: "Aljoša Asanović", flag: "hr" },
    { no: 7, pos: "Centrocampista", name: "Milan Rapaić", flag: "hr" },
    { no: 8, pos: "Centrocampista", name: "Nenad Pralija", flag: "hr" },
    { no: 10, pos: "Centrocampista", name: "Goran Vučević", flag: "hr" },
    { no: 14, pos: "Centrocampista", name: "Zoran Vulić", flag: "hr" },
    { no: 9, pos: "Delantero", name: "Ivica Mornar", flag: "hr" },
    { no: 11, pos: "Delantero", name: "Tomislav Erceg", flag: "hr" },
    { no: 16, pos: "Delantero", name: "Jurica Vučko", flag: "hr" }
  ],
  "benfica": [
    { no: 1, pos: "Portero", name: "Michel Preud'homme", flag: "be" },
    { no: 12, pos: "Portero", name: "Neno", flag: "pt" },
    { no: 2, pos: "Defensa", name: "António Veloso", flag: "pt" },
    { no: 3, pos: "Defensa", name: "Hélder", flag: "pt" },
    { no: 4, pos: "Defensa", name: "Paulo Madeira", flag: "pt" },
    { no: 5, pos: "Defensa", name: "Dimas", flag: "pt" },
    { no: 13, pos: "Defensa", name: "Abel Xavier", flag: "pt" },
    { no: 14, pos: "Defensa", name: "William", flag: "br" },
    { no: 6, pos: "Centrocampista", name: "Vítor Paneira", flag: "pt" },
    { no: 7, pos: "Centrocampista", name: "José Tavares", flag: "pt" },
    { no: 8, pos: "Centrocampista", name: "João Pinto", flag: "pt" },
    { no: 10, pos: "Centrocampista", name: "Isaías", flag: "br" },
    { no: 16, pos: "Centrocampista", name: "Kenedy", flag: "pt" },
    { no: 20, pos: "Centrocampista", name: "Mario Stanić", flag: "hr" },
    { no: 9, pos: "Delantero", name: "Edgar", flag: "pt" },
    { no: 11, pos: "Delantero", name: "Edílson", flag: "br" },
    { no: 18, pos: "Delantero", name: "Claudio Caniggia", flag: "ar" }
  ],
  "steaua": [
    { no: 1, pos: "Portero", name: "Bogdan Stelea", flag: "ro" },
    { no: 12, pos: "Portero", name: "Dumitru Stângaciu", flag: "ro" },
    { no: 2, pos: "Defensa", name: "Anton Doboș", flag: "ro" },
    { no: 3, pos: "Defensa", name: "Daniel Prodan", flag: "ro" },
    { no: 4, pos: "Defensa", name: "Iulian Filipescu", flag: "ro" },
    { no: 5, pos: "Defensa", name: "Aurel Panait", flag: "ro" },
    { no: 14, pos: "Defensa", name: "Tiberiu Csik", flag: "ro" },
    { no: 6, pos: "Centrocampista", name: "Constantin Gâlcă", flag: "ro" },
    { no: 7, pos: "Centrocampista", name: "Basarab Panduru", flag: "ro" },
    { no: 8, pos: "Centrocampista", name: "Damian Militaru", flag: "ro" },
    { no: 10, pos: "Centrocampista", name: "Ilie Stan", flag: "ro" },
    { no: 15, pos: "Centrocampista", name: "Augustin Călin", flag: "ro" },
    { no: 9, pos: "Delantero", name: "Marius Lăcătuș", flag: "ro" },
    { no: 11, pos: "Delantero", name: "Adrian Ilie", flag: "ro" },
    { no: 16, pos: "Delantero", name: "Jean Vlădoiu", flag: "ro" },
    { no: 19, pos: "Delantero", name: "Laurențiu Roșu", flag: "ro" }
  ],
  "anderlecht": [
    { no: 1, pos: "Portero", name: "Filip De Wilde", flag: "be" },
    { no: 12, pos: "Portero", name: "Frédéric Herpoel", flag: "be" },
    { no: 2, pos: "Defensa", name: "Bertrand Crasson", flag: "be" },
    { no: 3, pos: "Defensa", name: "Graeme Rutjes", flag: "nl" },
    { no: 4, pos: "Defensa", name: "Olivier Suray", flag: "be" },
    { no: 5, pos: "Defensa", name: "Celestine Babayaro", flag: "ng" },
    { no: 14, pos: "Defensa", name: "Georges Grün", flag: "be" },
    { no: 6, pos: "Centrocampista", name: "Johan Walem", flag: "be" },
    { no: 7, pos: "Centrocampista", name: "Pär Zetterberg", flag: "se" },
    { no: 8, pos: "Centrocampista", name: "Bruno Versavel", flag: "be" },
    { no: 10, pos: "Centrocampista", name: "Danny Boffin", flag: "be" },
    { no: 15, pos: "Centrocampista", name: "Charly Musonda", flag: "zm" },
    { no: 18, pos: "Centrocampista", name: "Philip Osondu", flag: "ng" },
    { no: 9, pos: "Delantero", name: "John Bosman", flag: "nl" },
    { no: 11, pos: "Delantero", name: "Yaw Preko", flag: "gh" },
    { no: 16, pos: "Delantero", name: "Johnny Miskovic", flag: "hr" }
  ],
  "salzburg": [
    { no: 1, pos: "Portero", name: "Otto Konrad", flag: "at" },
    { no: 21, pos: "Portero", name: "Herbert Ilsanker", flag: "at" },
    { no: 2, pos: "Defensa", name: "Leo Lainer", flag: "at" },
    { no: 3, pos: "Defensa", name: "Heribert Weber", flag: "at" },
    { no: 4, pos: "Defensa", name: "Thomas Winklhofer", flag: "at" },
    { no: 5, pos: "Defensa", name: "Christian Fürstaller", flag: "at" },
    { no: 14, pos: "Defensa", name: "Michael Hatz", flag: "at" },
    { no: 6, pos: "Centrocampista", name: "Franz Aigner", flag: "at" },
    { no: 7, pos: "Centrocampista", name: "Martin Amerhauser", flag: "at" },
    { no: 8, pos: "Centrocampista", name: "Peter Artner", flag: "at" },
    { no: 10, pos: "Centrocampista", name: "Wolfgang Feiersinger", flag: "at" },
    { no: 12, pos: "Centrocampista", name: "Adi Hütter", flag: "at" },
    { no: 17, pos: "Centrocampista", name: "Hermann Stadler", flag: "at" },
    { no: 9, pos: "Delantero", name: "Heimo Pfeifenberger", flag: "at" },
    { no: 11, pos: "Delantero", name: "Ralph Hasenhüttl", flag: "at" },
    { no: 16, pos: "Delantero", name: "Nikola Jurčević", flag: "hr" },
    { no: 18, pos: "Delantero", name: "Tomislav Kocijan", flag: "at" }
  ],
  "aek": [
    { no: 1, pos: "Portero", name: "Ilias Atmatsidis", flag: "gr" },
    { no: 15, pos: "Portero", name: "Vassilis Karagiannis", flag: "gr" },
    { no: 2, pos: "Defensa", name: "Michalis Kasapis", flag: "gr" },
    { no: 3, pos: "Defensa", name: "Vaios Karagiannis", flag: "gr" },
    { no: 4, pos: "Defensa", name: "Stelios Manolas", flag: "gr" },
    { no: 5, pos: "Defensa", name: "Refik Šabanadžović", flag: "ba" },
    { no: 13, pos: "Defensa", name: "Georgios Koutoulas", flag: "gr" },
    { no: 6, pos: "Centrocampista", name: "Vasilios Tsiartas", flag: "gr" },
    { no: 7, pos: "Centrocampista", name: "Temur Ketsbaia", flag: "ge" },
    { no: 8, pos: "Centrocampista", name: "Toni Savevski", flag: "mk" },
    { no: 10, pos: "Centrocampista", name: "Michalis Vlachos", flag: "gr" },
    { no: 12, pos: "Centrocampista", name: "Christos Kostis", flag: "gr" },
    { no: 14, pos: "Centrocampista", name: "Georgios Ketsbaia", flag: "ge" },
    { no: 9, pos: "Delantero", name: "Dimitrios Saravakos", flag: "gr" },
    { no: 11, pos: "Delantero", name: "Harry Kópis", flag: "gr" },
    { no: 16, pos: "Delantero", name: "Alexandros Alexandris", flag: "gr" }
  ]
};

data1995.participants.forEach(team => {
  if (rigorSquads[team.id]) {
    team.squad = rigorSquads[team.id];
  }
});

fs.writeFileSync(file1995, JSON.stringify(data1995, null, 2), 'utf-8');
console.log("¡Plantillas rigurosas inyectadas con éxito en 1995.json!");
