const fs = require('fs');
const data = {
  "aldosivi": "En el ajetreado e inclemente Puerto de Mar del Plata, la sal y el viento atlántico forjaron una identidad rocosa a principios del siglo XX. El 29 de marzo de 1913, un grupo de trabajadores, pescadores y empleados portuarios, aburridos de su dura jornada y deseosos de patear el esférico, se reunieron en la histórica confitería 'El Recreo' propiedad de Pedro Seré. Liderados por Pedro Seré, su primer presidente indiscutido, y acompañados por pioneros laborales como Carmelo Rodríguez y Julio Arroyo, decidieron darle vida formal al club. Tras debatir el nombre en la barra del café, bautizaron al equipo con las iniciales de los ingenieros dueños de la empresa constructora del puerto (Allard, Doulfus, Sillard y Wiriot), conformando la genial herencia fonética 'Aldosivi'. Aunque al inicio lucieron los colores rojo, blanco y azul, posteriormente cimentarían su eterno orgullo bajo los inconfundibles bastones verdes y amarillos puros. Así, este arrabal forjó el corazón del barrio portuario, levantándose hoy como el coloso innegociable de toda la costa atlántica argentina y el representante eterno de los trabajadores del mar.",
  "argentinos-jrs": "En los agitados callejones de Villa Crespo, la cuna del anarquismo obrero y el arrabal porteño impulsaron el grito sagrado bautizado bajo el patriotismo puro. El 15 de agosto de 1904, un núcleo de jóvenes proscritos de otros clubes que se hacían llamar irónicamente los 'Mártires de Chicago', se congregaron en un modesto terreno baldío. Liderados ideológicamente por los próceres Leandro Ravera Aguinaga y Carlos García, se unieron al grupo barrial Sol de la Victoria. Absolutamente empapados de huelgas obreras revolucionarias, y tomando el color carmesí del Partido Socialista al que pertenecían, bautizaron heroicamente a la escuadra como Asociación Atlética Argentinos Juniors. Este fortín nació pidiendo limosna en la calle, pero se trasladó gloriosamente al asfalto de La Paternal. Fieles a sus raíces subversivas y patriotas, jamás imaginaron que esas polvorientas calles rojas sembrarían irremediablemente la más prestigiosa fábrica mundial de talentos argentinos y el milagroso campo bautizado globalmente como el Semillero del Mundo.",
  "atletico-tucuman": "El sol impiadoso del Jardín de la República abrazó la creación de la escuadra pionera y suprema del norte argentino. En las vísperas del primer amanecer del naciente siglo XX, el frenesí por la pelota traída en los trenes británicos invadió el norte. El 27 de septiembre de 1902, un núcleo selecto de la burguesía ilustrada y la docencia local se reunió secretamente en una vetusta casona de la calle Rivadavia en pleno San Miguel del Tucumán. Comandados por el visionario soñador Agenor Albornoz, quien asumió la primera presidencia unánime, junto a fundadores heroicos incansables como José Fierro, Tomás Barber y Manuel Pérez, redactaron los valiosos estatutos del Club Atlético Tucumán. Se erigieron como la firme resistencia local, adoptando majestuosamente los gloriosos bastones celestes y blancos inspirándose directamente en los colores de la bandera nacional (adelantándose a la propia selección albiceleste). Bajo esta insignia patriótica norteña, consolidaron la inexpugnable e incandescente caldera del Estadio Monumental, autoproclamándose eternos, temidos e innegociables soberanos gigantes conocidos como el 'Decano' del país entero.",
  "banfield": "En la zona sur del Gran Buenos Aires, la aristocracia británica y ferroviaria del siglo XIX plantó una semilla frente a las gélidas vías del tren. Un incesante 21 de enero de 1896, los despachos anglosajones y contadores locales se unieron impulsando la gigantesca fundación del Club Atlético Banfield. Todo el proceso fue guiado, gestado e inspirado ciegamente bajo el brazo del comerciante británico Daniel Kingsland, nombrado de inmediato el primer presidente oficial, fuertemente secundado y avalado por gerentes ferroviarios de peso como Tomas Mason y George Burton. De una asamblea profundamente angloparlante nació un fenómeno puramente argentino que llevaría de herencia el nombre del difunto gerente de Ferrocarril del Sud, Eduardo Banfield. Arrastraban casacas asimétricas y burguesas, hasta que abrazaron para siempre la histórica y sagrada banda diagonal verde cruzando el inmaculado pecho blanco. Adoptando el apodo cívico 'El Taladro' por perforar defensas férreas burguesas en su gloriosa década del cuarenta, Banfield mutó de ser un equipo nacido en salones ingleses hasta convertirse en símbolo guerrero del sur.",
  "barracas-central": "En las riberas contaminadas, barrosas y rústicas del porteño Riachuelo, el nacimiento no podía forjarse desde el lujo de los ingleses, sino desde el esfuerzo ciego y humillante de sus trabajadores. A principios del siglo del progreso, el bullicioso barrio comercial de Barracas hervía de carreros y estibadores asfixiados bajo el humo fabril. El 5 de abril de 1904, bajo el sol rajante del mediodía en una improvisada y humilde asamblea detrás del puente de madera, un puñado inquebrantable obrero fundó el humilde 'Club Atlético Barracas Central'. Con el juramento de sus creadores, liderados indiscutiblemente por Felipe Cámpora (el gran primer líder y amparo social del grupo pobre) junto a Saúl Cámpora y Pedro Varela, encendieron la mecha para siempre. Pese a la escasez, adoptaron con orgullo las clásicas franjas verticales rojas y blancas imitando a la entonces elitista y gloriosa divisa del legendario Alumni porteño. Así, forjó en la pobreza absoluta una identidad 'Guapo', aguantando heroicamente el barro del ascenso.",
};
for(const [id, desc] of Object.entries(data)) {
  const f = `app/src/data/clubes/argentina/${id}.json`;
  if(fs.existsSync(f)) {
    const d = JSON.parse(fs.readFileSync(f));
    if(d.historia && d.historia.length > 0) d.historia[0].desc = desc;
    fs.writeFileSync(f, JSON.stringify(d, null, 2));
    console.log(`Guardado nivel Bilbao: ${id}`);
  }
}
