const fs = require('fs');
const path = require('path');

const FILE_PATH = path.join(__dirname, 'app', 'src', 'data', 'ligas', 'alemania_temporadas.json');

const ligas = [
  { anio: "1964", torneo: "Bundesliga", campeon: "1. FC Köln" },
  { anio: "1965", torneo: "Bundesliga", campeon: "Werder Bremen" },
  { anio: "1966", torneo: "Bundesliga", campeon: "1860 Munich" },
  { anio: "1967", torneo: "Bundesliga", campeon: "Eintracht Braunschweig" },
  { anio: "1968", torneo: "Bundesliga", campeon: "1. FC Nürnberg" },
  { anio: "1969", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1970", torneo: "Bundesliga", campeon: "Borussia Mönchengladbach" },
  { anio: "1971", torneo: "Bundesliga", campeon: "Borussia Mönchengladbach" },
  { anio: "1972", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1973", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1974", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1975", torneo: "Bundesliga", campeon: "Borussia Mönchengladbach" },
  { anio: "1976", torneo: "Bundesliga", campeon: "Borussia Mönchengladbach" },
  { anio: "1977", torneo: "Bundesliga", campeon: "Borussia Mönchengladbach" },
  { anio: "1978", torneo: "Bundesliga", campeon: "1. FC Köln" },
  { anio: "1979", torneo: "Bundesliga", campeon: "Hamburger SV" },
  { anio: "1980", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1981", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1982", torneo: "Bundesliga", campeon: "Hamburger SV" },
  { anio: "1983", torneo: "Bundesliga", campeon: "Hamburger SV" },
  { anio: "1984", torneo: "Bundesliga", campeon: "VfB Stuttgart" },
  { anio: "1985", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1986", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1987", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1988", torneo: "Bundesliga", campeon: "Werder Bremen" },
  { anio: "1989", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1990", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1991", torneo: "Bundesliga", campeon: "1. FC Kaiserslautern" },
  { anio: "1992", torneo: "Bundesliga", campeon: "VfB Stuttgart" },
  { anio: "1993", torneo: "Bundesliga", campeon: "Werder Bremen" },
  { anio: "1994", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1995", torneo: "Bundesliga", campeon: "Borussia Dortmund" },
  { anio: "1996", torneo: "Bundesliga", campeon: "Borussia Dortmund" },
  { anio: "1997", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "1998", torneo: "Bundesliga", campeon: "1. FC Kaiserslautern" },
  { anio: "1999", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2000", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2001", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2002", torneo: "Bundesliga", campeon: "Borussia Dortmund" },
  { anio: "2003", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2004", torneo: "Bundesliga", campeon: "Werder Bremen" },
  { anio: "2005", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2006", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2007", torneo: "Bundesliga", campeon: "VfB Stuttgart" },
  { anio: "2008", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2009", torneo: "Bundesliga", campeon: "VfL Wolfsburg" },
  { anio: "2010", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2011", torneo: "Bundesliga", campeon: "Borussia Dortmund" },
  { anio: "2012", torneo: "Bundesliga", campeon: "Borussia Dortmund" },
  { anio: "2013", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2014", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2015", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2016", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2017", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2018", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2019", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2020", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2021", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2022", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2023", torneo: "Bundesliga", campeon: "Bayern Munich" },
  { anio: "2024", torneo: "Bundesliga", campeon: "Bayer Leverkusen" }
];

const dfbPokal = [
  { anio: "1935", torneo: "DFB-Pokal", campeon: "1. FC Nürnberg" },
  { anio: "1936", torneo: "DFB-Pokal", campeon: "VfB Leipzig" },
  { anio: "1937", torneo: "DFB-Pokal", campeon: "Schalke 04" },
  { anio: "1938", torneo: "DFB-Pokal", campeon: "Rapid Viena" },
  { anio: "1939", torneo: "DFB-Pokal", campeon: "1. FC Nürnberg" },
  { anio: "1940", torneo: "DFB-Pokal", campeon: "Dresdner SC" },
  { anio: "1941", torneo: "DFB-Pokal", campeon: "Dresdner SC" },
  { anio: "1942", torneo: "DFB-Pokal", campeon: "1860 Munich" },
  { anio: "1943", torneo: "DFB-Pokal", campeon: "First Vienna" },
  { anio: "1953", torneo: "DFB-Pokal", campeon: "Rot-Weiss Essen" },
  { anio: "1954", torneo: "DFB-Pokal", campeon: "VfB Stuttgart" },
  { anio: "1955", torneo: "DFB-Pokal", campeon: "Karlsruher SC" },
  { anio: "1956", torneo: "DFB-Pokal", campeon: "Karlsruher SC" },
  { anio: "1957", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "1958", torneo: "DFB-Pokal", campeon: "VfB Stuttgart" },
  { anio: "1959", torneo: "DFB-Pokal", campeon: "Schwarz-Weiß Essen" },
  { anio: "1960", torneo: "DFB-Pokal", campeon: "Borussia Mönchengladbach" },
  { anio: "1961", torneo: "DFB-Pokal", campeon: "Werder Bremen" },
  { anio: "1962", torneo: "DFB-Pokal", campeon: "1. FC Nürnberg" },
  { anio: "1963", torneo: "DFB-Pokal", campeon: "Hamburger SV" },
  { anio: "1964", torneo: "DFB-Pokal", campeon: "1860 Munich" },
  { anio: "1965", torneo: "DFB-Pokal", campeon: "Borussia Dortmund" },
  { anio: "1966", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "1967", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "1968", torneo: "DFB-Pokal", campeon: "1. FC Köln" },
  { anio: "1969", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "1970", torneo: "DFB-Pokal", campeon: "Kickers Offenbach" },
  { anio: "1971", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "1972", torneo: "DFB-Pokal", campeon: "Schalke 04" },
  { anio: "1973", torneo: "DFB-Pokal", campeon: "Borussia Mönchengladbach" },
  { anio: "1974", torneo: "DFB-Pokal", campeon: "Eintracht Frankfurt" },
  { anio: "1975", torneo: "DFB-Pokal", campeon: "Eintracht Frankfurt" },
  { anio: "1976", torneo: "DFB-Pokal", campeon: "Hamburger SV" },
  { anio: "1977", torneo: "DFB-Pokal", campeon: "1. FC Köln" },
  { anio: "1978", torneo: "DFB-Pokal", campeon: "1. FC Köln" },
  { anio: "1979", torneo: "DFB-Pokal", campeon: "Fortuna Düsseldorf" },
  { anio: "1980", torneo: "DFB-Pokal", campeon: "Fortuna Düsseldorf" },
  { anio: "1981", torneo: "DFB-Pokal", campeon: "Eintracht Frankfurt" },
  { anio: "1982", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "1983", torneo: "DFB-Pokal", campeon: "1. FC Köln" },
  { anio: "1984", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "1985", torneo: "DFB-Pokal", campeon: "Bayer Uerdingen" },
  { anio: "1986", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "1987", torneo: "DFB-Pokal", campeon: "Hamburger SV" },
  { anio: "1988", torneo: "DFB-Pokal", campeon: "Eintracht Frankfurt" },
  { anio: "1989", torneo: "DFB-Pokal", campeon: "Borussia Dortmund" },
  { anio: "1990", torneo: "DFB-Pokal", campeon: "1. FC Kaiserslautern" },
  { anio: "1991", torneo: "DFB-Pokal", campeon: "Werder Bremen" },
  { anio: "1992", torneo: "DFB-Pokal", campeon: "Hannover 96" },
  { anio: "1993", torneo: "DFB-Pokal", campeon: "Bayer Leverkusen" },
  { anio: "1994", torneo: "DFB-Pokal", campeon: "Werder Bremen" },
  { anio: "1995", torneo: "DFB-Pokal", campeon: "Borussia Mönchengladbach" },
  { anio: "1996", torneo: "DFB-Pokal", campeon: "1. FC Kaiserslautern" },
  { anio: "1997", torneo: "DFB-Pokal", campeon: "VfB Stuttgart" },
  { anio: "1998", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "1999", torneo: "DFB-Pokal", campeon: "Werder Bremen" },
  { anio: "2000", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "2001", torneo: "DFB-Pokal", campeon: "Schalke 04" },
  { anio: "2002", torneo: "DFB-Pokal", campeon: "Schalke 04" },
  { anio: "2003", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "2004", torneo: "DFB-Pokal", campeon: "Werder Bremen" },
  { anio: "2005", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "2006", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "2007", torneo: "DFB-Pokal", campeon: "1. FC Nürnberg" },
  { anio: "2008", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "2009", torneo: "DFB-Pokal", campeon: "Werder Bremen" },
  { anio: "2010", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "2011", torneo: "DFB-Pokal", campeon: "Schalke 04" },
  { anio: "2012", torneo: "DFB-Pokal", campeon: "Borussia Dortmund" },
  { anio: "2013", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "2014", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "2015", torneo: "DFB-Pokal", campeon: "VfL Wolfsburg" },
  { anio: "2016", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "2017", torneo: "DFB-Pokal", campeon: "Borussia Dortmund" },
  { anio: "2018", torneo: "DFB-Pokal", campeon: "Eintracht Frankfurt" },
  { anio: "2019", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "2020", torneo: "DFB-Pokal", campeon: "Bayern Munich" },
  { anio: "2021", torneo: "DFB-Pokal", campeon: "Borussia Dortmund" },
  { anio: "2022", torneo: "DFB-Pokal", campeon: "RB Leipzig" },
  { anio: "2023", torneo: "DFB-Pokal", campeon: "RB Leipzig" },
  { anio: "2024", torneo: "DFB-Pokal", campeon: "Bayer Leverkusen" }
];

const supercopa = [
  { anio: "1987", torneo: "Supercopa de Alemania", campeon: "Bayern Munich" },
  { anio: "1988", torneo: "Supercopa de Alemania", campeon: "Werder Bremen" },
  { anio: "1989", torneo: "Supercopa de Alemania", campeon: "Borussia Dortmund" },
  { anio: "1990", torneo: "Supercopa de Alemania", campeon: "Bayern Munich" },
  { anio: "1991", torneo: "Supercopa de Alemania", campeon: "1. FC Kaiserslautern" },
  { anio: "1992", torneo: "Supercopa de Alemania", campeon: "VfB Stuttgart" },
  { anio: "1993", torneo: "Supercopa de Alemania", campeon: "Werder Bremen" },
  { anio: "1994", torneo: "Supercopa de Alemania", campeon: "Werder Bremen" },
  { anio: "1995", torneo: "Supercopa de Alemania", campeon: "Borussia Dortmund" },
  { anio: "1996", torneo: "Supercopa de Alemania", campeon: "Borussia Dortmund" },
  { anio: "2010", torneo: "Supercopa de Alemania", campeon: "Bayern Munich" },
  { anio: "2011", torneo: "Supercopa de Alemania", campeon: "Schalke 04" },
  { anio: "2012", torneo: "Supercopa de Alemania", campeon: "Bayern Munich" },
  { anio: "2013", torneo: "Supercopa de Alemania", campeon: "Borussia Dortmund" },
  { anio: "2014", torneo: "Supercopa de Alemania", campeon: "Borussia Dortmund" },
  { anio: "2015", torneo: "Supercopa de Alemania", campeon: "VfL Wolfsburg" },
  { anio: "2016", torneo: "Supercopa de Alemania", campeon: "Bayern Munich" },
  { anio: "2017", torneo: "Supercopa de Alemania", campeon: "Bayern Munich" },
  { anio: "2018", torneo: "Supercopa de Alemania", campeon: "Bayern Munich" },
  { anio: "2019", torneo: "Supercopa de Alemania", campeon: "Borussia Dortmund" },
  { anio: "2020", torneo: "Supercopa de Alemania", campeon: "Bayern Munich" },
  { anio: "2021", torneo: "Supercopa de Alemania", campeon: "Bayern Munich" },
  { anio: "2022", torneo: "Supercopa de Alemania", campeon: "Bayern Munich" },
  { anio: "2023", torneo: "Supercopa de Alemania", campeon: "RB Leipzig" },
  { anio: "2024", torneo: "Supercopa de Alemania", campeon: "Bayer Leverkusen" }
];

const ligaPokal = [
  { anio: "1997", torneo: "Copa de la Liga de Alemania", campeon: "Bayern Munich" },
  { anio: "1998", torneo: "Copa de la Liga de Alemania", campeon: "Bayern Munich" },
  { anio: "1999", torneo: "Copa de la Liga de Alemania", campeon: "Bayern Munich" },
  { anio: "2000", torneo: "Copa de la Liga de Alemania", campeon: "Bayern Munich" },
  { anio: "2001", torneo: "Copa de la Liga de Alemania", campeon: "Hertha BSC" },
  { anio: "2002", torneo: "Copa de la Liga de Alemania", campeon: "Hertha BSC" },
  { anio: "2003", torneo: "Copa de la Liga de Alemania", campeon: "Hamburger SV" },
  { anio: "2004", torneo: "Copa de la Liga de Alemania", campeon: "Bayern Munich" },
  { anio: "2005", torneo: "Copa de la Liga de Alemania", campeon: "Schalke 04" },
  { anio: "2006", torneo: "Copa de la Liga de Alemania", campeon: "Werder Bremen" },
  { anio: "2007", torneo: "Copa de la Liga de Alemania", campeon: "Bayern Munich" }
];

const todo = [...ligas, ...dfbPokal, ...supercopa, ...ligaPokal];

const buildHistory = todo.map(t => {
    // Generate id
    const tSlug = t.torneo.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\s+/g, '-');
    return {
       id: `${t.anio}-${tSlug}`,
       anio: t.anio,
       torneo: t.torneo,
       campeon: t.campeon,
       tabla_posiciones: []
    };
});

fs.writeFileSync(FILE_PATH, JSON.stringify(buildHistory, null, 2), 'utf-8');
console.log('Alemania temporadas generated. Total matches:', buildHistory.length);
